# Generated by Django 6.0.5 on 2026-05-25 21:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_commission_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "manager_commission_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=5
                    ),
                ),
                (
                    "loan_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.50"), max_digits=5
                    ),
                ),
                ("spin_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business setting",
                "verbose_name_plural": "Business settings",
            },
        ),
    ]
