# Generated by Django 6.0.5 on 2026-05-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(default="MW", max_length=10, unique=True)),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minutes a rep must wait between claiming applications.",
                    ),
                ),
                (
                    "max_active_applications",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum applications a rep can have active at once.",
                    ),
                ),
                (
                    "polling_interval_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="How often the home page polls for queue status (seconds).",
                    ),
                ),
                (
                    "inactive_pause_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutes of inactivity before polling pauses.",
                    ),
                ),
                (
                    "waiting_edit_grace_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutes an application can wait for customer edits before it stops counting toward the rep's active limit.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Queue rule",
                "verbose_name_plural": "Queue rules",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Application Approved"),
                            ("reject", "Application Rejected"),
                            ("payment_status_change", "Payment Status Changed"),
                            ("device_lock", "Device Locked"),
                            ("device_unlock", "Device Unlocked"),
                            ("kyc_change", "KYC Document Changed"),
                            ("contract_create", "Contract Created"),
                            ("claim_application", "Application Claimed"),
                            ("payout_request", "Payout Requested"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"],
                        name="core_auditl_action_096de0_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="core_auditl_object__42e4a9_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_auditl_user_id_7b678c_idx",
                    ),
                ],
            },
        ),
    ]
