# Generated by Django 6.0.5 on 2026-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_queuerule_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Application Approved"),
                    ("reject", "Application Rejected"),
                    ("payment", "Payment Applied"),
                    ("payment_status_change", "Payment Status Changed"),
                    ("device_lock", "Device Locked"),
                    ("device_unlock", "Device Unlocked"),
                    ("device_enroll", "Device Enrolled"),
                    ("kyc_change", "KYC Document Changed"),
                    ("contract_create", "Contract Created"),
                    ("claim_application", "Application Claimed"),
                    ("payout_request", "Payout Requested"),
                    ("webhook_received", "Webhook Received"),
                ],
                max_length=40,
            ),
        ),
    ]
