# Generated by Django 4.2.23 on 2025-09-10 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('demand_growth_pct', models.FloatField(default=0)),
                ('price_change_pct', models.FloatField(default=0)),
                ('base_price', models.FloatField(default=100.0)),
                ('unit_cost', models.FloatField(default=60.0)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('reorder_point', models.PositiveIntegerField(default=10)),
                ('initial_stock', models.PositiveIntegerField(default=50)),
                ('horizon_days', models.PositiveIntegerField(default=30)),
                ('op_ex_pct_of_revenue', models.FloatField(default=10.0)),
                ('tax_rate_pct', models.FloatField(default=25.0)),
                ('ar_days', models.PositiveIntegerField(default=7)),
                ('ap_days', models.PositiveIntegerField(default=7)),
                ('opening_cash', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulator.scenario')),
            ],
        ),
    ]
