# Generated by Django 4.2.23 on 2025-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_backfill_trials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='businesssubscription',
            index=models.Index(fields=['status'], name='billing_bus_status_94d10c_idx'),
        ),
        migrations.AddIndex(
            model_name='businesssubscription',
            index=models.Index(fields=['business'], name='billing_bus_busines_4f49db_idx'),
        ),
        migrations.AddIndex(
            model_name='businesssubscription',
            index=models.Index(fields=['plan', 'status'], name='billing_bus_plan_id_0595dc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['code'], name='billing_sub_code_58051a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active', 'sort_order'], name='billing_sub_is_acti_3b86b6_idx'),
        ),
    ]
