# Generated by Django 5.2.5 on 2025-12-02 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_businesssubscription_canceled_at_and_more"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscription",
            name="pesapal_merchant_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pesapal merchant reference",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="pesapal_order_tracking_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pesapal order tracking ID",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, default="", help_text="Stripe customer ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe subscription ID",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="businesssubscription",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("airtel", "Airtel Money"),
                    ("standard_bank", "Standard Bank"),
                    ("card", "Card (VISA/Mastercard)"),
                    ("stripe", "Stripe"),
                    ("pesapal", "Pesapal"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("airtel", "Airtel Money"),
                    ("standard_bank", "Standard Bank"),
                    ("card", "Card (VISA/Mastercard)"),
                    ("stripe", "Stripe"),
                    ("pesapal", "Pesapal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="kind",
            field=models.CharField(
                choices=[
                    ("airtel", "Airtel Money"),
                    ("standard_bank", "Standard Bank"),
                    ("card", "Card"),
                    ("stripe", "Stripe"),
                    ("pesapal", "Pesapal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="businesssubscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="billing_bus_stripe__8dd88f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businesssubscription",
            index=models.Index(
                fields=["pesapal_order_tracking_id"],
                name="billing_bus_pesapal_65f080_idx",
            ),
        ),
    ]
