# Generated by Django 5.2.5 on 2025-12-30 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_businesssubscription_pesapal_merchant_reference_and_more"),
        ("inventory", "1008_alter_archivebatch_counts_snapshot"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("airtel", "Airtel Money"),
                    ("standard_bank", "Standard Bank"),
                    ("card", "Card (VISA/Mastercard)"),
                    ("stripe", "Stripe"),
                    ("pesapal", "Pesapal"),
                    ("paychangu", "PayChangu"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(db_index=True, default="paychangu", max_length=20),
                ),
                (
                    "tx_ref",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="MWK", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                (
                    "raw_init_payload",
                    models.JSONField(blank=True, default=dict, help_text="Response from initiate API"),
                ),
                (
                    "raw_webhook_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Webhook notification payload",
                    ),
                ),
                (
                    "raw_verify_payload",
                    models.JSONField(blank=True, default=dict, help_text="Response from verify API"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "created_at"],
                        name="billing_pay_busines_26dc58_idx",
                    ),
                    models.Index(
                        fields=["provider", "status"],
                        name="billing_pay_provide_5211d9_idx",
                    ),
                    models.Index(fields=["tx_ref"], name="billing_pay_tx_ref_825c74_idx"),
                ],
            },
        ),
    ]
