# Generated by Django 5.2.5 on 2026-01-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_add_paychangu_provider_and_transaction_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="charge_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="PayChangu charge ID for mobile money direct charge",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Payment method: airtel, tnm, card, etc.",
                max_length=30,
            ),
        ),
    ]
