# Generated by Django 5.2.5 on 2026-01-03 13:28

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_add_charge_id_and_payment_method"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paychangu", "PayChangu"),
                            ("stripe", "Stripe"),
                            ("pesapal", "Pesapal"),
                            ("airtel", "Airtel Money"),
                            ("tnm", "TNM Mpamba"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Provider's event ID if available",
                        max_length=255,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Computed hash: provider + tx_ref + event_type + amount + currency",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Transaction reference (tx_ref, payment_id, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Alternative transaction identifier",
                        max_length=255,
                    ),
                ),
                ("event_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "payload_json",
                    models.JSONField(blank=True, default=dict, help_text="Raw webhook payload"),
                ),
                (
                    "signature_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether webhook signature was verified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="provider_customer_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Payment provider customer ID (PayChangu customer, Stripe customer, etc.)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="provider_subscription_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Payment provider subscription ID (if provider manages recurring billing)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_at",
            field=models.DateTimeField(blank=True, help_text="When payment is due (with time)", null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issued_at",
            field=models.DateTimeField(blank=True, help_text="When invoice was issued/finalized", null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Generated PDF invoice file",
                null=True,
                upload_to="invoices/pdfs/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, help_text="When PDF was last generated", null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="provider_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Payment provider transaction reference (PayChangu tx_ref, Stripe payment_intent, etc.)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated subscription if this is a recurring billing invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.businesssubscription",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Tax amount (alias for tax_amount)",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="businesssubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("grace", "Grace"),
                    ("suspended", "Suspended"),
                    ("canceled", "Canceled"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("void", "Void"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="businesssubscription",
            index=models.Index(fields=["provider_customer_ref"], name="billing_bus_provide_8795f6_idx"),
        ),
        migrations.AddIndex(
            model_name="businesssubscription",
            index=models.Index(
                fields=["provider_subscription_ref"],
                name="billing_bus_provide_ac90e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businesssubscription",
            index=models.Index(
                fields=["status", "current_period_end"],
                name="billing_bus_status_a1984a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businesssubscription",
            index=models.Index(fields=["status", "trial_end"], name="billing_bus_status_28f823_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["subscription"], name="billing_inv_subscri_d72937_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["provider_reference"], name="billing_inv_provide_cba455_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status", "due_date"], name="billing_inv_status_996e80_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["provider", "reference"], name="billing_pay_provide_44d31d_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["provider", "status"], name="billing_pay_provide_a62a5e_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["status", "received_at"], name="billing_pay_status_1540b9_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["idempotency_key"], name="billing_pay_idempot_0db0ec_idx"),
        ),
    ]
