# Generated by Django 5.2.5 on 2026-01-03 16:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_add_payment_event_and_enhance_invoice"),
        ("tenants", "0019_add_section_flags_with_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionChangeIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_plan_code", models.CharField(max_length=50)),
                ("to_plan_code", models.CharField(max_length=50)),
                (
                    "from_plan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "to_plan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to pay for upgrade (difference between plans)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="MWK", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("applied", "Applied"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paychangu_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "tx_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_change_intents",
                        to="tenants.business",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_intents",
                        to="billing.businesssubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "status"],
                        name="billing_sub_busines_b50f3c_idx",
                    ),
                    models.Index(
                        fields=["subscription", "status"],
                        name="billing_sub_subscri_1b93b4_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="billing_sub_status_d6c7f6_idx",
                    ),
                    models.Index(
                        fields=["paychangu_reference"],
                        name="billing_sub_paychan_ff2a3e_idx",
                    ),
                    models.Index(
                        fields=["tx_ref"], name="billing_sub_tx_ref_b1e36d_idx"
                    ),
                ],
            },
        ),
    ]
