# Generated by Django 5.2.5 on 2026-01-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0009_add_subscription_change_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="failure_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for payment failure (if status is FAILED)",
                null=True,
            ),
        ),
    ]
