# Generated by Django 5.2.5 on 2026-01-05 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_add_dunning_and_cancellation_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="billingattempt",
            new_name="billing_bil_invoice_0a3d6e_idx",
            old_name="billing_bil_invoice_idx",
        ),
        migrations.RenameIndex(
            model_name="billingattempt",
            new_name="billing_bil_subscri_17f312_idx",
            old_name="billing_bil_subscri_idx",
        ),
        migrations.RenameIndex(
            model_name="billingattempt",
            new_name="billing_bil_status_a6245f_idx",
            old_name="billing_bil_status_idx",
        ),
    ]
