# Generated by Django 5.2.5 on 2026-01-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "billing",
            "0012_rename_billing_bil_invoice_idx_billing_bil_invoice_0a3d6e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscription",
            name="cancel_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When cancel_at_period_end was set (user requested cancellation)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="hq_notified_cancel_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When HQ was notified of cancellation request (idempotency)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="hq_notified_canceled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When HQ was notified of effective cancellation (idempotency)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="hq_notified_suspended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When HQ was notified of suspension (idempotency)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="hq_notified_paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When HQ was notified of payment (idempotency)",
                null=True,
            ),
        ),
    ]
