# Generated by Django 5.2.5 on 2026-01-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_add_pending_checkout"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pendingcheckout",
            new_name="billing_pen_busines_dc3b9f_idx",
            old_name="billing_pen_busines_idx",
        ),
        migrations.RenameIndex(
            model_name="pendingcheckout",
            new_name="billing_pen_tx_ref_2afe1e_idx",
            old_name="billing_pen_tx_ref_idx",
        ),
    ]
