# Generated by Django 5.2.5 on 2026-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_ensure_default_trial_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_send_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of email send attempts"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When invoice confirmation email was sent (idempotency)",
                null=True,
            ),
        ),
    ]
