# Generated by Django 5.2.5 on 2026-04-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_add_invoice_email_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionchangeintent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
