services:
  - type: web
    name: circuitcity-main
    env: python
    plan: free
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=cc.settings
      python manage.py migrate --noinput --settings=cc.settings

    startCommand: >
      gunicorn --chdir /opt/render/project/src
      cc.wsgi:application
      --workers=${WEB_CONCURRENCY:-2} --threads=4 --timeout=120 --log-file -
