services:
  - type: web
    name: circuitcity-main
    env: python
    plan: starter
    autoDeploy: true

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput

    startCommand: gunicorn cc.wsgi:application --preload --workers=3 --timeout=120 --bind 0.0.0.0:$PORT

    # Your urls.py exposes /healthz (200 OK). Use that for Render's health check.
    healthCheckPath: /healthz

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: cc.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      # Ensure hosted env uses Postgres (not local SQLite)
      - key: FORCE_SQLITE
        value: "0"
      # Allow HTTP for health checks before redirects kick in
      - key: HEALTHZ_ALLOW_HTTP
        value: "1"
      # Safe defaults; add your custom domain later if needed
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"

      # Pull the Postgres connection string from the database defined below.
      - key: DATABASE_URL
        fromDatabase:
          name: circuitcity-db
          property: connectionString

databases:
  - name: circuitcity-db
    plan: free
