# Generated by Django 5.2.5 on 2025-12-15 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=80)),
                ("query", models.JSONField(default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "base",
                    models.CharField(
                        default="MWK",
                        help_text="Base currency (locked to MWK)",
                        max_length=3,
                    ),
                ),
                (
                    "quote",
                    models.CharField(
                        default="USD",
                        help_text="Quote currency (locked to USD)",
                        max_length=3,
                    ),
                ),
                (
                    "mwk_per_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Exchange rate: 1 USD = mwk_per_usd MWK (e.g., 1750.00 means 1 USD = 1750 MWK)",
                        max_digits=12,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this rate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exchange_rate_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_exchangerate",
                "ordering": ["-updated_at"],
                "unique_together": {("base", "quote")},
            },
        ),
    ]
