# Generated by Django 4.2.23 on 2025-09-11 09:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaybyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(db_index=True, max_length=32)),
                ('customer_id', models.CharField(blank=True, default='', help_text='NatID/Passport/etc', max_length=64)),
                ('product_name', models.CharField(max_length=160)),
                ('product_sku', models.CharField(blank=True, default='', max_length=80)),
                ('product_serial', models.CharField(blank=True, default='', max_length=80)),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_date', models.DateField(blank=True, help_text='Expected full-payment date', null=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('ACTIVE', 'Active'), ('DELINQUENT', 'Delinquent'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered')], default='RESERVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layby_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LaybyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(choices=[('AIRTEL', 'Airtel Money'), ('TNM', 'TNM Mpamba'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='AIRTEL', max_length=12)),
                ('provider_ref', models.CharField(blank=True, default='', help_text='Txn ID from Airtel/TNM/Bank', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='layby.laybyorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layby_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
