# Generated by Django 4.2.23 on 2025-09-11 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laybyorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='laybypayment',
            options={'ordering': ['-received_at']},
        ),
        migrations.RenameField(
            model_name='laybyorder',
            old_name='agent',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='laybyorder',
            old_name='deposit',
            new_name='deposit_amount',
        ),
        migrations.RenameField(
            model_name='laybyorder',
            old_name='product_name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='laybyorder',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='laybyorder',
            name='product_serial',
        ),
        migrations.RemoveField(
            model_name='laybyorder',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='laybyorder',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='laybyorder',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='laybyorder',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='laybyorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='laybypayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='laybypayment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='laybypayment',
            name='provider_ref',
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='ref',
            field=models.CharField(default='LBY-000000', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='sku',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='term_months',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laybypayment',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='laybypayment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Money'), ('bank', 'Bank Transfer')], default='cash', max_length=16),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='layby.laybyorder'),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='received_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='layby_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
