# Generated by Django 4.2.24 on 2025-09-12 23:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import layby.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layby', '0002_alter_laybyorder_options_alter_laybypayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laybyorder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='laybypayment',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='id_number',
            field=models.CharField(default=0, help_text='Enter exactly 8 digits', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'ID number must be exactly 8 digits.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='layby/id_photos/'),
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='kin1_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='kin1_phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='kin2_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='kin2_phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='laybyorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layby_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='ref',
            field=models.CharField(default=layby.models._generate_ref, editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='sku',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='term_months',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='laybyorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='method',
            field=models.CharField(default='cash', max_length=24),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='layby.laybyorder'),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='laybypayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='laybyorder',
            index=models.Index(fields=['ref'], name='layby_layby_ref_785a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='laybyorder',
            index=models.Index(fields=['sku'], name='layby_layby_sku_8c1f27_idx'),
        ),
        migrations.AddIndex(
            model_name='laybyorder',
            index=models.Index(fields=['status'], name='layby_layby_status_06c311_idx'),
        ),
        migrations.AddIndex(
            model_name='laybyorder',
            index=models.Index(fields=['created_at'], name='layby_layby_created_9cf5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='laybyorder',
            index=models.Index(fields=['status', 'created_by'], name='layby_layby_status_c390b7_idx'),
        ),
        migrations.AddIndex(
            model_name='laybypayment',
            index=models.Index(fields=['received_at'], name='layby_layby_receive_d5aff3_idx'),
        ),
        migrations.AddIndex(
            model_name='laybypayment',
            index=models.Index(fields=['order', 'received_at'], name='layby_layby_order_i_a3b5cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='laybyorder',
            constraint=models.CheckConstraint(check=models.Q(('term_months__gte', 1), ('term_months__lte', 12)), name='layby_term_1_to_12'),
        ),
        migrations.AddConstraint(
            model_name='laybyorder',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='layby_total_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='laybyorder',
            constraint=models.CheckConstraint(check=models.Q(('deposit_amount__gte', 0)), name='layby_deposit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='laybypayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='layby_payment_amount_positive'),
        ),
    ]
