# inventory/utils_verticals.py
"""
Vertical-specific routing and configuration utilities.
Ensures business-kind-aware dashboards, navigation, and onboarding flows.
"""
from __future__ import annotations

from typing import Dict, List, Optional, Tuple

try:
    from inventory.business_kinds import BusinessKind
except ImportError:
    # Fallback if business_kinds isn't available
    class BusinessKind:
        PHONES = "phones"
        LIQUOR = "liquor"
        GROCERY = "grocery"
        PHARMACY = "pharmacy"
        CLOTHING = "clothing"
        GYM = "gym"


def get_vertical_kind(business) -> str:
    """
    Returns a normalized vertical code for the given business.

    Args:
        business: Business model instance (or None)

    Returns:
        str: One of "phones", "gym", "clothing", "liquor", "pharmacy", "grocery", "hardware", "cement", or "generic"
    """
    if business is None:
        return "generic"

    kind = getattr(business, "business_kind", None)
    if not kind:
        return "generic"  # No business_kind set = generic minimal nav

    # Normalize to lowercase string
    if hasattr(kind, "value"):
        kind = kind.value
    kind = str(kind).strip().lower()

    # Map to known verticals
    valid_kinds = ["phones", "gym", "clothing", "liquor", "pharmacy", "grocery", "hardware", "cement", "farm", "welding", "car_hire"]
    if kind in valid_kinds:
        return kind

    return "generic"  # Unknown vertical = generic minimal nav


def get_vertical_dashboard_url(vertical_kind: str) -> Optional[str]:
    """
    Returns the named URL for a vertical-specific dashboard.

    Args:
        vertical_kind: Vertical code (e.g., "gym", "pharmacy")

    Returns:
        str: URL name to redirect to, or None if default dashboard should be used
    """
    vertical_dashboard_map = {
        "gym": "verticals:gym_dashboard",
        "pharmacy": "verticals:pharmacy_hub",
        "clothing": "verticals:clothing_dashboard",
        "liquor": "verticals:liquor_dashboard",
        "grocery": "groceries:dashboard",
        "hardware": "inventory:generic_dashboard",  # Hardware uses generic retail dashboard
        "cement": "verticals:cement_dashboard",  # Cement has its own dashboard
        "farm": "verticals:farm_dashboard",  # Farm vertical
        "welding": "verticals:welding_dashboard",  # Welding vertical
        "car_hire": "verticals:car_hire_dashboard",  # Car Hire Service vertical
        "generic": "inventory:generic_dashboard",  # Fallback for unrecognized verticals
        # "phones" uses the default dashboard at /inventory/dashboard/
    }
    return vertical_dashboard_map.get(vertical_kind)


def get_onboarding_steps(vertical_kind: str, request=None) -> List[Dict[str, str]]:
    """
    Returns onboarding steps tailored to the business vertical.

    Args:
        vertical_kind: Vertical code (e.g., "gym", "pharmacy")
        request: Optional HttpRequest for URL resolution

    Returns:
        List of dicts with keys: 'number', 'label', 'url', 'icon'
    """

    # Helper to safely resolve URLs
    def safe_url(name: str, fallback: str = "#") -> str:
        if request is None:
            return fallback
        try:
            from django.urls import reverse

            return reverse(name)
        except Exception:
            return fallback

    if vertical_kind == "gym":
        return [
            {
                "number": "1",
                "label": "Add membership plans",
                "url": safe_url("inventory:gym_plans", "/inventory/gym/plans/"),
                "icon": "bi-calendar-check",
            },
            {
                "number": "2",
                "label": "Add your first members",
                "url": safe_url("inventory:gym_members", "/inventory/gym/members/"),
                "icon": "bi-people",
            },
            {
                "number": "3",
                "label": "Track payments & arrears",
                "url": safe_url("inventory:gym_dashboard", "/inventory/gym/dashboard/"),
                "icon": "bi-wallet2",
            },
        ]

    elif vertical_kind == "clothing":
        return [
            {
                "number": "1",
                "label": "Add clothing products",
                "url": safe_url("inventory:clothing_product_new", "/inventory/clothing/products/new/"),
                "icon": "bi-bag",
            },
            {
                "number": "2",
                "label": "Set up sizes & colors",
                "url": safe_url("inventory:clothing_stock_list", "/inventory/clothing/stock/"),
                "icon": "bi-palette",
            },
            {
                "number": "3",
                "label": "Start selling",
                "url": safe_url("inventory:clothing_sell", "/inventory/clothing/sell/"),
                "icon": "bi-cart-check",
            },
        ]

    elif vertical_kind == "liquor":
        return [
            {
                "number": "1",
                "label": "Add liquor products",
                "url": safe_url("inventory:liquor_product_new", "/inventory/liquor/products/new/"),
                "icon": "bi-cup-straw",
            },
            {
                "number": "2",
                "label": "Stock in inventory",
                "url": safe_url("inventory:liquor_stock_list", "/inventory/liquor/stock/"),
                "icon": "bi-boxes",
            },
            {
                "number": "3",
                "label": "Record sales",
                "url": safe_url("inventory:liquor_sell", "/inventory/liquor/sell/"),
                "icon": "bi-receipt",
            },
        ]

    elif vertical_kind == "pharmacy":
        return [
            {
                "number": "1",
                "label": "Add products with categories",
                "url": safe_url("pharmacy:stock_in", "/pharmacy/stock-in/"),
                "icon": "bi-capsule",
            },
            {
                "number": "2",
                "label": "Start selling products",
                "url": safe_url("pharmacy:sell", "/pharmacy/sell/"),
                "icon": "bi-bag-check",
            },
            {
                "number": "3",
                "label": "Track sales & analytics",
                "url": safe_url("verticals:pharmacy_dashboard", "/verticals/pharmacy/"),
                "icon": "bi-graph-up",
            },
        ]

    else:  # "phones" or default
        return [
            {
                "number": "1",
                "label": "Add your first product",
                "url": safe_url("inventory:product_new", "/inventory/products/new/"),
                "icon": "bi-phone",
            },
            {
                "number": "2",
                "label": "Stock in items",
                "url": safe_url("inventory:scan_in", "/inventory/scan-in/"),
                "icon": "bi-upc-scan",
            },
            {
                "number": "3",
                "label": "Invite/approve agents",
                "url": safe_url("tenants:manager_review_agents", "/tenants/manager/agents/"),
                "icon": "bi-people",
            },
        ]


def get_vertical_display_name(vertical_kind: str) -> str:
    """
    Returns human-friendly display name for a vertical.

    SINGLE SOURCE OF TRUTH for vertical display names across the entire app.
    Use this function everywhere instead of hardcoding labels.
    """
    display_names = {
        "phones": "Phones & Electronics",
        "gym": "Gym & Fitness",
        "clothing": "Clothing Store",
        "liquor": "Liquor Store",
        "pharmacy": "Pharmacy & Cosmetics",
        "grocery": "Grocery Store",
        "hardware": "Hardware & General Dealers",  # NEW: Hardware vertical
        "cement": "Cement / Building Materials",  # Legacy: Cement vertical
        "farm": "Farm Manager",  # Farm profitability tracking
        "welding": "Welding Workshop",  # Welding job estimation
        "car_hire": "Car Hire Service",  # Vehicle rental and fleet management
        "generic": "Business",
    }
    return display_names.get(vertical_kind, vertical_kind.title())


def get_vertical_sidebar_items(business_kind: str) -> list[dict]:
    """
    Returns a list of sidebar navigation items for the given business kind.

    Each item is a dict with keys:
        - section: str (e.g., "MAIN", "TIME", "MONEY", "BUSINESS", "LAYBY")
        - key: str (unique identifier for the item, e.g., "dashboard", "analytics")
        - url: str (URL or named route)
        - label: str (display label)
        - icon: str (Bootstrap icon class, e.g., "bi-speedometer2")
        - active_prefix: str (URL prefix for active state matching)
        - active_pattern: str (alias for active_prefix, for backward compatibility)
        - is_menu: bool (default False, True if item opens menu drawer)
        - is_header: bool (default False, True if item is a section header)
        - require_manager: bool (default False, True if item requires manager role)
        - group: str (optional, "more" for items in collapsible More section)

    Args:
        business_kind: Vertical code (e.g., "phones", "gym", "clothing", "liquor", "pharmacy", "cement", "generic")

    Returns:
        List of nav items organized by section
    """
    # CRITICAL: Handle None/unknown business_kind FIRST (before any vertical-specific nav)
    if business_kind in (None, "", "generic", "none"):
        return [
            # Minimal nav for businesses without a vertical set
            {
                "section": "MAIN",
                "key": "home",
                "url": "verticals:no_business",
                "label": "Home",
                "icon": "bi-house",
                "active_prefix": "/verticals/none",
                "active_pattern": "/verticals/none",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "settings",
                "url": "settings_root",
                "label": "Business Settings",
                "icon": "bi-gear",
                "active_prefix": "/settings/",
                "active_pattern": "/settings/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
            },
        ]

    if business_kind == "gym":
        return [
            # MAIN section - gym-specific operations (membership-based, NOT inventory)
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "verticals:gym_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/verticals/gym/",
                "active_pattern": "/verticals/gym/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "app_router:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/app/analytics",
                "active_pattern": "/app/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # Note: Fast Sell removed - gym is membership-based, not product-based
            {
                "section": "MAIN",
                "key": "members",
                "url": "gym:members_list",
                "label": "Members",
                "icon": "bi-people",
                "active_prefix": "/gym/members/",
                "active_pattern": "/gym/members/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "checkin",
                "url": "gym:checkin_page",
                "label": "Member Check-ins",
                "icon": "bi-clipboard-check",
                "active_prefix": "/gym/checkin",
                "active_pattern": "/gym/checkin",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section - Collapsible tools (Wallet & Time Logs accessible to all, manager tools below)
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "reports",
                "url": "reports:home",
                "label": "Reports",
                "icon": "bi-file-earmark-bar-graph",
                "active_prefix": "/reports/",
                "active_pattern": "/reports/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "simulator",
                "url": "simulator:business_home",
                "label": "Simulator",
                "icon": "bi-cpu",
                "active_prefix": "/simulator/business/",
                "active_pattern": "/simulator/business/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "costs",
                "url": "wallet:admin_cost_list",
                "label": "Costs",
                "icon": "bi-cash-stack",
                "active_prefix": "/wallet/admin/costs/",
                "active_pattern": "/wallet/admin/costs/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "trainers",
                "url": "tenants:manager_review_agents",
                "label": "Trainers",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "backups",
                "url": "backups:manager_list",
                "label": "Data Backup",
                "icon": "bi-cloud-download",
                "active_prefix": "/backups/",
                "active_pattern": "/backups/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing_checkout",
                "url": "billing:checkout",
                "label": "Billing Checkout",
                "icon": "bi-cart-check",
                "active_prefix": "/billing/checkout",
                "active_pattern": "/billing/checkout",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "clothing":
        return [
            # MAIN section
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "verticals:clothing_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/verticals/clothing/dashboard",
                "active_pattern": "/verticals/clothing/dashboard",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "app_router:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/app/analytics",
                "active_pattern": "/app/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "fast_sell",
                "url": "verticals:clothing_fast_sell",
                "label": "Fast Sell",
                "icon": "bi-lightning-charge",
                "active_prefix": "/verticals/clothing/fast-sell",
                "active_pattern": "/verticals/clothing/fast-sell",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "hub",
                "url": "verticals:clothing_hub",
                "label": "Clothing Hub",
                "icon": "bi-person-bounding-box",
                "active_prefix": "/verticals/clothing/hub",
                "active_pattern": "/verticals/clothing/hub",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "add_product",
                "url": "inventory:clothing_wizard",
                "label": "Add Product",
                "icon": "bi-plus-square",
                "active_prefix": "/inventory/wizard/clothing",
                "active_pattern": "/inventory/wizard/clothing",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "scan_in",
                "url": "verticals:clothing_scan_in",
                "label": "Scan IN",
                "icon": "bi-upc-scan",
                "active_prefix": "/verticals/clothing/scan-in",
                "active_pattern": "/verticals/clothing/scan-in",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "sell",
                "url": "verticals:clothing_sell",
                "label": "Sell",
                "icon": "bi-bag-check",
                "active_prefix": "/verticals/clothing/sell",
                "active_pattern": "/verticals/clothing/sell",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section - Collapsible tools (Wallet & Time Logs accessible to all, manager tools below)
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "reports",
                "url": "reports:home",
                "label": "Reports",
                "icon": "bi-file-earmark-bar-graph",
                "active_prefix": "/reports/",
                "active_pattern": "/reports/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "simulator",
                "url": "simulator:business_home",
                "label": "Simulator",
                "icon": "bi-cpu",
                "active_prefix": "/simulator/business/",
                "active_pattern": "/simulator/business/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "costs",
                "url": "wallet:admin_cost_list",
                "label": "Costs",
                "icon": "bi-cash-stack",
                "active_prefix": "/wallet/admin/costs/",
                "active_pattern": "/wallet/admin/costs/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "agents",
                "url": "tenants:manager_review_agents",
                "label": "Agents",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-agents",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "backups",
                "url": "backups:manager_list",
                "label": "Data Backup",
                "icon": "bi-cloud-download",
                "active_prefix": "/backups/",
                "active_pattern": "/backups/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "orders",
                "url": "inventory:orders_list",
                "label": "Orders",
                "icon": "bi-clipboard-data",
                "active_prefix": "/inventory/orders/",
                "active_pattern": "/inventory/orders/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "liquor":
        return [
            # MAIN section
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "verticals:liquor_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/verticals/liquor/",
                "active_pattern": "/verticals/liquor/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "app_router:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/app/analytics",
                "active_pattern": "/app/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # Note: Fast Sell removed - liquor uses dedicated sell flow with barman attribution
            {
                "section": "MAIN",
                "key": "hub",
                "url": "liquor:inventory_dashboard",
                "label": "Liquor Hub",
                "icon": "bi-cup-straw",
                "active_prefix": "/liquor/inventory/",
                "active_pattern": "/liquor/inventory/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "stock",
                "url": "liquor:stock_overview",
                "label": "Stock",
                "icon": "bi-box-seam",
                "active_prefix": "/liquor/stock/",
                "active_pattern": "/liquor/stock/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # PHASE 6: Agent Assignment
            {
                "section": "MAIN",
                "key": "my_stock",
                "url": "liquor:my_stock",
                "label": "My Stock",
                "icon": "bi-bag-check",
                "active_prefix": "/liquor/my-stock/",
                "active_pattern": "/liquor/my-stock/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-liquor-my-stock",
            },
            {
                "section": "MAIN",
                "key": "assignments",
                "url": "liquor:assignment_list",
                "label": "Assignments",
                "icon": "bi-clipboard-check",
                "active_prefix": "/liquor/assignments/",
                "active_pattern": "/liquor/assignments/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-liquor-assignments",
            },
            {
                "section": "MAIN",
                "key": "reconciliation",
                "url": "liquor:reconciliation",
                "label": "Reconciliation",
                "icon": "bi-calculator",
                "active_prefix": "/liquor/reconciliation/",
                "active_pattern": "/liquor/reconciliation/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-liquor-reconciliation",
            },
            {
                "section": "MAIN",
                "key": "performance",
                "url": "liquor:agent_performance",
                "label": "Performance",
                "icon": "bi-trophy",
                "active_prefix": "/liquor/performance/",
                "active_pattern": "/liquor/performance/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-liquor-performance",
            },
            {
                "section": "MAIN",
                "key": "add_product",
                "url": "inventory:liquor_wizard",
                "label": "Add Product",
                "icon": "bi-droplet-half",
                "active_prefix": "/inventory/wizard/liquor",
                "active_pattern": "/inventory/wizard/liquor",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "scan_in",
                "url": "liquor:scan_in",
                "label": "Scan In",
                "icon": "bi-upc-scan",
                "active_prefix": "/liquor/scan-in",
                "active_pattern": "/liquor/scan-in",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "sell",
                "url": "liquor:sell",
                "label": "Sell",
                "icon": "bi-lightning-charge",
                "active_prefix": "/liquor/sell",
                "active_pattern": "/liquor/sell",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MONEY section (keep Credits here - liquor-specific feature)
            {
                "section": "MONEY",
                "key": "credits",
                "url": "liquor:credits_list",
                "label": "Credits",
                "icon": "bi-person-lines-fill",
                "active_prefix": "/liquor/credits/",
                "active_pattern": "/liquor/credits/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section - Collapsible tools (Wallet & Time Logs accessible to all, manager tools below)
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "reports",
                "url": "reports:home",
                "label": "Reports",
                "icon": "bi-file-earmark-bar-graph",
                "active_prefix": "/reports/",
                "active_pattern": "/reports/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "simulator",
                "url": "simulator:business_home",
                "label": "Simulator",
                "icon": "bi-cpu",
                "active_prefix": "/simulator/business/",
                "active_pattern": "/simulator/business/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "costs",
                "url": "wallet:admin_cost_list",
                "label": "Costs",
                "icon": "bi-cash-stack",
                "active_prefix": "/wallet/admin/costs/",
                "active_pattern": "/wallet/admin/costs/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "agents",
                "url": "tenants:manager_review_agents",
                "label": "Agents",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-agents",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "backups",
                "url": "backups:manager_list",
                "label": "Data Backup",
                "icon": "bi-cloud-download",
                "active_prefix": "/backups/",
                "active_pattern": "/backups/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "pharmacy":
        return [
            # MAIN section - pharmacy & cosmetics vertical-aware flows
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "dashboard:home",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/dashboard/",
                "active_pattern": "/dashboard/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "app_router:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/app/analytics",
                "active_pattern": "/app/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "fast_sell",
                "url": "verticals:pharmacy_fast_sell",
                "label": "Fast Sell",
                "icon": "bi-lightning-charge-fill",
                "active_prefix": "/verticals/pharmacy/fast-sell",
                "active_pattern": "/verticals/pharmacy/fast-sell",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "hub",
                "url": "verticals:pharmacy_hub",
                "label": "Pharmacy & Cosmetics Hub",
                "icon": "bi-grid-3x3-gap",
                "active_prefix": "/verticals/pharmacy/hub",
                "active_pattern": "/verticals/pharmacy/hub",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "stock_in",
                "url": "pharmacy:stock_in",
                "label": "Stock In",
                "icon": "bi-box-arrow-in-down",
                "active_prefix": "/pharmacy/stock-in",
                "active_pattern": "/pharmacy/stock-in",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "sell",
                "url": "pharmacy:sell",
                "label": "Sell",
                "icon": "bi-bag-check",
                "active_prefix": "/pharmacy/sell",
                "active_pattern": "/pharmacy/sell",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "batches",
                "url": "pharmacy:batch_list",
                "label": "Batches",
                "icon": "bi-boxes",
                "active_prefix": "/pharmacy/batches",
                "active_pattern": "/pharmacy/batches",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section - Collapsible tools (Wallet & Time Logs accessible to all, manager tools below)
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "reports",
                "url": "reports:home",
                "label": "Reports",
                "icon": "bi-file-earmark-bar-graph",
                "active_prefix": "/reports/",
                "active_pattern": "/reports/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "simulator",
                "url": "simulator:business_home",
                "label": "Simulator",
                "icon": "bi-cpu",
                "active_prefix": "/simulator/business/",
                "active_pattern": "/simulator/business/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "costs",
                "url": "wallet:admin_cost_list",
                "label": "Costs",
                "icon": "bi-cash-stack",
                "active_prefix": "/wallet/admin/costs/",
                "active_pattern": "/wallet/admin/costs/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "agents",
                "url": "tenants:manager_review_agents",
                "label": "Agents",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-agents",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "backups",
                "url": "backups:manager_list",
                "label": "Data Backup",
                "icon": "bi-cloud-download",
                "active_prefix": "/backups/",
                "active_pattern": "/backups/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "grocery":
        return [
            # MAIN section - Groceries vertical
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "groceries:dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/groceries/dashboard",
                "active_pattern": "/groceries/dashboard",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "groceries:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/groceries/analytics",
                "active_pattern": "/groceries/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "stock",
                "url": "groceries:stock_list",
                "label": "Stock",
                "icon": "bi-box-seam",
                "active_prefix": "/groceries/stock",
                "active_pattern": "/groceries/stock",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "stock_in",
                "url": "groceries:stock_in",
                "label": "Stock In",
                "icon": "bi-box-arrow-in-down",
                "active_prefix": "/groceries/stock-in",
                "active_pattern": "/groceries/stock-in",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "sell",
                "url": "groceries:sell",
                "label": "Sell",
                "icon": "bi-bag-check",
                "active_prefix": "/groceries/sell",
                "active_pattern": "/groceries/sell",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "agents",
                "url": "tenants:manager_review_agents",
                "label": "Agents",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-agents",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "cement":
        return [
            # MAIN section - Hardware & General Dealers vertical (Premium Experience)
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "verticals:cement_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/verticals/cement/dashboard",
                "active_pattern": "/verticals/cement/dashboard",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "products",
                "url": "cement:products_catalog",
                "label": "Products",
                "icon": "bi-grid-3x3-gap",
                "active_prefix": "/cement/products",
                "active_pattern": "/cement/products",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-hardware-products",
            },
            {
                "section": "MAIN",
                "key": "stock_in",
                "url": "cement:stock_in",
                "label": "Stock In",
                "icon": "bi-box-arrow-in-down",
                "active_prefix": "/cement/stock-in",
                "active_pattern": "/cement/stock-in",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "sell",
                "url": "cement:sell",
                "label": "Sell",
                "icon": "bi-bag-check",
                "active_prefix": "/cement/sell",
                "active_pattern": "/cement/sell",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "stock",
                "url": "cement:stock_list",
                "label": "Stock",
                "icon": "bi-box-seam",
                "active_prefix": "/cement/stock",
                "active_pattern": "/cement/stock",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "costs",
                "url": "cement:costs",
                "label": "Costs",
                "icon": "bi-cash-stack",
                "active_prefix": "/cement/costs",
                "active_pattern": "/cement/costs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "cement:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/cement/analytics",
                "active_pattern": "/cement/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "locations",
                "url": "tenants:manager_locations_list",
                "label": "Locations",
                "icon": "bi-geo-alt",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "agents",
                "url": "tenants:manager_review_agents",
                "label": "Agents",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-agents",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "hardware":
        return [
            # MAIN section - Hardware & General Dealers vertical
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "inventory:generic_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/inventory/generic-dashboard",
                "active_pattern": "/inventory/generic-dashboard",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "app_router:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/app/analytics",
                "active_pattern": "/app/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "stock",
                "url": "inventory:stock_list",
                "label": "Stock",
                "icon": "bi-box-seam",
                "active_prefix": "/inventory/list/",
                "active_pattern": "/inventory/list/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "products",
                "url": "inventory:product_list",
                "label": "Products",
                "icon": "bi-grid-3x3-gap",
                "active_prefix": "/inventory/products/",
                "active_pattern": "/inventory/products/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "scan_in",
                "url": "inventory:scan_in",
                "label": "Scan IN",
                "icon": "bi-upc-scan",
                "active_prefix": "/inventory/scan-in",
                "active_pattern": "/inventory/scan-in",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "sell",
                "url": "inventory:scan_sold",
                "label": "Sell",
                "icon": "bi-bag-check",
                "active_prefix": "/inventory/scan-sold",
                "active_pattern": "/inventory/scan-sold",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section - Collapsible tools (Wallet & Time Logs accessible to all, manager tools below)
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "reports",
                "url": "reports:home",
                "label": "Reports",
                "icon": "bi-file-earmark-bar-graph",
                "active_prefix": "/reports/",
                "active_pattern": "/reports/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "simulator",
                "url": "simulator:business_home",
                "label": "Simulator",
                "icon": "bi-cpu",
                "active_prefix": "/simulator/business/",
                "active_pattern": "/simulator/business/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "costs",
                "url": "wallet:admin_cost_list",
                "label": "Costs",
                "icon": "bi-cash-stack",
                "active_prefix": "/wallet/admin/costs/",
                "active_pattern": "/wallet/admin/costs/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "agents",
                "url": "tenants:manager_review_agents",
                "label": "Agents",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-agents",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "backups",
                "url": "backups:manager_list",
                "label": "Data Backup",
                "icon": "bi-cloud-download",
                "active_prefix": "/backups/",
                "active_pattern": "/backups/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "farm":
        return [
            # MAIN section - Farm Manager vertical (GREEN theme) - CLEAN NAVIGATION
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "verticals:farm_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/verticals/farm/dashboard",
                "active_pattern": "/verticals/farm/dashboard",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-dashboard",
            },
            {
                "section": "MAIN",
                "key": "crops",
                "url": "verticals:farm_crops_list",
                "label": "Crops",
                "icon": "bi-flower1",
                "active_prefix": "/verticals/farm/crops",
                "active_pattern": "/verticals/farm/crops",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-crops",
            },
            {
                "section": "MAIN",
                "key": "sales",
                "url": "verticals:farm_sales",
                "label": "Sales",
                "icon": "bi-cart-check",
                "active_prefix": "/verticals/farm/sales",
                "active_pattern": "/verticals/farm/sales",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-sales",
            },
            {
                "section": "MAIN",
                "key": "expenses",
                "url": "verticals:farm_expenses",
                "label": "Expenses",
                "icon": "bi-receipt-cutoff",
                "active_prefix": "/verticals/farm/expenses",
                "active_pattern": "/verticals/farm/expenses",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-expenses",
            },
            {
                "section": "MAIN",
                "key": "livestock",
                "url": "verticals:farm_livestock_list",
                "label": "Livestock",
                "icon": "bi-piggy-bank",
                "active_prefix": "/verticals/farm/livestock",
                "active_pattern": "/verticals/farm/livestock",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-livestock",
            },
            {
                "section": "MAIN",
                "key": "assets",
                "url": "verticals:farm_assets",
                "label": "Assets",
                "icon": "bi-tools",
                "active_prefix": "/verticals/farm/assets",
                "active_pattern": "/verticals/farm/assets",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-assets",
            },
            {
                "section": "MAIN",
                "key": "locations",
                "url": "verticals:farm_locations",
                "label": "Locations",
                "icon": "bi-geo-alt",
                "active_prefix": "/verticals/farm/locations",
                "active_pattern": "/verticals/farm/locations",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-locations",
            },
            {
                "section": "MAIN",
                "key": "reports",
                "url": "verticals:farm_reports",
                "label": "Metrics & Reports",
                "icon": "bi-graph-up-arrow",
                "active_prefix": "/verticals/farm/reports",
                "active_pattern": "/verticals/farm/reports",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-reports",
            },
            # SUBSCRIPTION section (manager-only)
            {
                "section": "SUBSCRIPTION",
                "key": "billing",
                "url": "billing:plans",
                "label": "Billing",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/",
                "active_pattern": "/billing/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-billing",
            },
            {
                "section": "SUBSCRIPTION",
                "key": "settings",
                "url": "settings_root",
                "label": "Settings",
                "icon": "bi-gear",
                "active_prefix": "/settings/",
                "active_pattern": "/settings/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-farm-settings",
            },
        ]

    elif business_kind == "welding":
        return [
            # MAIN section - Welding Workshop vertical
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "verticals:welding_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/verticals/welding/dashboard",
                "active_pattern": "/verticals/welding/dashboard",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "sales",
                "url": "verticals:welding_sales",
                "label": "Sales",
                "icon": "bi-cart-check",
                "active_prefix": "/verticals/welding/sales",
                "active_pattern": "/verticals/welding/sales",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-welding-sales",
            },
            {
                "section": "MAIN",
                "key": "quotes",
                "url": "verticals:welding_quotes_list",
                "label": "Quotes",
                "icon": "bi-file-text",
                "active_prefix": "/verticals/welding/quotes",
                "active_pattern": "/verticals/welding/quotes",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "create_quote",
                "url": "verticals:welding_quote_create",
                "label": "Create Quote",
                "icon": "bi-plus-square",
                "active_prefix": "/verticals/welding/quotes/create",
                "active_pattern": "/verticals/welding/quotes/create",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "jobs",
                "url": "verticals:welding_jobs_list",
                "label": "Jobs",
                "icon": "bi-kanban",
                "active_prefix": "/verticals/welding/jobs",
                "active_pattern": "/verticals/welding/jobs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "materials",
                "url": "verticals:welding_materials_list",
                "label": "Materials",
                "icon": "bi-box-seam",
                "active_prefix": "/verticals/welding/materials",
                "active_pattern": "/verticals/welding/materials",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "stock_in",
                "url": "verticals:welding_stock_in",
                "label": "Stock In",
                "icon": "bi-box-arrow-in-down",
                "active_prefix": "/verticals/welding/stock-in",
                "active_pattern": "/verticals/welding/stock-in",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            {
                "section": "MAIN",
                "key": "invoices",
                "url": "verticals:welding_invoices_list",
                "label": "Invoices",
                "icon": "bi-receipt",
                "active_prefix": "/verticals/welding/invoices",
                "active_pattern": "/verticals/welding/invoices",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # MORE section
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "reports",
                "url": "verticals:welding_reports",
                "label": "Reports",
                "icon": "bi-file-earmark-bar-graph",
                "active_prefix": "/verticals/welding/reports",
                "active_pattern": "/verticals/welding/reports",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenants/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]

    elif business_kind == "car_hire":
        return [
            # MAIN section - Car Hire Service vertical (GREEN theme - fleet management)
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "verticals:car_hire_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/verticals/car_hire/dashboard",
                "active_pattern": "/verticals/car_hire/dashboard",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-dashboard",
            },
            {
                "section": "MAIN",
                "key": "vehicles",
                "url": "verticals:car_hire_vehicles",
                "label": "Vehicles",
                "icon": "bi-truck",
                "active_prefix": "/verticals/car_hire/vehicles",
                "active_pattern": "/verticals/car_hire/vehicles",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-vehicles",
            },
            {
                "section": "MAIN",
                "key": "add_vehicle",
                "url": "verticals:car_hire_vehicle_add",
                "label": "Add Vehicle",
                "icon": "bi-plus-square",
                "active_prefix": "/verticals/car_hire/vehicles/new",
                "active_pattern": "/verticals/car_hire/vehicles/new",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-add-vehicle",
            },
            {
                "section": "MAIN",
                "key": "trips",
                "url": "verticals:car_hire_trips",
                "label": "Trips / Bookings",
                "icon": "bi-calendar-check",
                "active_prefix": "/verticals/car_hire/trips",
                "active_pattern": "/verticals/car_hire/trips",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-trips",
            },
            {
                "section": "MAIN",
                "key": "add_trip",
                "url": "verticals:car_hire_trip_add",
                "label": "Add Trip",
                "icon": "bi-plus-circle",
                "active_prefix": "/verticals/car_hire/trips/new",
                "active_pattern": "/verticals/car_hire/trips/new",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-add-trip",
            },
            {
                "section": "MAIN",
                "key": "maintenance",
                "url": "verticals:car_hire_maintenance",
                "label": "Maintenance",
                "icon": "bi-wrench-adjustable",
                "active_prefix": "/verticals/car_hire/maintenance",
                "active_pattern": "/verticals/car_hire/maintenance",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-maintenance",
            },
            # SUBSCRIPTION section (manager-only)
            {
                "section": "SUBSCRIPTION",
                "key": "billing",
                "url": "billing:plans",
                "label": "Billing",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/",
                "active_pattern": "/billing/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-billing",
            },
            {
                "section": "SUBSCRIPTION",
                "key": "settings",
                "url": "settings_root",
                "label": "Settings",
                "icon": "bi-gear",
                "active_prefix": "/settings/",
                "active_pattern": "/settings/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-car-hire-settings",
            },
        ]

    else:  # "phones" or default
        return [
            # MAIN section - Phones Dashboard is the primary entry point
            {
                "section": "MAIN",
                "key": "dashboard",
                "url": "inventory_verticals:phones_dashboard",
                "label": "Dashboard",
                "icon": "bi-speedometer2",
                "active_prefix": "/inventory/verticals/phones",
                "active_pattern": "/inventory/verticals/phones",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "sidebar-dashboard",
            },
            {
                "section": "MAIN",
                "key": "analytics",
                "url": "app_router:analytics",
                "label": "Analytics",
                "icon": "bi-graph-up",
                "active_prefix": "/app/analytics",
                "active_pattern": "/app/analytics",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "sidebar-analytics",
            },
            # Note: Fast Sell removed - phones uses dedicated scan/sell flows
            {
                "section": "MAIN",
                "key": "stock",
                "url": "inventory:stock_list",
                "label": "Stock",
                "icon": "bi-box-seam",
                "active_prefix": "/inventory/list/",
                "active_pattern": "/inventory/list/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "sidebar-stock",
            },
            {
                "section": "MAIN",
                "key": "scan_in",
                "url": "inventory:scan_in",
                "label": "Scan IN",
                "icon": "bi-upc-scan",
                "active_prefix": "/inventory/scan",
                "active_pattern": "/inventory/scan",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "sidebar-scan-in",
            },
            {
                "section": "MAIN",
                "key": "sell",
                "url": "inventory:phone_sale_wizard",
                "label": "Scan & Sell",
                "icon": "bi-bag-check",
                "active_prefix": "/inventory/phone-sale-wizard/",
                "active_pattern": "/inventory/phone-sale-wizard/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "sidebar-sell",
            },
            # ACCESSORIES section (phones accessories - quantity-based, separate from IMEI phones)
            {
                "section": "MAIN",
                "key": "accessories",
                "url": "verticals:phones_accessories_dashboard",
                "label": "Accessories",
                "icon": "bi-box-seam",
                "active_prefix": "/verticals/phones/accessories/",
                "active_pattern": "/verticals/phones/accessories/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-phones-accessories",
            },
            {
                "section": "MAIN",
                "key": "accessories_stock_in",
                "url": "verticals:phones_accessories_stock_in",
                "label": "Stock In Accessories",
                "icon": "bi-box-arrow-in-down",
                "active_prefix": "/verticals/phones/accessories/stock-in/",
                "active_pattern": "/verticals/phones/accessories/stock-in/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-phones-accessories-stockin",
            },
            {
                "section": "MAIN",
                "key": "accessories_sell",
                "url": "verticals:phones_accessories_sell",
                "label": "Sell Accessories",
                "icon": "bi-cart-check",
                "active_prefix": "/verticals/phones/accessories/sell/",
                "active_pattern": "/verticals/phones/accessories/sell/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-phones-accessories-sell",
            },
            # LAYBY section (phones specific)
            {
                "section": "LAYBY",
                "key": "layby",
                "url": "layby:dashboard",
                "label": "Layby",
                "icon": "bi-journal-check",
                "active_prefix": "/layby/",
                "active_pattern": "/layby/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
            },
            # SALES & TEAM section (MORE section items)
            {
                "section": "MORE",
                "key": "sales_history",
                "url": "sales:list",
                "label": "Sales History",
                "icon": "bi-receipt",
                "active_prefix": "/sales/",
                "active_pattern": "/sales/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-sales-history",
            },
            # DATA CORRECTION (Manager-only - critical adoption feature)
            {
                "section": "MAIN",
                "key": "data_correction",
                "url": "verticals:phones_data_correction",
                "label": "Data Correction",
                "icon": "bi-pencil-square",
                "active_prefix": "/verticals/phones/data-correction/",
                "active_pattern": "/verticals/phones/data-correction/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "testid": "nav-phones-data-correction",
            },
            # MORE section - Collapsible tools (Wallet & Time Logs accessible to all, manager tools below)
            {
                "section": "MORE",
                "key": "wallet",
                "url": "wallet:agent_wallet",
                "label": "Wallet",
                "icon": "bi-wallet2",
                "active_prefix": "/wallet/",
                "active_pattern": "/wallet/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "time_logs",
                "url": "inventory:time_logs",
                "label": "Time Logs",
                "icon": "bi-journal-text",
                "active_prefix": "/inventory/time/logs",
                "active_pattern": "/inventory/time/logs",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "reports",
                "url": "reports:home",
                "label": "Reports",
                "icon": "bi-file-earmark-bar-graph",
                "active_prefix": "/reports/",
                "active_pattern": "/reports/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-reports",
            },
            {
                "section": "MORE",
                "key": "simulator",
                "url": "simulator:business_home",
                "label": "Simulator",
                "icon": "bi-cpu",
                "active_prefix": "/simulator/business/",
                "active_pattern": "/simulator/business/",
                "require_manager": False,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "products",
                "url": "inventory:phone_products",
                "label": "Products",
                "icon": "bi-grid-3x3-gap",
                "active_prefix": "/inventory/phone-products",
                "active_pattern": "/inventory/phone-products",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "admin_wallet",
                "url": "wallet:admin_home",
                "label": "Admin Wallet",
                "icon": "bi-briefcase",
                "active_prefix": "/wallet/admin/",
                "active_pattern": "/wallet/admin/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "costs",
                "url": "wallet:admin_cost_list",
                "label": "Costs",
                "icon": "bi-cash-stack",
                "active_prefix": "/wallet/admin/costs/",
                "active_pattern": "/wallet/admin/costs/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "agents",
                "url": "tenants:manager_review_agents",
                "label": "Agents",
                "icon": "bi-people",
                "active_prefix": "/tenants/manager/agents/",
                "active_pattern": "/tenants/manager/agents/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
                "testid": "sidebar-agents",
            },
            {
                "section": "MORE",
                "key": "locations",
                "url": "tenants:manager_locations",
                "label": "Locations",
                "icon": "bi-geo",
                "active_prefix": "/tenants/manager/locations/",
                "active_pattern": "/tenicals/manager/locations/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "backups",
                "url": "backups:manager_list",
                "label": "Data Backup",
                "icon": "bi-cloud-download",
                "active_prefix": "/backups/",
                "active_pattern": "/backups/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "billing",
                "url": "billing:plans",
                "label": "Choose Plan",
                "icon": "bi-credit-card-2-front",
                "active_prefix": "/billing/plans",
                "active_pattern": "/billing/plans",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
            {
                "section": "MORE",
                "key": "orders",
                "url": "inventory:orders_list",
                "label": "Orders",
                "icon": "bi-clipboard-data",
                "active_prefix": "/inventory/orders/",
                "active_pattern": "/inventory/orders/",
                "require_manager": True,
                "is_menu": False,
                "is_header": False,
                "group": "more",
            },
        ]


__all__ = [
    "get_vertical_kind",
    "get_vertical_dashboard_url",
    "get_onboarding_steps",
    "get_vertical_display_name",
    "get_vertical_sidebar_items",
]

