# Generated by Django 4.2.24 on 2025-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_business_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('AGENT', 'Agent')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('subdomain', ''), _negated=True), fields=('subdomain',), name='uniq_business_subdomain_nonblank'),
        ),
    ]
