# Generated by Django 4.2.23 on 2025-09-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_alter_membership_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('JOINED', 'Joined'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=240)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_invites_created', to=settings.AUTH_USER_MODEL)),
                ('joined_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_invites_redeemed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['business', 'status', '-created_at'], name='tenants_age_busines_9d8428_idx')],
            },
        ),
    ]
