# Generated by Django 4.2.23 on 2025-09-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_agentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinvite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinvite',
            name='invited_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='agentinvite',
            name='token',
            field=models.CharField(db_index=True, max_length=140, unique=True),
        ),
    ]
