# Generated by Django 4.2.23 on 2025-10-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_doc_docitem_doc_inventory_d_type_b2a3e3_idx_and_more'),
        ('tenants', '0005_agentinvite_expires_at_agentinvite_invited_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinvite',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location for this invite. On accept, the membership will use this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_invites', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='membership',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Default store/location for this member (agents are restricted to this by default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='inventory.location'),
        ),
    ]
