# Generated by Django 4.2.23 on 2025-10-31 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_inventoryaudit_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0006_agentinvite_location_membership_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Default store/location for this member. Agents must have this set; managers may leave it blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='inventory.location'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'business', 'location')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'business'], name='tenants_mem_user_id_9141c5_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['role'], name='tenants_mem_role_f2351c_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['status'], name='tenants_mem_status_571dd3_idx'),
        ),
    ]
