# Generated by Django 4.2.23 on 2025-11-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_membership_location_and_defaults'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='business',
            name='biz_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='business',
            name='biz_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='business',
            name='biz_subdomain_idx',
        ),
    ]
