# Generated by Django 4.2.23 on 2025-11-01 13:09

from django.db import migrations
from django.db.migrations.operations.models import RemoveIndex


class SafeRemoveIndex(RemoveIndex):
    """
    Prevents ValueError if index is missing from migration state.
    """
    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except ValueError:
            pass


def drop_business_indexes_database(apps, schema_editor):
    """
    Drop business indexes using idempotent SQL.
    Safe to run even if indexes don't exist (handles state drift).
    """
    vendor = schema_editor.connection.vendor
    
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("DROP INDEX IF EXISTS biz_created_idx")
            cursor.execute("DROP INDEX IF EXISTS biz_status_idx")
            cursor.execute("DROP INDEX IF EXISTS biz_subdomain_idx")
        elif vendor == 'sqlite':
            cursor.execute("DROP INDEX IF EXISTS biz_created_idx")
            cursor.execute("DROP INDEX IF EXISTS biz_status_idx")
            cursor.execute("DROP INDEX IF EXISTS biz_subdomain_idx")
        # Other databases: skip (should not happen in production)


def reverse_drop_business_indexes_database(apps, schema_editor):
    """Reverse: Recreate indexes (not typically needed, but for completeness)"""
    # This is a no-op since we're removing them - reverse would require
    # knowing the original definition. In practice, this migration should not be reversed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_membership_location_and_defaults'),
    ]

    operations = [
        # Remove indexes using SeparateDatabaseAndState to handle state drift
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_business_indexes_database,
                    reverse_drop_business_indexes_database,
                ),
            ],
            state_operations=[
                SafeRemoveIndex(
                    model_name='business',
                    name='biz_created_idx',
                ),
                SafeRemoveIndex(
                    model_name='business',
                    name='biz_status_idx',
                ),
                SafeRemoveIndex(
                    model_name='business',
                    name='biz_subdomain_idx',
                ),
            ],
        ),
    ]
