# Generated by Django 5.2.5 on 2025-12-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_business_business_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinvite",
            name="temp_password_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hashed temporary password for agent login.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="agentinvite",
            name="temp_password_used",
            field=models.BooleanField(
                default=False, help_text="Whether the temp password has been used."
            ),
        ),
    ]
