# Generated by Django 5.2.5 on 2025-12-03 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_monthlysalestarget"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Business logo. Best fit: square or 3:1 ratio (e.g., 300x300 or 600x200). PNG with transparent background recommended.",
                null=True,
                upload_to="business_logos/",
            ),
        ),
        migrations.CreateModel(
            name="MembershipLocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_transfers_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous location (null if this is the first assignment)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_history_from",
                        to="inventory.location",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to="tenants.membership",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        help_text="New location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_history_to",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Location History",
                "verbose_name_plural": "Membership Location Histories",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["membership", "-changed_at"],
                        name="tenants_mem_members_55b2a2_idx",
                    ),
                    models.Index(
                        fields=["from_location", "-changed_at"],
                        name="tenants_mem_from_lo_141416_idx",
                    ),
                    models.Index(
                        fields=["to_location", "-changed_at"],
                        name="tenants_mem_to_loca_3bc96a_idx",
                    ),
                ],
            },
        ),
    ]
