# Generated by Django 5.2.5 on 2025-12-14 09:58

from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):
    """
    MULTI-TENANCY HARDENING: Add case-insensitive unique constraints.
    
    This migration ensures:
    1. Business names are globally unique (case-insensitive)
    2. User emails are globally unique (case-insensitive)
    
    These constraints prevent:
    - Creating "Majinet" and "majinet" as separate businesses
    - Same email creating multiple user accounts
    """

    dependencies = [
        ("tenants", "0013_add_location_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Business name unique case-insensitive
        migrations.RemoveConstraint(
            model_name='business',
            name='uniq_business_name_ci',
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(
                Lower('name'),
                name='uniq_business_name_ci',
                violation_error_message='A business with this name already exists (case-insensitive).'
            ),
        ),
        
        # Email unique case-insensitive (User model)
        # Note: This requires the User model to be in this app or we use RunSQL
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'uniq_user_email_ci'
                    ) THEN
                        ALTER TABLE auth_user 
                        ADD CONSTRAINT uniq_user_email_ci 
                        UNIQUE (LOWER(email));
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS uniq_user_email_ci;
            """,
        ),
    ]
