# Generated by Django 5.2.5 on 2025-12-14 09:58

from django.conf import settings
from django.db import migrations, models, connection
from django.db.models import Q
from django.db.models.functions import Lower


def create_email_unique_index(apps, schema_editor):
    """Create case-insensitive unique index on email, excluding blank emails"""
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_email_ci 
            ON auth_user (LOWER(email))
            WHERE email != ''
        """)


def drop_email_unique_index(apps, schema_editor):
    """Drop the email unique index"""
    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS uniq_user_email_ci")


def create_business_name_ci_constraint_database(apps, schema_editor):
    """
    Create case-insensitive unique constraint/index for business names.
    This uses raw SQL to safely handle both PostgreSQL and SQLite.
    """
    vendor = schema_editor.connection.vendor
    
    if vendor == 'postgresql':
        # PostgreSQL: Drop constraint/index if exists, then create unique index
        with schema_editor.connection.cursor() as cursor:
            # Drop constraint if it exists (PostgreSQL constraint)
            cursor.execute("""
                ALTER TABLE tenants_business 
                DROP CONSTRAINT IF EXISTS uniq_business_name_ci
            """)
            # Drop index if it exists (PostgreSQL index)
            cursor.execute("DROP INDEX IF EXISTS uniq_business_name_ci")
            # Create unique index if not exists
            cursor.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS uniq_business_name_ci 
                ON tenants_business (LOWER(name))
            """)
    elif vendor == 'sqlite':
        # SQLite: Create unique index (SQLite doesn't support constraints the same way)
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS uniq_business_name_ci 
                ON tenants_business (LOWER(name))
            """)
    else:
        # Other databases: fallback to Django's AddConstraint
        # This should not happen in production (Render uses PostgreSQL)
        pass


def reverse_business_name_ci_constraint_database(apps, schema_editor):
    """Reverse operation: drop the constraint/index"""
    vendor = schema_editor.connection.vendor
    
    if vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE tenants_business DROP CONSTRAINT IF EXISTS uniq_business_name_ci")
            cursor.execute("DROP INDEX IF EXISTS uniq_business_name_ci")
    elif vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP INDEX IF EXISTS uniq_business_name_ci")
    else:
        pass


class Migration(migrations.Migration):
    """
    MULTI-TENANCY HARDENING: Add case-insensitive unique constraints.
    
    This migration ensures:
    1. Business names are globally unique (case-insensitive)
    2. User emails are globally unique (case-insensitive)
    
    These constraints prevent:
    - Creating "Majinet" and "majinet" as separate businesses
    - Same email creating multiple user accounts
    
    FIXED: Uses SeparateDatabaseAndState to avoid RemoveConstraint error
    when constraint doesn't exist in migration state. Database operations
    use idempotent SQL (DROP IF EXISTS, CREATE IF NOT EXISTS).
    """

    dependencies = [
        ("tenants", "0013_add_location_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Business name unique case-insensitive
        # Use SeparateDatabaseAndState to safely handle constraint that may not exist in state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_business_name_ci_constraint_database,
                    reverse_business_name_ci_constraint_database,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='business',
                    constraint=models.UniqueConstraint(
                        Lower('name'),
                        name='uniq_business_name_ci',
                        violation_error_message='A business with this name already exists (case-insensitive).'
                    ),
                ),
            ],
        ),
        
        # Email unique case-insensitive (User model)
        # Note: Uses partial unique index to exclude blank emails
        # Works in both production and test databases
        migrations.RunPython(
            create_email_unique_index,
            drop_email_unique_index,
        ),
    ]
