# Generated by Django 5.2.5 on 2025-12-14 09:58

from django.conf import settings
from django.db import migrations, models, connection
from django.db.models import Q
from django.db.models.functions import Lower


def create_email_unique_index(apps, schema_editor):
    """Create case-insensitive unique index on email, excluding blank emails"""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            # PostgreSQL: Use IF NOT EXISTS
            cursor.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_email_ci 
                ON auth_user (LOWER(email))
                WHERE email != ''
            """)
        elif vendor == 'sqlite':
            # SQLite: Use IF NOT EXISTS
            cursor.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_email_ci 
                ON auth_user (LOWER(email))
                WHERE email != ''
            """)
        # Other databases: skip (should not happen in production)


def drop_email_unique_index(apps, schema_editor):
    """Drop the email unique index (idempotent)"""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("DROP INDEX IF EXISTS uniq_user_email_ci")
        elif vendor == 'sqlite':
            cursor.execute("DROP INDEX IF EXISTS uniq_user_email_ci")
        # Other databases: skip


def create_business_name_ci_constraint_database(apps, schema_editor):
    """
    Create case-insensitive unique constraint/index for business names.
    IDEMPOTENT: Safe to run multiple times, handles state drift.
    Uses raw SQL to safely handle both PostgreSQL and SQLite.
    """
    vendor = schema_editor.connection.vendor
    
    # Get the actual table name from the model
    Business = apps.get_model('tenants', 'Business')
    table_name = Business._meta.db_table
    
    if vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if index/constraint already exists
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'uniq_business_name_ci'
                LIMIT 1
            """)
            index_exists = cursor.fetchone() is not None
            
            # Only create if it doesn't exist (idempotent)
            if not index_exists:
                # Drop any existing constraint with same name (in case of partial migration)
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    DROP CONSTRAINT IF EXISTS uniq_business_name_ci
                """)
                # Create unique index
                cursor.execute(f"""
                    CREATE UNIQUE INDEX uniq_business_name_ci 
                    ON {table_name} (LOWER(name))
                """)
    elif vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            # SQLite: Use IF NOT EXISTS for idempotency
            cursor.execute(f"""
                CREATE UNIQUE INDEX IF NOT EXISTS uniq_business_name_ci 
                ON {table_name} (LOWER(name))
            """)
    # Other databases: skip (should not happen in production)


def reverse_business_name_ci_constraint_database(apps, schema_editor):
    """Reverse operation: drop the constraint/index (idempotent)"""
    vendor = schema_editor.connection.vendor
    
    # Get the actual table name from the model
    Business = apps.get_model('tenants', 'Business')
    table_name = Business._meta.db_table
    
    if vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS uniq_business_name_ci")
            cursor.execute("DROP INDEX IF EXISTS uniq_business_name_ci")
    elif vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP INDEX IF EXISTS uniq_business_name_ci")
    # Other databases: skip


class Migration(migrations.Migration):
    """
    MULTI-TENANCY HARDENING: Add case-insensitive unique constraints.
    
    This migration ensures:
    1. Business names are globally unique (case-insensitive)
    2. User emails are globally unique (case-insensitive)
    
    These constraints prevent:
    - Creating "Majinet" and "majinet" as separate businesses
    - Same email creating multiple user accounts
    
    FIXED: Uses SeparateDatabaseAndState to avoid RemoveConstraint error
    when constraint doesn't exist in migration state. Database operations
    use idempotent SQL (DROP IF EXISTS, CREATE IF NOT EXISTS).
    """

    dependencies = [
        ("tenants", "0013_add_location_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Business name unique case-insensitive
        # Use SeparateDatabaseAndState to completely decouple database ops from state ops.
        # This prevents Django from trying to remove constraints that don't exist in state.
        # Database operations are idempotent (IF NOT EXISTS, check before create).
        # State operations only update Django's migration graph, never touch the database.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_business_name_ci_constraint_database,
                    reverse_business_name_ci_constraint_database,
                ),
            ],
            state_operations=[
                # State operation: Add constraint to Django's migration state only.
                # This does NOT touch the database - it only updates Django's understanding
                # of what the model should look like. The actual database constraint
                # is created by the database_operations above.
                migrations.AddConstraint(
                    model_name='business',
                    constraint=models.UniqueConstraint(
                        Lower('name'),
                        name='uniq_business_name_ci',
                        violation_error_message='A business with this name already exists (case-insensitive).'
                    ),
                ),
            ],
        ),
        
        # Email unique case-insensitive (User model)
        # Note: Uses partial unique index to exclude blank emails
        # Works in both production and test databases
        # This is a raw SQL index, so no state operation needed (it's not a Django constraint)
        migrations.RunPython(
            create_email_unique_index,
            drop_email_unique_index,
        ),
    ]
