# Generated by Django 5.2.5 on 2025-12-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_add_unique_active_membership_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinvite",
            name="role",
            field=models.CharField(
                choices=[("AGENT", "Sales Agent"), ("BAR_MANAGER", "Bar Manager")],
                db_index=True,
                default="AGENT",
                help_text="Role the user will receive upon accepting this invite",
                max_length=20,
            ),
        ),
    ]
