# Generated by Django 5.2.5 on 2025-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_add_role_to_agent_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="has_cosmetics_section",
            field=models.BooleanField(
                default=False,
                help_text="True if this business operates a Cosmetics section",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="has_pharmacy_section",
            field=models.BooleanField(
                default=False,
                help_text="True if this business operates a Pharmacy section",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="business_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Pharmacy"),
                    ("cosmetics", "Cosmetics"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("cement", "Cement & Hardware"),
                ],
                db_index=True,
                help_text="Business vertical (drives tailored dashboards and flows).",
                max_length=20,
                null=True,
            ),
        ),
    ]
