# Generated by Django 5.2.5 on 2025-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_add_role_to_agent_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="business_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("cement", "Cement / Hardware"),
                ],
                db_index=True,
                help_text="Business vertical (drives tailored dashboards and flows).",
                max_length=20,
                null=True,
            ),
        ),
    ]
