# Generated by Django 5.2.5 on 2025-12-25 17:57

from django.db import migrations, models


def normalize_section_flags(apps, schema_editor):
    """Normalize any NULL section flags to False (defensive)"""
    # Use raw SQL since field might exist in DB but not in model state yet
    from django.db import connection
    with connection.cursor() as cursor:
        # Normalize has_cosmetics_section (might exist in DB without default)
        try:
            cursor.execute("""
                UPDATE tenants_business 
                SET has_cosmetics_section = 0 
                WHERE has_cosmetics_section IS NULL
            """)
        except Exception:
            pass  # Field might not exist yet
        
        # Normalize new fields after they're added
        try:
            cursor.execute("""
                UPDATE tenants_business 
                SET has_groceries_section = 0 
                WHERE has_groceries_section IS NULL
            """)
        except Exception:
            pass
        
        try:
            cursor.execute("""
                UPDATE tenants_business 
                SET has_cement_section = 0 
                WHERE has_cement_section IS NULL
            """)
        except Exception:
            pass


def reverse_normalize(apps, schema_editor):
    """Reverse migration - no-op"""
    pass


def ensure_has_cosmetics_section_default(apps, schema_editor):
    """Ensure has_cosmetics_section has default=False if it exists"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Check if field exists and add default if needed
        try:
            # SQLite doesn't support ALTER COLUMN SET DEFAULT directly
            # So we'll just normalize NULLs in the RunPython step
            pass
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_add_cement_grocery_sales_and_costs"),
    ]

    operations = [
        # Use RunSQL to handle existing has_cosmetics_section field
        # If it exists, ensure it has default; if not, this will be handled by AddField
        migrations.RunSQL(
            sql="""
                -- Try to add default if field exists (SQLite doesn't support ALTER COLUMN SET DEFAULT)
                -- We'll handle NULLs in RunPython instead
                SELECT 1;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Add has_cosmetics_section (will be no-op if exists, or add if missing)
        migrations.AddField(
            model_name="business",
            name="has_cosmetics_section",
            field=models.BooleanField(
                default=False,
                help_text="Enable cosmetics section for pharmacy businesses",
            ),
        ),
        # Add new section flags
        migrations.AddField(
            model_name="business",
            name="has_cement_section",
            field=models.BooleanField(
                default=False, help_text="Enable cement/hardware section"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="has_groceries_section",
            field=models.BooleanField(
                default=False, help_text="Enable groceries section"
            ),
        ),
        # Normalize any NULLs to False (defensive)
        migrations.RunPython(normalize_section_flags, reverse_normalize),
    ]
