# Generated by Django 5.2.5 on 2025-12-25 17:57

from django.db import migrations, models


def safely_add_section_flag_fields(apps, schema_editor):
    """
    Safely add section flag fields using idempotent SQL operations.
    Uses ADD COLUMN IF NOT EXISTS and separate statements to avoid "pending trigger events" error.
    Pattern: add column -> backfill -> set default -> set NOT NULL (each as separate statement)
    """
    connection = schema_editor.connection
    db_vendor = connection.vendor
    
    # Get the actual db_table name dynamically
    Business = apps.get_model('tenants', 'Business')
    table_name = Business._meta.db_table
    
    SECTION_FLAGS = [
        'has_cosmetics_section',
        'has_cement_section',
        'has_groceries_section',
    ]
    
    print("Creating default section flags...")
    
    if db_vendor == 'postgresql':
        # Get quoted identifiers for safe SQL construction
        quoted_table = connection.ops.quote_name(table_name)
        
        with connection.cursor() as cursor:
            for col in SECTION_FLAGS:
                print(f"Processing column: {col}")
                qcol = connection.ops.quote_name(col)
                
                # 1) Add column if missing (nullable first) - idempotent
                cursor.execute(f"ALTER TABLE {quoted_table} ADD COLUMN IF NOT EXISTS {qcol} boolean;")
                
                # 2) Backfill any NULLs - idempotent
                cursor.execute(f"UPDATE {quoted_table} SET {qcol} = FALSE WHERE {qcol} IS NULL;")
                
                # 3) Set DB default - idempotent
                cursor.execute(f"ALTER TABLE {quoted_table} ALTER COLUMN {qcol} SET DEFAULT FALSE;")
                
                # 4) Enforce not-null - idempotent (safe to re-run if already NOT NULL)
                cursor.execute(f"ALTER TABLE {quoted_table} ALTER COLUMN {qcol} SET NOT NULL;")
    
    elif db_vendor == 'sqlite':
        quoted_table = connection.ops.quote_name(table_name)
        with connection.cursor() as cursor:
            # Check existing columns
            cursor.execute(f"PRAGMA table_info({quoted_table})")
            existing_columns = {row[1] for row in cursor.fetchall()}
            
            for field_name in SECTION_FLAGS:
                quoted_field = connection.ops.quote_name(field_name)
                if field_name not in existing_columns:
                    # SQLite: Add column with DEFAULT and NOT NULL in one step
                    cursor.execute(f"""
                        ALTER TABLE {quoted_table}
                        ADD COLUMN {quoted_field} BOOLEAN NOT NULL DEFAULT 0
                    """)
                else:
                    # Column exists, just normalize any NULLs
                    cursor.execute(f"""
                        UPDATE {quoted_table}
                        SET {quoted_field} = 0
                        WHERE {quoted_field} IS NULL
                    """)
    else:
        # For other databases, fall back to standard AddField (will be handled below)
        pass
    
    print("Done creating section flags.")


def reverse_normalize(apps, schema_editor):
    """Reverse migration - no-op (don't delete production data)"""
    pass


class Migration(migrations.Migration):
    """
    Add section flag fields to Business model.
    Idempotent: safely handles cases where fields may already exist.
    
    atomic = False is required because Postgres defers constraint triggers until commit,
    then blocks later ALTER TABLE operations in the same transaction with "pending trigger events" error.
    By making the migration non-atomic, each ALTER TABLE statement commits immediately.
    """
    
    atomic = False  # Required: Postgres pending trigger events block ALTER TABLE in same transaction

    dependencies = [
        ("tenants", "0018_add_cement_grocery_sales_and_costs"),
    ]

    operations = [
        # Safely add columns using raw SQL (idempotent, uses ADD COLUMN IF NOT EXISTS)
        migrations.RunPython(
            safely_add_section_flag_fields,
            reverse_normalize,
            atomic=False,  # Must match Migration.atomic=False to avoid pending trigger events
        ),
        # Use Django's AddField to ensure migration state is tracked
        # These may fail if columns already exist, but with atomic=False the migration
        # can continue. However, if they fail, Django's state won't be updated.
        # Better approach: use SeparateDatabaseAndState to track state without running SQL
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database operations already done in RunPython above
            ],
            state_operations=[
                migrations.AddField(
                    model_name="business",
                    name="has_cosmetics_section",
                    field=models.BooleanField(
                        default=False,
                        help_text="Enable cosmetics section for pharmacy businesses",
                    ),
                ),
                migrations.AddField(
                    model_name="business",
                    name="has_cement_section",
                    field=models.BooleanField(
                        default=False,
                        help_text="Enable cement/hardware section",
                    ),
                ),
                migrations.AddField(
                    model_name="business",
                    name="has_groceries_section",
                    field=models.BooleanField(
                        default=False,
                        help_text="Enable groceries section",
                    ),
                ),
            ],
        ),
    ]
