# Generated by Django 5.2.5 on 2026-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0021_alter_business_business_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="hq_notified_signup_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When HQ was notified of this business signup (idempotency)",
                null=True,
            ),
        ),
    ]
