# Generated by Django 5.2.5 on 2026-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0022_business_hq_notified_signup_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="currency",
            field=models.CharField(
                default="MWK",
                help_text="Currency code (ISO 4217, e.g., MWK, USD, GBP).",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="business_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("hardware", "Hardware & General Dealers"),
                    ("cement", "Cement / Building Materials"),
                ],
                db_index=True,
                help_text="Business vertical (drives tailored dashboards and flows).",
                max_length=20,
                null=True,
            ),
        ),
    ]
