# Generated by Django 5.2.5 on 2026-01-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_fix_cement_business_kind"),
        ("tenants", "0024_reconcile_0019a_rename"),
    ]

    operations = []
