# Generated by Django 5.2.5 on 2026-01-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0025_merge_20260108_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Backwards compatibility flag. Prefer using status field.",
            ),
        ),
    ]
