# Generated by Django 5.2.5 on 2026-01-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0027_add_farm_welding_business_kinds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending staff approval"),
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager"),
                    ("manager", "Manager"),
                    ("AGENT", "Agent"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
