# Generated by Django 5.2.5 on 2026-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0028_alter_business_status_alter_membership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
