# Generated by Django 5.2.5 on 2026-01-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0029_alter_membership_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager"),
                    ("AGENT", "Agent"),
                    ("BAR_MANAGER", "Bar Manager"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
