# Generated by Django 5.2.5 on 2025-12-02 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hq", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agentmilestone",
            new_name="hq_agentmil_user_id_04feea_idx",
            old_name="hq_agentmil_user_id_b17e89_idx",
        ),
        migrations.RenameIndex(
            model_name="agentmilestone",
            new_name="hq_agentmil_busines_21f4aa_idx",
            old_name="hq_agentmil_busines_44e1b5_idx",
        ),
    ]
