# Generated by Django 5.2.5 on 2025-12-14 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hq", "0004_support_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentMilestone",
        ),
        migrations.DeleteModel(
            name="MerchantContract",
        ),
    ]
