# Generated by Django 5.2.5 on 2025-12-15 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hq", "0005_remove_merchantcontract_business_and_more"),
        ("tenants", "0014_add_case_insensitive_unique_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(help_text="Signed contract PDF file", upload_to="contracts/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes about this contract"),
                ),
                (
                    "business",
                    models.OneToOneField(
                        help_text="The business this contract is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_contract",
                        to="tenants.business",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="HQ staff member who uploaded this contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Contract",
                "verbose_name_plural": "Merchant Contracts",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(fields=["business"], name="hq_merchant_busines_fadd16_idx"),
                    models.Index(fields=["uploaded_at"], name="hq_merchant_uploade_34b1f5_idx"),
                ],
            },
        ),
    ]
