# Generated by Django 5.2.5 on 2025-12-17 10:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hq", "0006_merchantcontract"),
        ("tenants", "0016_add_unique_active_membership_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        help_text="Type of milestone (e.g., first_sale, 100_sales, top_seller)",
                        max_length=50,
                    ),
                ),
                (
                    "achieved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional milestone data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-achieved_at"],
            },
        ),
        migrations.CreateModel(
            name="HQPaymentMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(help_text="Start of billing period")),
                ("period_end", models.DateField(help_text="End of billing period")),
                (
                    "plan_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Plan code at time of marking",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount marked paid",
                        max_digits=12,
                    ),
                ),
                ("marked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.RemoveField(
            model_name="businessnote",
            name="author",
        ),
        migrations.RemoveField(
            model_name="businessnote",
            name="business",
        ),
        migrations.RemoveField(
            model_name="supportnote",
            name="author",
        ),
        migrations.RemoveField(
            model_name="supportnote",
            name="ticket",
        ),
        migrations.AlterModelOptions(
            name="merchantcontract",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="supportactionlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="supportticket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="merchantcontract",
            name="hq_merchant_busines_fadd16_idx",
        ),
        migrations.RemoveIndex(
            model_name="merchantcontract",
            name="hq_merchant_uploade_34b1f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportactionlog",
            name="hq_supporta_busines_dc10bb_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportactionlog",
            name="hq_supporta_actor_i_b8e39c_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportactionlog",
            name="hq_supporta_action__644feb_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportactionlog",
            name="hq_supporta_busines_7eb091_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportticket",
            name="hq_supportt_busines_a1eebf_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportticket",
            name="hq_supportt_assigne_eb97cc_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportticket",
            name="hq_supportt_categor_cd0197_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportticket",
            name="hq_supportt_priorit_aae70d_idx",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="entity_id",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="entity_type",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="payload_after",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="payload_before",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="supportactionlog",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="category",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="closed_at",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="meta",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="requester",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="requester_email",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="ticket_number",
        ),
        migrations.AddField(
            model_name="merchantcontract",
            name="contract_type",
            field=models.CharField(default="standard", max_length=50),
        ),
        migrations.AddField(
            model_name="merchantcontract",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantcontract",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantcontract",
            name="title",
            field=models.CharField(
                default="Merchant Services Agreement", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="supportactionlog",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="supportactionlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="supportactionlog",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportactionlog",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_logs",
                to="hq.supportticket",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="merchantcontract",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="tenants.business",
            ),
        ),
        migrations.AlterField(
            model_name="merchantcontract",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="contracts/"),
        ),
        migrations.AlterField(
            model_name="merchantcontract",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="merchantcontract",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supportactionlog",
            name="action_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="supportactionlog",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.business",
            ),
        ),
        migrations.AlterField(
            model_name="supportactionlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="supportactionlog",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="priority",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="merchantcontract",
            index=models.Index(
                fields=["business", "contract_type"],
                name="hq_merchant_busines_780df6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportactionlog",
            index=models.Index(
                fields=["business", "created_at"], name="hq_supporta_busines_3e6a2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportactionlog",
            index=models.Index(
                fields=["ticket", "created_at"], name="hq_supporta_ticket__246d80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["business", "status"], name="hq_supportt_busines_e10157_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["status", "created_at"], name="hq_supportt_status_52f457_idx"
            ),
        ),
        migrations.AddField(
            model_name="agentmilestone",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="agentmilestone",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_milestones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hqpaymentmark",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_marks",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="hqpaymentmark",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BusinessNote",
        ),
        migrations.DeleteModel(
            name="SupportNote",
        ),
        migrations.AddIndex(
            model_name="agentmilestone",
            index=models.Index(
                fields=["user", "milestone_type"], name="hq_agentmil_user_id_6bf178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentmilestone",
            index=models.Index(
                fields=["business", "achieved_at"],
                name="hq_agentmil_busines_7596a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hqpaymentmark",
            index=models.Index(
                fields=["business", "period_start"],
                name="hq_hqpaymen_busines_bd9bb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hqpaymentmark",
            index=models.Index(
                fields=["marked_at"], name="hq_hqpaymen_marked__382bde_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hqpaymentmark",
            constraint=models.UniqueConstraint(
                fields=("business", "period_start", "period_end"),
                name="unique_payment_mark_per_period",
            ),
        ),
    ]
