# Generated by Django 5.2.5 on 2026-04-28 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hq", "0008_bug_monitor_and_audit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HQPermissions",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="hq_adminaud_actor_i_609296_idx",
            old_name="hq_adminlog_actor_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="hq_adminaud_action_bad8c3_idx",
            old_name="hq_adminlog_action_idx",
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="hq_adminaud_target__858ae9_idx",
            old_name="hq_adminlog_target_idx",
        ),
        migrations.RenameIndex(
            model_name="systemissue",
            new_name="hq_systemis_fingerp_789c3c_idx",
            old_name="hq_sysiss_fp_idx",
        ),
        migrations.RenameIndex(
            model_name="systemissue",
            new_name="hq_systemis_status_c0e865_idx",
            old_name="hq_sysiss_stat_sev_idx",
        ),
        migrations.RenameIndex(
            model_name="systemissue",
            new_name="hq_systemis_status__05a03a_idx",
            old_name="hq_sysiss_code_idx",
        ),
        migrations.RenameIndex(
            model_name="systemissue",
            new_name="hq_systemis_last_se_dff27a_idx",
            old_name="hq_sysiss_lastseen_idx",
        ),
        migrations.RenameIndex(
            model_name="systemissue",
            new_name="hq_systemis_assigne_d51dd0_idx",
            old_name="hq_sysiss_assignee_idx",
        ),
        migrations.RenameIndex(
            model_name="systemissueoccurrence",
            new_name="hq_systemis_issue_i_ab3836_idx",
            old_name="hq_sysoccur_issue_idx",
        ),
        migrations.AlterField(
            model_name="systemissue",
            name="first_seen_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="systemissue",
            name="last_seen_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="systemissue",
            name="status_code",
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemissueoccurrence",
            name="occurred_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
