# Generated by Django 5.2.5 on 2026-04-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hq", "0009_bug_monitor_and_audit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemissue",
            options={
                "ordering": ["-last_seen_at"],
                "permissions": [
                    ("can_view_hq_admin", "Can view HQ admin"),
                    ("can_view_bug_monitor", "Can view Bug Monitor"),
                    ("can_view_stack_traces", "Can view stack traces"),
                    ("can_manage_bug_status", "Can manage bug status"),
                    ("can_assign_bugs", "Can assign bugs"),
                    ("can_view_audit_logs", "Can view audit logs"),
                    ("can_manage_admin_roles", "Can manage admin roles"),
                    ("can_view_business_data", "Can view business data"),
                    ("can_manage_integrations", "Can manage integrations"),
                    ("can_view_webhooks", "Can view webhooks"),
                ],
                "verbose_name": "System Issue",
                "verbose_name_plural": "System Issues",
            },
        ),
    ]
