# Generated by Django 5.2.5 on 2026-05-26 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hq", "0011_merchantcontract_esignature"),
        ("tenants", "0035_add_new_business_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="merchantcontract",
            index=models.Index(fields=["status"], name="hq_merchant_status_57c1e7_idx"),
        ),
        migrations.AddIndex(
            model_name="merchantcontract",
            index=models.Index(
                fields=["sign_token"], name="hq_merchant_sign_to_fc7654_idx"
            ),
        ),
    ]
