# Generated by Django 6.0.5 on 2026-05-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="brand_logos/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=120)),
                ("specs", models.CharField(max_length=80)),
                ("cash_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_percent",
                    models.DecimalField(decimal_places=2, default=32, max_digits=5),
                ),
                ("unlock_days", models.PositiveIntegerField(default=7)),
                (
                    "total_12_month_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="deals.devicebrand",
                    ),
                ),
            ],
        ),
    ]
