# Generated by Django 6.0.5 on 2026-05-25 19:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedeal",
            name="default_cash_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="loan_multiplier",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2.5"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="max_cash_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="min_cash_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="term_months",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="devicedeal",
            name="cash_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="devicedeal",
            name="deposit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=24,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("22")),
                    django.core.validators.MaxValueValidator(Decimal("40")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="devicedeal",
            name="total_12_month_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
