# Generated by Django 6.0.5 on 2026-05-25 20:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def normalize_deposit_percent(apps, schema_editor):
    DeviceDeal = apps.get_model("deals", "DeviceDeal")
    DeviceDeal.objects.filter(deposit_percent__lt=Decimal("13")).update(deposit_percent=Decimal("13"))
    DeviceDeal.objects.filter(deposit_percent__gt=Decimal("16")).update(deposit_percent=Decimal("13"))


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_devicedeal_default_cash_price_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_deposit_percent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="devicedeal",
            name="deposit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=13,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("13")),
                    django.core.validators.MaxValueValidator(Decimal("16")),
                ],
            ),
        ),
    ]
