# Generated by Django 6.0.5 on 2026-05-28 10:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_alter_devicedeal_deposit_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedeal",
            name="arrears_penalty_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.1400"),
                help_text="Arrears/penalty deduction rate (e.g. 0.14 = 14%)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="country",
            field=models.CharField(default="MW", max_length=10),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="lock_provider",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="merchant_commission_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0100"),
                help_text="Merchant commission rate (e.g. 0.01 = 1%)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("limited", "Limited Stock"),
                    ("out_of_stock", "Out of Stock"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="underwriter_commission_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0700"),
                help_text="Underwriter commission rate (e.g. 0.07 = 7%)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="devicedeal",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
