# Generated by Django 6.0.5 on 2026-05-27 18:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="total_wht_withheld",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("commission_credit", "Commission Credit"),
                    ("commission", "Payment Commission"),
                    ("payout", "Wallet Payout"),
                    ("wallet_payout", "Wallet Payout"),
                    ("payout_debit", "Payout Debit"),
                    ("wht_deduction", "WHT Deduction"),
                    ("tax", "Withholding Tax"),
                    ("arrears_deduction", "Arrears Deduction"),
                    ("adjustment", "Adjustment"),
                    ("bonus", "Bonus"),
                    ("manual_credit", "Manual Credit"),
                    ("spin_reward", "Spin Reward"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ManagerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "wht_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.2000"), max_digits=5
                    ),
                ),
                (
                    "wht_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("destination_phone", models.CharField(blank=True, max_length=20)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managerpayouts",
                        to="earnings.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager Payout",
                "verbose_name_plural": "Manager Payouts",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="MerchantPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(blank=True, max_length=100)),
                ("device_description", models.CharField(blank=True, max_length=200)),
                ("cash_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("external_processing", "External Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchant_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Payout",
                "verbose_name_plural": "Merchant Payouts",
                "ordering": ["-created_at"],
            },
        ),
    ]
