# Generated by Django 6.0.5 on 2026-05-28 07:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0002_add_manager_merchant_payout_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantpayout",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="merchantpayout",
            name="financed_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="merchantpayout",
            name="merchant_commission_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="merchantpayout",
            name="merchant_commission_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0100"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="merchantpayout",
            name="total_payable",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
    ]
