# Generated by Django 6.0.5 on 2026-05-28 07:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_applicationfieldreview"),
        ("commissions", "0001_initial"),
        ("merchants", "0001_initial"),
        ("portal", "0002_add_device_lock_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantContractPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "financed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "merchant_commission_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0100"), max_digits=5
                    ),
                ),
                (
                    "merchant_commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_payable",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("bank", "Bank Transfer"),
                            ("airtel_money", "Airtel Money"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("destination_name", models.CharField(blank=True, max_length=120)),
                ("destination_account", models.CharField(blank=True, max_length=120)),
                ("destination_phone", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_payout",
                        to="portal.paymentcontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_payouts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Contract Payout",
                "verbose_name_plural": "Merchant Contract Payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("repayment_commission", "Repayment Commission"),
                            ("arrears_deduction", "Arrears Deduction"),
                            ("monthly_wht_deduction", "Monthly WHT Deduction"),
                            ("monthly_payout", "Monthly Payout"),
                            ("manual_adjustment", "Manual Adjustment"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Signed: positive=earn, negative=deduct",
                        max_digits=14,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("missed_date", models.DateField(blank=True, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_ledger_entries",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_ledger_entries",
                        to="portal.paymentcontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_ledger_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_ledger_entries",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "source_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_ledger_entries",
                        to="portal.paymenttransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Ledger Entry",
                "verbose_name_plural": "Commission Ledger",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("entry_type", "repayment_commission"),
                            ("source_payment__isnull", False),
                        ),
                        fields=("source_payment", "user", "entry_type"),
                        name="unique_repayment_commission_per_payment_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("entry_type", "arrears_deduction"),
                            ("missed_date__isnull", False),
                        ),
                        fields=("contract", "user", "missed_date", "entry_type"),
                        name="unique_arrears_deduction_per_contract_user_date",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnderwriterMonthlyPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "gross_commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "wht_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.2000"), max_digits=5
                    ),
                ),
                (
                    "wht_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=14,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("destination_phone", models.CharField(blank=True, max_length=30)),
                ("destination_bank", models.CharField(blank=True, max_length=120)),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Underwriter Monthly Payout",
                "verbose_name_plural": "Underwriter Monthly Payouts",
                "ordering": ["-period_end"],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
    ]
