# Generated by Django 6.0.5 on 2026-05-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("district", models.CharField(max_length=100)),
                (
                    "role_interested",
                    models.CharField(
                        choices=[
                            ("sales_agent", "Sales Agent"),
                            ("underwriter", "Underwriter"),
                            ("merchant_admin", "Merchant Administrator"),
                            ("customer_support", "Customer Support Agent"),
                            ("software_engineer", "Software Engineer"),
                            ("data_analyst", "Data / Credit Risk Analyst"),
                            ("operations_manager", "Operations Manager"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "cv_file",
                    models.FileField(blank=True, null=True, upload_to="career_cvs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("contacted", "Contacted"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Lead",
                "verbose_name_plural": "Career Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("owner_full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=30)),
                ("whatsapp_phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("district", models.CharField(max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("phone_shop", "Phone Shop"),
                            ("electronics_shop", "Electronics Shop"),
                            ("mixed_retail", "Mixed Retail"),
                            ("agent", "Agent"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "estimated_monthly_phone_sales",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "has_business_registration",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "preferred_payout_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank", "Bank Transfer"),
                            ("airtel_money", "Airtel Money"),
                            ("tnm_mpamba", "TNM Mpamba"),
                            ("not_sure", "Not sure yet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="public_site", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Lead",
                "verbose_name_plural": "Merchant Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
