# Generated by Django 6.0.5 on 2026-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantlead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New Lead"),
                    ("contacted", "Contacted"),
                    ("kyc_pending", "KYC Pending"),
                    ("documents_pending", "Documents Pending"),
                    ("site_visit_needed", "Site Visit Needed"),
                    ("awaiting_hq", "Awaiting HQ Approval"),
                    ("qualified", "Qualified"),
                    ("approved", "Approved"),
                    ("converted", "Converted"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
