# Generated by Django 5.2.5 on 2026-05-11 04:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0034_alter_business_business_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "opening_cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "opening_stock_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "opening_receivables",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "current_cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "current_stock_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "current_receivables",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "sales_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "cost_of_goods_sold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "recorded_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "capital_injection",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "owner_withdrawals",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "loans_received",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "loan_repayments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "tolerance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1000.00"), max_digits=18
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_enough_data", "Not enough data"),
                            ("balanced", "Books Balanced"),
                            ("winning", "You Are Winning"),
                            ("warning_missing_money", "Warning: Missing Money"),
                            ("warning_costs", "Warning: Costs Not Recorded"),
                            ("warning_receivables", "Warning: Receivables Too High"),
                            ("danger", "Books Not Balanced"),
                        ],
                        db_index=True,
                        default="not_enough_data",
                        max_length=32,
                    ),
                ),
                ("recommendation", models.TextField(blank=True, default="")),
                ("badges", models.JSONField(blank=True, default=list)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_health_checks",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "date"],
                        name="dashboard_b_busines_990a40_idx",
                    ),
                    models.Index(
                        fields=["business", "status", "date"],
                        name="dashboard_b_busines_0bee61_idx",
                    ),
                ],
                "unique_together": {("business", "date")},
            },
        ),
    ]
