# Generated by Django 6.0.5 on 2026-05-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_applicationfieldreview"),
        ("portal", "0003_paymenttransaction_commissionable_amount"),
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imei", models.CharField(blank=True, max_length=20)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "Mock / Placeholder"),
                            ("imei_db", "IMEI Database"),
                            ("manufacturer", "Manufacturer API"),
                        ],
                        default="mock",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "warranty_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expired", "Expired"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "lock_eligible",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this device can be enrolled in PayG lock",
                    ),
                ),
                ("response_summary", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_checks",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_checks",
                        to="portal.paymentcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Check",
                "ordering": ["-checked_at"],
            },
        ),
    ]
