# Generated by Django 6.0.5 on 2026-05-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_applicationfieldreview"),
        ("risk", "0002_add_device_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "phone_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("none", "No Risk"),
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("block", "Block — Do Not Proceed"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("proceed", "Proceed"),
                            ("manual_review", "Manual Review"),
                            ("require_hq_approval", "Require HQ Approval"),
                            ("block_new_contract", "Block New Contract"),
                        ],
                        default="proceed",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("cleared", "Cleared"),
                            ("blocked", "Blocked"),
                            ("hq_override", "HQ Override"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_checks",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_checks_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_checks_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraud Check",
                "ordering": ["-created_at"],
            },
        ),
    ]
