# Generated by Django 5.2.5 on 2025-12-03 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this backup was initiated.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the backup.",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="ZIP file containing the backup data.",
                        null=True,
                        upload_to="backups/%Y/%m/",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Size of the backup file in bytes.",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if backup failed.",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this backup completed (success or failure).",
                        null=True,
                    ),
                ),
                (
                    "records_count",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Count of records per model type included in this backup.",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business this backup belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_snapshots",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who requested this backup (usually a manager).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Snapshot",
                "verbose_name_plural": "Backup Snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-created_at"],
                        name="backups_bac_busines_124cdb_idx",
                    ),
                    models.Index(
                        fields=["business", "status"],
                        name="backups_bac_busines_90debf_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="backups_bac_status_6a387d_idx",
                    ),
                ],
            },
        ),
    ]
