# Generated by Django 5.2.5 on 2026-05-11 05:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0001_initial"),
        ("tenants", "0034_alter_business_business_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("all", "Everything"),
                            ("inventory", "Inventory"),
                            ("financial", "Financial"),
                            ("staff", "Staff & HR"),
                            ("sales", "Sales"),
                            ("wallet", "Wallet"),
                            ("reports", "Reports"),
                            ("marketplace", "Marketplace"),
                            ("restore", "Restore"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("zip", "ZIP Package"),
                            ("csv", "CSV Package"),
                            ("xlsx", "Excel Workbook"),
                            ("pdf", "PDF Summary"),
                        ],
                        default="zip",
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("records_count", models.JSONField(blank=True, default=dict)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_logs",
                        to="tenants.business",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_logs",
                        to="backups.backupsnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_export_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-created_at"],
                        name="backups_dat_busines_d81906_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "-created_at"],
                        name="backups_dat_busines_a5f3a2_idx",
                    ),
                    models.Index(
                        fields=["business", "export_format", "-created_at"],
                        name="backups_dat_busines_48d590_idx",
                    ),
                ],
            },
        ),
    ]
