# Generated by Django 6.0.5 on 2026-05-27 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=15, unique=True),
                ),
                (
                    "payg_number",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("customer_name", models.CharField(max_length=180)),
                ("customer_phone", models.CharField(max_length=30)),
                ("customer_national_id", models.CharField(blank=True, max_length=80)),
                ("device_model", models.CharField(blank=True, max_length=120)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "daily_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "thirty_day_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("lock_date", models.DateField(blank=True, null=True)),
                ("term_months", models.PositiveIntegerField(default=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("overdue", "Overdue"),
                            ("locked", "Locked"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "early_settlement_3m_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=25,
                        help_text="Percentage discount for 3-month early settlement",
                        max_digits=5,
                    ),
                ),
                (
                    "early_settlement_6m_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=15,
                        help_text="Percentage discount for 6-month early settlement",
                        max_digits=5,
                    ),
                ),
                (
                    "early_settlement_9m_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=8,
                        help_text="Percentage discount for 9-month early settlement",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financing_contract",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_contract",
                        to="financing.financingcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "Mock / Sandbox"),
                            ("paychangu", "PayChangu"),
                            ("airtel_money", "Airtel Money"),
                            ("tnm_mpamba", "TNM Mpamba"),
                            ("paytrigger", "PayTrigger"),
                        ],
                        default="mock",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="MWK", max_length=5)),
                ("phone", models.CharField(max_length=30)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("external_processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portal.paymentcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentcontract",
            index=models.Index(
                fields=["contract_number"], name="portal_paym_contrac_e7608c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentcontract",
            index=models.Index(
                fields=["payg_number"], name="portal_paym_payg_nu_b92f51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentcontract",
            index=models.Index(
                fields=["customer_phone"], name="portal_paym_custome_205939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentcontract",
            index=models.Index(
                fields=["customer_national_id"], name="portal_paym_custome_ea0c10_idx"
            ),
        ),
    ]
