# Generated by Django 6.0.5 on 2026-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcontract",
            name="device_enrollment_status",
            field=models.CharField(
                blank=True,
                default="none",
                help_text="MDM enrollment state: none, pending, enrolled, failed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="device_lock_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MDM/lock provider: mock, knox, nuovopay, upya, or empty for none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="device_lock_status",
            field=models.CharField(
                blank=True,
                default="unknown",
                help_text="Current lock state: unknown, unlocked, locked, pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="last_lock_error",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last error message from lock provider",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paymentcontract",
            name="last_lock_sync_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time lock status was synced with provider",
                null=True,
            ),
        ),
    ]
