# Generated by Django 6.0.5 on 2026-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_add_device_lock_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="commissionable_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount eligible for underwriter commission (excludes deposit)",
                max_digits=12,
            ),
        ),
    ]
