# Generated by Django 6.0.5 on 2026-05-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_applicationfieldreview"),
        ("portal", "0003_paymenttransaction_commissionable_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcontract",
            name="source_application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_contract",
                to="applications.financingapplication",
            ),
        ),
    ]
