# Generated by Django 5.2.5 on 2025-09-06 20:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_wallettxn_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_order_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_prices', to='inventory.product')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['product', 'active'], name='ordprice_prod_active_idx'), models.Index(fields=['effective_from'], name='ordprice_effective_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('product', 'active'), name='uniq_active_order_price_per_product')],
            },
        ),
    ]
