# Generated by Django 4.2.24 on 2025-09-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_membership_role_and_more'),
        ('inventory', '0016_orderprice'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='invitem_active_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='invitem_prod_loc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inv_received_idx',
            old_name='invitem_received_at_idx',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='tenants.business'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['business', 'product', 'current_location', 'status'], name='inv_bpls_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['business', 'is_active', 'status'], name='inv_bis_idx'),
        ),
    ]
