# Generated by Django 4.2.24 on 2025-09-15 20:43

from django.db import migrations, models
from django.db.migrations.operations.models import RemoveIndex
import django.db.models.deletion


class SafeRemoveIndex(RemoveIndex):
    """
    Prevents ValueError if index is missing from migration state.
    """
    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except ValueError:
            pass


def drop_inventory_indexes_database(apps, schema_editor):
    """Drop inventory indexes using idempotent SQL. Safe to run even if indexes don't exist."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor in ('postgresql', 'sqlite'):
            cursor.execute("DROP INDEX IF EXISTS invitem_active_status_idx")
            cursor.execute("DROP INDEX IF EXISTS invitem_prod_loc_status_idx")


def reverse_drop_inventory_indexes_database(apps, schema_editor):
    """Reverse: no-op (indexes are being removed)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_membership_role_and_more'),
        ('inventory', '0016_orderprice'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_inventory_indexes_database,
                    reverse_drop_inventory_indexes_database,
                ),
            ],
            state_operations=[
                SafeRemoveIndex(
                    model_name='inventoryitem',
                    name='invitem_active_status_idx',
                ),
                SafeRemoveIndex(
                    model_name='inventoryitem',
                    name='invitem_prod_loc_status_idx',
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inv_received_idx',
            old_name='invitem_received_at_idx',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='tenants.business'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['business', 'product', 'current_location', 'status'], name='inv_bpls_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['business', 'is_active', 'status'], name='inv_bis_idx'),
        ),
    ]
