# Generated by Django 4.2.23 on 2025-09-16 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_membership_role_and_more'),
        ('inventory', '0017_remove_inventoryitem_invitem_active_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaudit',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audits', to='tenants.business'),
        ),
        migrations.AddField(
            model_name='location',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.business'),
        ),
        migrations.AddField(
            model_name='warrantychecklog',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.business'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='imei',
            field=models.CharField(blank=True, help_text='15-digit IMEI. Unique per business when provided.', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'IMEI must be exactly 15 digits.')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('business', 'name')},
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['business', 'action', 'at'], name='invaudit_biz_action_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['business', 'imei'], name='inv_biz_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['business', 'name'], name='loc_biz_name_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantychecklog',
            index=models.Index(fields=['business', 'imei', 'created_at'], name='wcl_biz_imei_created'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('imei__isnull', False)), fields=('business', 'imei'), name='uniq_imei_per_business'),
        ),
    ]
