# Generated by Django 4.2.23 on 2025-09-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_inventoryaudit_business_location_business_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_imei_per_business',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In stock'), ('SOLD', 'Sold')], db_index=True, default='IN_STOCK', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('imei__isnull', False), models.Q(('imei', ''), _negated=True)), fields=('business', 'imei'), name='uniq_imei_per_business'),
        ),
    ]
