# Generated by Django 4.2.23 on 2025-09-22 13:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_inventoryitem_uniq_imei_per_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_default',
            field=models.BooleanField(default=False, help_text='When true, this is the default store/location for this business.'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Must be zero or positive.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='received_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['business', 'is_default'], name='loc_biz_isdefault_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('business', 'is_default'), name='one_default_location_per_business'),
        ),
    ]
