# Generated by Django 4.2.23 on 2025-10-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_agentinvite_expires_at_agentinvite_invited_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_location_is_default_alter_inventoryitem_order_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('phones', 'Phones & Electronics'), ('liquor', 'Liquor / Bar'), ('grocery', 'Grocery / General'), ('pharmacy', 'Pharmacy'), ('clothing', 'Clothing')], default='grocery', max_length=20)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('scan_required', models.BooleanField(default=False)),
                ('base_unit', models.CharField(choices=[('unit', 'Unit'), ('shot', 'Shot'), ('ml', 'ml'), ('g', 'g')], default='unit', max_length=10)),
                ('track_inventory', models.BooleanField(default=True)),
                ('has_shots', models.BooleanField(default=False)),
                ('shots_per_bottle', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MerchUnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('unit', 'Unit'), ('dozen', 'Dozen (12)'), ('box', 'Box'), ('crate', 'Crate'), ('bottle', 'Bottle'), ('shot', 'Shot')], max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=3, help_text='How many base units in this pack (e.g., 12 for dozen, 24 for bottle of 24 shots, 1 for unit).', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside')], max_length=8, null=True)),
                ('last_credited_at', models.DateTimeField(blank=True, null=True)),
                ('inside_seconds', models.IntegerField(default=0)),
                ('outside_seconds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Phone Product',
                'verbose_name_plural': 'Phone Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
        migrations.AddField(
            model_name='timelog',
            name='event',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('ping', 'Ping'), ('end', 'End')], max_length=10),
        ),
        migrations.AddField(
            model_name='timelog',
            name='geofence',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['event', 'logged_at'], name='timelog_event_logged_idx'),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.business'),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchunitprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='inventory.merchproduct'),
        ),
        migrations.AddField(
            model_name='merchproduct',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_products', to='tenants.business'),
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Clothing Product',
                'verbose_name_plural': 'Clothing Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.merchproduct',),
        ),
        migrations.CreateModel(
            name='LiquorProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Liquor Product',
                'verbose_name_plural': 'Liquor Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.merchproduct',),
        ),
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Pharmacy Product',
                'verbose_name_plural': 'Pharmacy Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.merchproduct',),
        ),
        migrations.AddIndex(
            model_name='shiftsession',
            index=models.Index(fields=['user', 'started_at'], name='shift_user_started_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftsession',
            index=models.Index(fields=['business', 'started_at'], name='shift_biz_started_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftsession',
            index=models.Index(fields=['ended_at'], name='shift_ended_idx'),
        ),
        migrations.AddIndex(
            model_name='merchunitprice',
            index=models.Index(fields=['product', 'label'], name='merchprice_prod_label_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchunitprice',
            unique_together={('product', 'label')},
        ),
        migrations.AddIndex(
            model_name='merchproduct',
            index=models.Index(fields=['business', 'name'], name='merchprod_biz_name_idx'),
        ),
        migrations.AddIndex(
            model_name='merchproduct',
            index=models.Index(fields=['business', 'kind'], name='merchprod_biz_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='merchproduct',
            index=models.Index(fields=['is_active'], name='merchprod_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchproduct',
            unique_together={('business', 'name')},
        ),
    ]
