# Generated by Django 4.2.23 on 2025-10-27 19:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_agentinvite_expires_at_agentinvite_invited_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0021_merchproduct_merchunitprice_shiftsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVOICE', 'Invoice'), ('QUOTE', 'Quotation')], default='INVOICE', max_length=16)),
                ('reference', models.CharField(help_text='Human reference/number shown to customer.', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=12)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=40)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.doc')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['type', 'status'], name='inventory_d_type_b2a3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['created_at'], name='inventory_d_created_20aa93_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['reference'], name='inventory_d_referen_dd5d34_idx'),
        ),
    ]
