# Generated by Django 4.2.23 on 2025-10-28 00:23

from django.db import migrations, models
from django.db.migrations.operations.models import RemoveIndex
import django.db.models.deletion
import django.utils.timezone


class SafeRemoveIndex(RemoveIndex):
    """
    Prevents ValueError if index is missing from migration state.
    """

    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except ValueError:
            pass


def drop_timelog_indexes_database(apps, schema_editor):
    """Drop timelog indexes using idempotent SQL. Safe to run even if indexes don't exist."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor in ("postgresql", "sqlite"):
            cursor.execute("DROP INDEX IF EXISTS timelog_user_logged_idx")
            cursor.execute("DROP INDEX IF EXISTS timelog_location_logged_idx")
            cursor.execute("DROP INDEX IF EXISTS timelog_event_logged_idx")


def reverse_drop_timelog_indexes_database(apps, schema_editor):
    """Reverse: no-op (indexes are being removed)"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_agentinvite_location_membership_location"),
        ("inventory", "0022_doc_docitem_doc_inventory_d_type_b2a3e3_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timelog",
            options={"ordering": ("-ts",)},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_timelog_indexes_database,
                    reverse_drop_timelog_indexes_database,
                ),
            ],
            state_operations=[
                SafeRemoveIndex(
                    model_name="timelog",
                    name="timelog_user_logged_idx",
                ),
                SafeRemoveIndex(
                    model_name="timelog",
                    name="timelog_location_logged_idx",
                ),
                SafeRemoveIndex(
                    model_name="timelog",
                    name="timelog_event_logged_idx",
                ),
            ],
        ),
        migrations.RenameField(
            model_name="timelog",
            old_name="latitude",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="timelog",
            old_name="longitude",
            new_name="lon",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="accuracy_m",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="checkin_type",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="distance_m",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="event",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="geofence",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="logged_at",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="note",
        ),
        migrations.RemoveField(
            model_name="timelog",
            name="within_geofence",
        ),
        migrations.AddField(
            model_name="timelog",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_logs",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="kind",
            field=models.CharField(
                choices=[("ARRIVAL", "Arrival"), ("DEPARTURE", "Departure")],
                db_index=True,
                default="ARRIVAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="timelog",
            name="ts",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_logs",
                to="inventory.location",
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["business", "ts"], name="timelog_biz_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["user", "ts"], name="timelog_user_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["location", "ts"], name="timelog_loc_ts_idx"),
        ),
    ]
