# Generated by Django 4.2.23 on 2025-10-31 18:14

from django.db import migrations, models
from django.db.migrations.operations.models import RemoveConstraint, RemoveIndex
import django.utils.timezone


def cleanup_uniq_imei_per_business(apps, schema_editor):
    """
    Drop both constraint and index for uniq_imei_per_business if they exist (Postgres only).
    This handles the case where a previous migration run left behind the constraint or index.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    InventoryItem = apps.get_model("inventory", "InventoryItem")
    table = InventoryItem._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        # 1) Drop constraint if it exists (this also removes its backing index)
        cursor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "uniq_imei_per_business";')
        # 2) Drop any leftover index if it still exists
        cursor.execute('DROP INDEX IF EXISTS "uniq_imei_per_business";')


class SafeRemoveConstraint(RemoveConstraint):
    """
    Prevents ValueError if constraint is missing from migration state.
    """

    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except ValueError:
            pass


class SafeRemoveIndex(RemoveIndex):
    """
    Prevents ValueError if index is missing from migration state.
    """

    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except ValueError:
            pass


def drop_constraint_and_indexes_database(apps, schema_editor):
    """
    Drop constraint and indexes using idempotent SQL.
    Safe to run even if they don't exist (handles state drift).
    """
    vendor = schema_editor.connection.vendor

    InventoryItem = apps.get_model("inventory", "InventoryItem")
    OrderPrice = apps.get_model("inventory", "OrderPrice")

    inventory_table = InventoryItem._meta.db_table
    orderprice_table = OrderPrice._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            # Drop constraint if exists (PostgreSQL)
            cursor.execute(
                f"""
                ALTER TABLE {inventory_table} 
                DROP CONSTRAINT IF EXISTS uniq_imei_per_business
            """
            )
            # Drop indexes if exist
            cursor.execute("DROP INDEX IF EXISTS ordprice_prod_active_idx")
            cursor.execute("DROP INDEX IF EXISTS ordprice_effective_idx")
        elif vendor == "sqlite":
            # SQLite: Drop indexes (SQLite doesn't support DROP CONSTRAINT the same way)
            cursor.execute("DROP INDEX IF EXISTS uniq_imei_per_business")
            cursor.execute("DROP INDEX IF EXISTS ordprice_prod_active_idx")
            cursor.execute("DROP INDEX IF EXISTS ordprice_effective_idx")
        # Other databases: skip (should not happen in production)


def reverse_drop_constraint_and_indexes_database(apps, schema_editor):
    """Reverse: Recreate constraint and indexes (not typically needed, but for completeness)"""
    # This is a no-op since we're removing them - reverse would require
    # knowing the original definition, which is complex. In practice,
    # this migration should not be reversed.
    pass


class Migration(migrations.Migration):
    # Make sure this matches your previous migration
    dependencies = [
        ("inventory", "0025_backfill_location_non_null"),
    ]

    operations = [
        # --- PRE-FLIGHT: clean up duplicate auto-named indexes left by earlier runs ---
        migrations.RunSQL(
            "DROP INDEX IF EXISTS inventory_inventoryitem_is_active_435aae93;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS inventory_inventoryitem_status_59404d58;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS inventory_inventoryitem_status_59404d58_like;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # --- Remove constraint and indexes using SeparateDatabaseAndState ---
        # This prevents state drift errors when constraint/index doesn't exist in Django's state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_constraint_and_indexes_database,
                    reverse_drop_constraint_and_indexes_database,
                ),
            ],
            state_operations=[
                # State operations: Remove from Django's migration state
                SafeRemoveConstraint(
                    model_name="inventoryitem",
                    name="uniq_imei_per_business",
                ),
                SafeRemoveIndex(
                    model_name="orderprice",
                    name="ordprice_prod_active_idx",
                ),
                SafeRemoveIndex(
                    model_name="orderprice",
                    name="ordprice_effective_idx",
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(
                choices=[("IN_STOCK", "In stock"), ("SOLD", "Sold")],
                db_index=True,
                default="IN_STOCK",
                max_length=10,
            ),
        ),
        # Drop stale constraint and index before creating the constraint (fixes Render Postgres deploy)
        migrations.RunPython(cleanup_uniq_imei_per_business, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("imei__isnull", False), models.Q(("imei", ""), _negated=True)),
                fields=("business", "imei"),
                name="uniq_imei_per_business",
            ),
        ),
    ]
