# Generated by Django 5.2.5 on 2025-12-01 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025a_preflight_drop_dupe_indexes"),
        ("inventory", "0026_remove_inventoryitem_uniq_imei_per_business_and_more"),
    ]

    operations = []
