# Generated by Django 5.2.5 on 2025-12-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warranty_and_approval'),
        ('inventory', '0029_verticals_models'),
    ]

    operations = [
    ]
