# Generated by Django 5.2.5 on 2025-12-01 23:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_merge_20251202_0148"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquorShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "total_sales_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_cost_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_profit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_credit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_free_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "missing_stock_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("opening_notes", models.TextField(blank=True, default="")),
                ("closing_notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LiquorShiftStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bottles_count",
                    models.IntegerField(default=0, help_text="Full bottles in stock"),
                ),
                (
                    "shots_count",
                    models.IntegerField(
                        default=0,
                        help_text="Individual shots available (from open bottles)",
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening Stock"),
                            ("closing", "Closing Stock"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("was_adjusted", models.BooleanField(default=False)),
                ("adjustment_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["shift", "product"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="gymmember",
            name="unique_gym_member_phone",
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inv_wty_stat_exp_idx",
        ),
        migrations.RenameIndex(
            model_name="clothingproductlog",
            new_name="inventory_c_product_3de679_idx",
            old_name="clothing_log_prod_idx",
        ),
        migrations.RenameIndex(
            model_name="clothingproductlog",
            new_name="inventory_c_action_fb45a9_idx",
            old_name="clothing_log_action_idx",
        ),
        migrations.RenameIndex(
            model_name="clothingsale",
            new_name="inventory_c_busines_95cc06_idx",
            old_name="clothing_sale_idx",
        ),
        migrations.RenameIndex(
            model_name="gymmember",
            new_name="inventory_g_busines_4bb5aa_idx",
            old_name="gym_member_status_idx",
        ),
        migrations.RenameIndex(
            model_name="gymmember",
            new_name="inventory_g_phone_965bdc_idx",
            old_name="gym_member_phone_idx",
        ),
        migrations.RenameIndex(
            model_name="gymmemberlog",
            new_name="inventory_g_member__a7a884_idx",
            old_name="gym_log_member_idx",
        ),
        migrations.RenameIndex(
            model_name="gymmemberlog",
            new_name="inventory_g_action_e951a0_idx",
            old_name="gym_log_action_idx",
        ),
        migrations.RenameIndex(
            model_name="gympayment",
            new_name="inventory_g_member__83f276_idx",
            old_name="gym_payment_member_idx",
        ),
        migrations.RenameIndex(
            model_name="gympayment",
            new_name="inventory_g_start_d_b86e33_idx",
            old_name="gym_payment_dates_idx",
        ),
        migrations.RenameIndex(
            model_name="gymwalletentry",
            new_name="inventory_g_busines_635566_idx",
            old_name="gym_wallet_idx",
        ),
        migrations.RenameIndex(
            model_name="gymwalletentry",
            new_name="inventory_g_entry_t_6d1684_idx",
            old_name="gym_wallet_type_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorcredit",
            new_name="inventory_l_busines_54ec45_idx",
            old_name="liquor_credit_status_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorcredit",
            new_name="inventory_l_custome_4627f6_idx",
            old_name="liquor_credit_customer_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorcreditpayment",
            new_name="inventory_l_status_794172_idx",
            old_name="liquor_payment_status_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorcreditpayment",
            new_name="inventory_l_credit__ce20b8_idx",
            old_name="liquor_payment_credit_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorexpense",
            new_name="inventory_l_busines_054ad1_idx",
            old_name="liquor_expense_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorsale",
            new_name="inventory_l_busines_bf04c3_idx",
            old_name="liquor_sale_biz_date_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorsale",
            new_name="inventory_l_busines_ab15ca_idx",
            old_name="liquor_sale_type_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorsale",
            new_name="inventory_l_is_cred_14a3f0_idx",
            old_name="liquor_sale_credit_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorstockeditrequest",
            new_name="inventory_l_busines_d9a7f2_idx",
            old_name="liquor_stock_req_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorstockeditrequest",
            new_name="inventory_l_product_a9fe21_idx",
            old_name="liquor_stock_prod_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorwalletentry",
            new_name="inventory_l_busines_ad1f31_idx",
            old_name="liquor_wallet_idx",
        ),
        migrations.RenameIndex(
            model_name="liquorwalletentry",
            new_name="inventory_l_entry_t_a28c64_idx",
            old_name="liquor_wallet_type_idx",
        ),
        # Removed 3 RenameIndex operations for deleted PhoneStockEditRequest model
        # to avoid KeyError: ('inventory', 'phonestockeditrequest')
        migrations.RunSQL(sql="", reverse_sql=""),
        migrations.AddField(
            model_name="liquorcredit",
            name="customer_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Physical description or identifying info (e.g., 'short guy, red jacket, comes Fridays')",
            ),
        ),
        migrations.AddField(
            model_name="liquorcredit",
            name="customer_photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo to help identify customer",
                null=True,
                upload_to="liquor/customer_photos/",
            ),
        ),
        migrations.AddField(
            model_name="liquorcredit",
            name="settled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liquor_credits_settled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquorsale",
            name="is_free",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True for barman shots or complimentary drinks",
            ),
        ),
        migrations.AddField(
            model_name="liquorsale",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="liquorsale",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost per unit sold",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="merchproduct",
            name="cost_per_bottle",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost price for a full bottle",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="merchproduct",
            name="cost_per_shot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost price per shot",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="warranty_expiration",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Warranty expiration date if available",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="liquorsale",
            name="sale_type",
            field=models.CharField(
                choices=[
                    ("sale", "Cash Sale"),
                    ("credit", "Credit Sale"),
                    ("free", "Free (Barman/Complimentary)"),
                    ("undecided", "Undecided"),
                ],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="liquorsale",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gymmember",
            unique_together={("business", "phone")},
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["warranty_status", "warranty_expiration"],
                name="inv_wty_stat_exp_idx",
            ),
        ),
        migrations.AddField(
            model_name="liquorshift",
            name="barman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquor_shifts_worked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquorshift",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liquor_shifts",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="liquorshift",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquor_shifts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquorshift",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liquor_shifts",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="liquorsale",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="inventory.liquorshift",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorsale",
            index=models.Index(
                fields=["shift", "-sold_at"], name="inventory_l_shift_i_082bc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liquorsale",
            index=models.Index(
                fields=["business", "is_free", "-sold_at"],
                name="inventory_l_busines_8c2e32_idx",
            ),
        ),
        migrations.AddField(
            model_name="liquorshiftstock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_stock_snapshots",
                to="inventory.merchproduct",
            ),
        ),
        migrations.AddField(
            model_name="liquorshiftstock",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquorshiftstock",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_snapshots",
                to="inventory.liquorshift",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorshift",
            index=models.Index(
                fields=["business", "status", "-started_at"],
                name="inventory_l_busines_f49361_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorshift",
            index=models.Index(
                fields=["barman", "-started_at"], name="inventory_l_barman__d2b32d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liquorshift",
            index=models.Index(
                fields=["business", "-started_at"],
                name="inventory_l_busines_4cecf0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorshiftstock",
            index=models.Index(
                fields=["shift", "snapshot_type"], name="inventory_l_shift_i_e4a052_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="liquorshiftstock",
            index=models.Index(
                fields=["product", "shift"], name="inventory_l_product_925b0d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="liquorshiftstock",
            unique_together={("shift", "product", "snapshot_type")},
        ),
    ]
