# Generated by Django 5.2.5 on 2025-12-02 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0031_liquor_shift_system"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingsale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank"),
                    ("mobile_money", "Mobile Money"),
                ],
                db_index=True,
                default="cash",
                help_text="Payment method used for this sale",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="liquorsale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank"),
                    ("mobile_money", "Mobile Money"),
                ],
                db_index=True,
                default="cash",
                help_text="Payment method used for this sale",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="clothingsale",
            index=models.Index(
                fields=["business", "payment_method", "-sold_at"],
                name="inventory_c_busines_380775_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorsale",
            index=models.Index(
                fields=["business", "payment_method", "-sold_at"],
                name="inventory_l_busines_1c87ba_idx",
            ),
        ),
    ]
