# Generated by Django 5.2.5 on 2025-12-02 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0032_add_payment_method_and_penalties"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("BANK", "Bank"),
                    ("MOBILE_MONEY", "Mobile Money"),
                ],
                default="CASH",
                help_text="Payment method used when sold",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PharmacyBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(help_text="Manufacturer batch/lot number", max_length=100),
                ),
                (
                    "expiry_date",
                    models.DateField(db_index=True, help_text="Expiry date (day/month/year)"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, help_text="Current quantity in stock"),
                ),
                (
                    "reorder_level",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Alert when stock drops to or below this level",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Supplier name",
                        max_length=200,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date batch was received",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_batches",
                        to="tenants.business",
                    ),
                ),
                (
                    "merch_product",
                    models.ForeignKey(
                        help_text="Product this batch belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_batches",
                        to="inventory.merchproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy Batch",
                "verbose_name_plural": "Pharmacy Batches",
                "ordering": ["expiry_date", "batch_number"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 500mg, 10ml, 250mg/5ml",
                        max_length=50,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("suspension", "Suspension"),
                            ("injection", "Injection"),
                            ("cream", "Cream"),
                            ("ointment", "Ointment"),
                            ("drops", "Drops"),
                            ("inhaler", "Inhaler"),
                            ("powder", "Powder"),
                            ("other", "Other"),
                        ],
                        default="tablet",
                        help_text="Dosage form",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("analgesic", "Analgesic (Pain Relief)"),
                            ("antibiotic", "Antibiotic"),
                            ("antifungal", "Antifungal"),
                            ("antiviral", "Antiviral"),
                            ("antihistamine", "Antihistamine"),
                            ("antipyretic", "Antipyretic (Fever)"),
                            ("antihypertensive", "Antihypertensive (Blood Pressure)"),
                            ("antidiabetic", "Antidiabetic"),
                            ("vitamin", "Vitamin/Supplement"),
                            ("antiparasitic", "Antiparasitic"),
                            ("respiratory", "Respiratory"),
                            ("gastrointestinal", "Gastrointestinal"),
                            ("dermatological", "Dermatological"),
                            ("contraceptive", "Contraceptive"),
                            ("other", "Other"),
                        ],
                        default="",
                        help_text="Drug category",
                        max_length=30,
                    ),
                ),
                (
                    "requires_prescription",
                    models.BooleanField(
                        default=False,
                        help_text="True if this drug requires a prescription",
                    ),
                ),
                (
                    "is_generic",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a generic (non-branded) drug",
                    ),
                ),
                (
                    "active_ingredient",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Active pharmaceutical ingredient (API)",
                        max_length=255,
                    ),
                ),
                (
                    "storage_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Special storage requirements (e.g. refrigerate, keep dry)",
                    ),
                ),
                (
                    "merch_product",
                    models.OneToOneField(
                        help_text="Base product reference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_info",
                        to="inventory.merchproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy Product Info",
                "verbose_name_plural": "Pharmacy Product Info",
            },
        ),
        migrations.CreateModel(
            name="PharmacySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity sold",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost price per unit (for profit calculation)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale amount (quantity * unit_price)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK", "Bank Transfer"),
                            ("CREDIT", "Credit"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer name (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer phone (optional)",
                        max_length=20,
                    ),
                ),
                (
                    "prescription_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Prescription reference (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch sold from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="inventory.pharmacybatch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_sales",
                        to="tenants.business",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy Sale",
                "verbose_name_plural": "Pharmacy Sales",
                "ordering": ["-sold_at"],
            },
        ),
        migrations.CreateModel(
            name="StockActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_model",
                    models.CharField(
                        help_text="Model name (e.g., 'InventoryItem', 'MerchProduct')",
                        max_length=100,
                    ),
                ),
                (
                    "product_id",
                    models.IntegerField(help_text="ID of the product/stock item"),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Product name (for quick reference)",
                        max_length=255,
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="IMEI (for phones)",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("ADJUST_QUANTITY", "Quantity Adjusted"),
                            ("SOFT_DELETE", "Soft Deleted"),
                            ("DELETE_ATTEMPT", "Delete Attempted (Blocked)"),
                            ("IMPORT", "Bulk Import"),
                            ("RESTORE", "Restored"),
                        ],
                        db_index=True,
                        help_text="Action performed",
                        max_length=32,
                    ),
                ),
                (
                    "old_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantity before change",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "new_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantity after change",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, help_text="Optional note or reason for action"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of request (if available)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, help_text="User agent string", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this action occurred",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business this stock belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_activity_logs",
                        to="tenants.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_activity_logs",
                        to="inventory.location",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null if system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Activity Log",
                "verbose_name_plural": "Stock Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pharmacybatch",
            index=models.Index(
                fields=["business", "merch_product", "expiry_date"],
                name="inventory_p_busines_41a991_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacybatch",
            index=models.Index(
                fields=["business", "expiry_date"],
                name="inventory_p_busines_7ab4b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacybatch",
            index=models.Index(fields=["is_archived"], name="inventory_p_is_arch_67f627_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="pharmacybatch",
            unique_together={("business", "merch_product", "batch_number", "expiry_date")},
        ),
        migrations.AddIndex(
            model_name="pharmacysale",
            index=models.Index(fields=["business", "-sold_at"], name="inventory_p_busines_f3ae6d_idx"),
        ),
        migrations.AddIndex(
            model_name="pharmacysale",
            index=models.Index(fields=["batch", "-sold_at"], name="inventory_p_batch_i_e6938a_idx"),
        ),
        migrations.AddIndex(
            model_name="pharmacysale",
            index=models.Index(fields=["sold_by", "-sold_at"], name="inventory_p_sold_by_b653ce_idx"),
        ),
        migrations.AddIndex(
            model_name="stockactivitylog",
            index=models.Index(
                fields=["business", "-created_at"],
                name="inventory_s_busines_58e254_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockactivitylog",
            index=models.Index(
                fields=["location", "-created_at"],
                name="inventory_s_locatio_24be86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockactivitylog",
            index=models.Index(fields=["action", "-created_at"], name="inventory_s_action_c4198b_idx"),
        ),
        migrations.AddIndex(
            model_name="stockactivitylog",
            index=models.Index(
                fields=["performed_by", "-created_at"],
                name="inventory_s_perform_da34bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockactivitylog",
            index=models.Index(
                fields=["product_model", "product_id"],
                name="inventory_s_product_9c0353_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockactivitylog",
            index=models.Index(fields=["imei"], name="inventory_s_imei_dd3da0_idx"),
        ),
    ]
