# Generated by Django 5.2.5 on 2025-12-03 07:40
# FIXED: Made GymPayment.payment_method addition idempotent for Postgres

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def add_gympayment_payment_method_safe(apps, schema_editor):
    """
    Add payment_method to GymPayment in a Postgres-safe, idempotent way.
    """
    connection = schema_editor.connection

    if connection.vendor == "postgresql":
        # Postgres: Use IF NOT EXISTS
        schema_editor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'inventory_gympayment'
                      AND column_name = 'payment_method'
                ) THEN
                    ALTER TABLE inventory_gympayment
                    ADD COLUMN payment_method VARCHAR(20) DEFAULT 'cash' NOT NULL;
                    
                    CREATE INDEX IF NOT EXISTS inventory_gympayment_payment_method_idx
                    ON inventory_gympayment (payment_method);
                END IF;
            END $$;
        """
        )
    else:
        # SQLite: Check if column exists
        cursor = connection.cursor()
        cursor.execute("PRAGMA table_info(inventory_gympayment)")
        columns = [row[1] for row in cursor.fetchall()]

        if "payment_method" not in columns:
            schema_editor.execute(
                """
                ALTER TABLE inventory_gympayment
                ADD COLUMN payment_method VARCHAR(20) DEFAULT 'cash' NOT NULL;
            """
            )
            schema_editor.execute(
                """
                CREATE INDEX IF NOT EXISTS inventory_gympayment_payment_method_idx
                ON inventory_gympayment (payment_method);
            """
            )


def remove_gympayment_payment_method(apps, schema_editor):
    """Remove payment_method column in reverse migration"""
    connection = schema_editor.connection

    if connection.vendor == "postgresql":
        schema_editor.execute(
            """
            DROP INDEX IF EXISTS inventory_gympayment_payment_method_idx;
            ALTER TABLE inventory_gympayment DROP COLUMN IF EXISTS payment_method;
        """
        )
    else:
        schema_editor.execute(
            """
            DROP INDEX IF EXISTS inventory_gympayment_payment_method_idx;
        """
        )
        # SQLite column drop is handled by Django if supported
        cursor = connection.cursor()
        cursor.execute("PRAGMA table_info(inventory_gympayment)")
        columns = [row[1] for row in cursor.fetchall()]

        if "payment_method" in columns:
            schema_editor.execute(
                """
                ALTER TABLE inventory_gympayment DROP COLUMN payment_method;
            """
            )


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0033_inventoryitem_payment_method_pharmacybatch_and_more"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="activation_detected_at",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="warranty_expires_at",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="warranty_last_checked_at",
        ),
        # Use SeparateDatabaseAndState for idempotent field addition
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_gympayment_payment_method_safe,
                    remove_gympayment_payment_method,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="gympayment",
                    name="payment_method",
                    field=models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        db_index=True,
                        default="cash",
                        help_text="Payment method used for this membership payment",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="warranty_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time warranty was checked with Carlcare",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="warranty_source",
            field=models.CharField(
                blank=True,
                default="carlcare",
                help_text="Source of warranty information (e.g., carlcare)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="warranty_raw",
            field=models.JSONField(
                blank=True,
                help_text="Raw warranty check response for auditing",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="warranty_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("no_warranty", "No warranty"),
                    ("in_warranty", "In warranty"),
                    ("expired", "Expired"),
                    ("activated", "Activated"),
                ],
                default="unknown",
                help_text="Carlcare warranty status for Tecno/Itel phones",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PhoneStockEditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Proposed changes as a dict of field: new_value"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was approved/rejected",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Optional reason for rejection or notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business this edit request belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_edit_requests",
                        to="tenants.business",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Agent who requested the edit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_edit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved/rejected this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_stock_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        help_text="The stock item to be edited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_requests",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "status"],
                        name="inventory_p_busines_4d3f26_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "status"],
                        name="inventory_p_request_c5c279_idx",
                    ),
                    models.Index(
                        fields=["stock", "status"],
                        name="inventory_p_stock_i_48c135_idx",
                    ),
                ],
            },
        ),
    ]
