# Generated by Django 5.2.5 on 2025-12-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0034_add_gym_payment_method"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquorStockThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("beer", "Beer"),
                            ("cider", "Cider"),
                            ("spirits", "Spirits"),
                            ("wine", "Wine"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "full_capacity",
                    models.PositiveIntegerField(
                        default=600,
                        help_text="Target capacity (bottles) when fully stocked",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_stock_thresholds",
                        to="tenants.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_stock_thresholds",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "location", "category"],
                        name="inventory_l_busines_75427c_idx",
                    )
                ],
                "unique_together": {("business", "location", "category")},
            },
        ),
    ]
