# Generated by Django 5.2.5 on 2025-12-03 09:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_liquorstockthreshold"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySalesTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        db_index=True,
                        help_text="Business vertical: liquor, phones, gym, clothing, pharmacy, etc.",
                        max_length=32,
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("month", models.IntegerField(db_index=True, help_text="1-12")),
                (
                    "target_units",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Target number of items/units to sell this month",
                    ),
                ),
                (
                    "target_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Optional revenue target in local currency",
                        max_digits=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_sales_targets",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_sales_targets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_sales_targets",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["business", "vertical", "year", "month"],
                        name="inventory_m_busines_ec7a16_idx",
                    ),
                    models.Index(
                        fields=["business", "location", "vertical", "year", "month"],
                        name="inventory_m_busines_49c451_idx",
                    ),
                ],
                "unique_together": {
                    ("business", "location", "vertical", "year", "month")
                },
            },
        ),
    ]
