# Generated by Django 5.2.5 on 2025-12-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_monthlysalestarget"),
        ("tenants", "0012_add_business_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchproduct",
            name="auto_adjust_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable smart auto-adjust based on sales demand"
            ),
        ),
        migrations.AddField(
            model_name="merchproduct",
            name="auto_adjust_pct",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Increase target by this % over observed peak demand",
            ),
        ),
        migrations.AddField(
            model_name="merchproduct",
            name="target_bottles",
            field=models.PositiveIntegerField(
                default=0, help_text="Desired full stock for this product in bottles"
            ),
        ),
        migrations.CreateModel(
            name="LiquorStockSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beer_target",
                    models.PositiveIntegerField(
                        default=600, help_text="Default target for beer category"
                    ),
                ),
                (
                    "cider_target",
                    models.PositiveIntegerField(
                        default=600, help_text="Default target for cider category"
                    ),
                ),
                (
                    "spirits_target",
                    models.PositiveIntegerField(
                        default=600, help_text="Default target for spirits category"
                    ),
                ),
                (
                    "whiskey_target",
                    models.PositiveIntegerField(
                        default=600, help_text="Default target for whiskey category"
                    ),
                ),
                (
                    "wine_target",
                    models.PositiveIntegerField(
                        default=600, help_text="Default target for wine category"
                    ),
                ),
                (
                    "other_target",
                    models.PositiveIntegerField(
                        default=600, help_text="Default target for other category"
                    ),
                ),
                (
                    "default_auto_adjust_pct",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Default auto-adjust percentage for products (typically 20%)",
                    ),
                ),
                (
                    "auto_adjust_lookback_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days to look back when calculating peak demand",
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_stock_settings",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquor Stock Settings",
                "verbose_name_plural": "Liquor Stock Settings",
            },
        ),
    ]
