# Generated by Django 5.2.5 on 2025-12-03 19:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0037_add_liquor_stock_targets"),
        ("tenants", "0012_add_business_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneProductCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        db_index=True,
                        help_text="Phone brand (e.g., TECNO, ITEL, SAMSUNG)",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name (e.g., Spark 40, Pop 10, A15)",
                        max_length=100,
                    ),
                ),
                (
                    "ram_gb",
                    models.PositiveIntegerField(help_text="RAM in GB (e.g., 4, 8)"),
                ),
                (
                    "rom_gb",
                    models.PositiveIntegerField(help_text="ROM/Storage in GB (e.g., 128, 256)"),
                ),
                (
                    "variant_label",
                    models.CharField(
                        blank=True,
                        help_text="Display label for variant (e.g., '4+128', '8+256')",
                        max_length=20,
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Internal model/SKU number (optional, editable)",
                        max_length=50,
                    ),
                ),
                (
                    "default_cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default cost price (optional)",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "default_selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default selling price (optional)",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this product is active in the catalog",
                    ),
                ),
                (
                    "is_flagship",
                    models.BooleanField(default=False, help_text="Mark as flagship/featured product"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_catalog_products",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "model_name", "ram_gb", "rom_gb"],
                "indexes": [
                    models.Index(fields=["business", "brand"], name="phoneprod_biz_brand_idx"),
                    models.Index(
                        fields=["business", "is_active"],
                        name="phoneprod_biz_active_idx",
                    ),
                    models.Index(fields=["brand", "model_name"], name="phoneprod_brand_model_idx"),
                ],
                "unique_together": {("business", "brand", "model_name", "ram_gb", "rom_gb")},
            },
        ),
    ]
