# Generated by Django - adds payment_method field to GymPayment model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_seed_default_phone_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='gympayment',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cash', 'Cash'),
                    ('bank', 'Bank'),
                    ('mobile_money', 'Mobile Money')
                ],
                default='cash',
                max_length=20,
                db_index=True,
                help_text='Payment method used for this membership payment'
            ),
        ),
    ]

