# Generated by Django 5.2.5 on 2025-12-05 23:42
# Adds assigned_role to InventoryItem for agent/manager stock assignment.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0041_add_gympayment_payment_method"),
        ("tenants", "0012_add_business_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="assigned_role",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("AGENT", "Agent")],
                default="MANAGER",
                help_text="For reporting and filters. Indicates whether stock is manager-owned or agent-owned.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="warranty_expiration",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Warranty expiration date if available",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this stock item belongs to a specific agent; otherwise to the manager/global pool.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["warranty_status", "warranty_expiration"],
                name="inv_wty_stat_exp_idx",
            ),
        ),
    ]
