# Generated by Django 5.2.5 on 2025-12-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0042_add_assigned_role_to_inventoryitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="assigned_role",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("AGENT", "Agent")],
                db_index=True,
                default="MANAGER",
                help_text="For reporting and filters. Indicates whether stock is manager-owned or agent-owned.",
                max_length=20,
            ),
        ),
    ]
