# Generated by Django 5.2.5 on 2025-12-06 15:18

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0045_clothing_cost_tracking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gymcheckin",
            new_name="inventory_g_busines_72ef0c_idx",
            old_name="gymcheckin_biz_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="gymcheckin",
            new_name="inventory_g_member__f5de6c_idx",
            old_name="gymcheckin_mem_ts_idx",
        ),
        migrations.AlterField(
            model_name="clothingproductlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("archived", "Archived"),
                    ("restored", "Restored"),
                    ("stock_in", "Stock In"),
                    ("sold", "Sold"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gymcheckin",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gymsettings",
            name="default_membership_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50000.00"),
                help_text="Default monthly membership fee (30 days)",
                max_digits=10,
            ),
        ),
    ]
