# Generated by Django 5.2.5 on 2025-12-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0048_merge_20251207_1007"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="merchproduct",
            name="merchprod_biz_kind_type_idx",
        ),
        migrations.RenameIndex(
            model_name="pharmacysale",
            new_name="inventory_p_is_dele_fec87a_idx",
            old_name="inventory_ph_is_dele_idx",
        ),
        migrations.RenameIndex(
            model_name="pharmacysale",
            new_name="inventory_p_is_reve_dbcfac_idx",
            old_name="inventory_ph_is_reve_idx",
        ),
        migrations.RemoveField(
            model_name="merchproduct",
            name="product_type",
        ),
        migrations.AlterField(
            model_name="pharmacyproductinfo",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("analgesic", "Analgesic (Pain Relief)"),
                    ("antibiotic", "Antibiotic"),
                    ("antifungal", "Antifungal"),
                    ("antiviral", "Antiviral"),
                    ("antihistamine", "Antihistamine"),
                    ("antipyretic", "Antipyretic (Fever)"),
                    ("antihypertensive", "Antihypertensive (Blood Pressure)"),
                    ("antidiabetic", "Antidiabetic"),
                    ("vitamin", "Vitamin/Supplement"),
                    ("antiparasitic", "Antiparasitic"),
                    ("respiratory", "Respiratory"),
                    ("gastrointestinal", "Gastrointestinal"),
                    ("contraceptive", "Contraceptive"),
                    ("skin_care", "Skin Care"),
                    ("hair_care", "Hair Care"),
                    ("personal_care", "Personal Care"),
                    ("beauty_makeup", "Beauty & Makeup"),
                    ("baby_care", "Baby Care"),
                    ("oral_care", "Oral Care"),
                    ("general", "General Products"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Drug category",
                max_length=30,
            ),
        ),
    ]
