# Generated by Django 5.2.5 on 2025-12-07 08:11

from django.db import migrations, models
from django.db.migrations.operations.models import RemoveIndex


class SafeRemoveIndex(RemoveIndex):
    """
    Prevents ValueError if index is missing from migration state.
    """
    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except ValueError:
            pass


def drop_merchproduct_index_database(apps, schema_editor):
    """Drop merchproduct index using idempotent SQL. Safe to run even if index doesn't exist."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor in ('postgresql', 'sqlite'):
            cursor.execute("DROP INDEX IF EXISTS merchprod_biz_kind_type_idx")


def reverse_drop_merchproduct_index_database(apps, schema_editor):
    """Reverse: no-op (index is being removed)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0048_merge_20251207_1007"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_merchproduct_index_database,
                    reverse_drop_merchproduct_index_database,
                ),
            ],
            state_operations=[
                SafeRemoveIndex(
                    model_name="merchproduct",
                    name="merchprod_biz_kind_type_idx",
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name="pharmacysale",
            new_name="inventory_p_is_dele_fec87a_idx",
            old_name="inventory_ph_is_dele_idx",
        ),
        migrations.RenameIndex(
            model_name="pharmacysale",
            new_name="inventory_p_is_reve_dbcfac_idx",
            old_name="inventory_ph_is_reve_idx",
        ),
        migrations.RemoveField(
            model_name="merchproduct",
            name="product_type",
        ),
        migrations.AlterField(
            model_name="pharmacyproductinfo",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("analgesic", "Analgesic (Pain Relief)"),
                    ("antibiotic", "Antibiotic"),
                    ("antifungal", "Antifungal"),
                    ("antiviral", "Antiviral"),
                    ("antihistamine", "Antihistamine"),
                    ("antipyretic", "Antipyretic (Fever)"),
                    ("antihypertensive", "Antihypertensive (Blood Pressure)"),
                    ("antidiabetic", "Antidiabetic"),
                    ("vitamin", "Vitamin/Supplement"),
                    ("antiparasitic", "Antiparasitic"),
                    ("respiratory", "Respiratory"),
                    ("gastrointestinal", "Gastrointestinal"),
                    ("contraceptive", "Contraceptive"),
                    ("skin_care", "Skin Care"),
                    ("hair_care", "Hair Care"),
                    ("personal_care", "Personal Care"),
                    ("beauty_makeup", "Beauty & Makeup"),
                    ("baby_care", "Baby Care"),
                    ("oral_care", "Oral Care"),
                    ("general", "General Products"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Drug category",
                max_length=30,
            ),
        ),
    ]
