# Generated by Django 5.2.5 on 2025-12-09 22:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0049_remove_merchproduct_merchprod_biz_kind_type_idx_and_more"),
        ("tenants", "0013_add_location_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventoryitem",
            name="uniq_imei_per_business",
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="imei",
            field=models.CharField(
                blank=True,
                help_text="15-digit IMEI. GLOBALLY UNIQUE across all tenants when provided.",
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{15}$", "IMEI must be exactly 15 digits."
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["imei"], name="inv_imei_global_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("imei__isnull", False), models.Q(("imei", ""), _negated=True)
                ),
                fields=("imei",),
                name="uniq_imei_globally",
            ),
        ),
    ]
