# Generated by Django 5.2.5 on 2025-12-10 14:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0051_add_gym_trainers"),
        ("tenants", "0013_add_location_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Trainer fee amount for this period",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start date of membership period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date of membership period"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="gymtrainer",
            new_name="inventory_g_busines_8ef5c6_idx",
            old_name="inventory_g_busines_gym_trainer_idx",
        ),
        migrations.AddField(
            model_name="trainerfee",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_fees",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="trainerfee",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_fees",
                to="inventory.gymmember",
            ),
        ),
        migrations.AddField(
            model_name="trainerfee",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainer_fees_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainerfee",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="inventory.gymtrainer",
            ),
        ),
        migrations.AddIndex(
            model_name="trainerfee",
            index=models.Index(
                fields=["business", "-created_at"],
                name="inventory_t_busines_f120f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainerfee",
            index=models.Index(
                fields=["trainer", "-created_at"], name="inventory_t_trainer_e25dbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerfee",
            index=models.Index(
                fields=["member", "period_start", "period_end"],
                name="inventory_t_member__07f9f1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainerfee",
            unique_together={("member", "period_start", "period_end")},
        ),
    ]
