# Generated by Django 5.2.5 on 2025-12-13 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0052_add_trainer_fee_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this item was archived (soft-deleted). NULL means not archived.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager/admin who archived this item.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_stock_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
