# Generated by Django 5.2.5 on 2025-12-13 15:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def copy_amount_to_membership_amount(apps, schema_editor):
    """Copy existing amount values to membership_amount for backward compatibility"""
    GymPayment = apps.get_model("inventory", "GymPayment")
    # Update all existing payments to have membership_amount = amount (no trainer fee in old data)
    GymPayment.objects.all().update(membership_amount=models.F('amount'))


def reverse_copy_amount(apps, schema_editor):
    """Reverse migration: no-op since we're not removing data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0053_add_archive_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gympayment",
            name="membership_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("55000.00"),
                help_text="Base membership fee (used for days calculation)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        # Copy existing amount values to membership_amount
        migrations.RunPython(copy_amount_to_membership_amount, reverse_copy_amount),
        migrations.AddField(
            model_name="gympayment",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                help_text="Trainer assigned for this payment period",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="inventory.gymtrainer",
            ),
        ),
        migrations.AddField(
            model_name="gympayment",
            name="trainer_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Additional trainer fee (does not grant extra days)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="gymtrainer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked user account for trainer (enables wallet access)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gym_trainer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gympayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount paid (membership + trainer fee)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddIndex(
            model_name="gympayment",
            index=models.Index(
                fields=["trainer", "-paid_at"], name="inventory_g_trainer_1cc495_idx"
            ),
        ),
    ]
