# Generated by Django 5.2.5 on 2025-12-22 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_liquor_payment_mix_and_wine_glass"),
        ("tenants", "0017_add_role_to_agent_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquorsale",
            name="unit",
            field=models.CharField(
                choices=[("bottle", "Bottle"), ("shot", "Shot"), ("glass", "Glass")],
                default="bottle",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BarcodeRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_code",
                    models.CharField(
                        db_index=True,
                        help_text="Original barcode exactly as scanned",
                        max_length=100,
                    ),
                ),
                (
                    "normalized_code",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized barcode: uppercase, no spaces/hyphens, alphanumeric only",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Set to False to disable barcode without deleting",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pharmacy batch this barcode maps to (if batch-level tracking)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="inventory.pharmacybatch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business this barcode belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcode_registry",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_barcodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product this barcode maps to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="inventory.merchproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barcode Registry Entry",
                "verbose_name_plural": "Barcode Registry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "normalized_code", "is_active"],
                        name="barcode_biz_norm_active",
                    ),
                    models.Index(
                        fields=["business", "raw_code", "is_active"],
                        name="barcode_biz_raw_active",
                    ),
                    models.Index(
                        fields=["product", "is_active"], name="barcode_product_active"
                    ),
                    models.Index(
                        fields=["batch", "is_active"], name="barcode_batch_active"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("business", "normalized_code"),
                        name="unique_barcode_per_business",
                    )
                ],
            },
        ),
    ]
