# Generated by Django 5.2.5 on 2025-12-22 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0055_add_barcode_registry"),
        ("tenants", "0017_add_role_to_agent_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name (e.g., 'Oraimo Powerbank OPB-P1100D')",
                        max_length=160,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("powerbank", "Powerbank"),
                            ("charger", "Charger"),
                            ("cable", "Data Cable"),
                            ("battery", "Battery"),
                            ("headset", "Headset/Earbuds"),
                            ("speaker", "Speaker"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Accessory category",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brand name (optional, e.g., 'Oraimo', 'Tecno')",
                        max_length=80,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Internal SKU/code (auto-generated if not provided)",
                        max_length=64,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Product barcode (EAN, UPC, QR, etc.) - optional",
                        max_length=100,
                    ),
                ),
                (
                    "default_order_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default order/cost price (MWK)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "default_selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default selling price (MWK)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business that owns this accessory product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_products",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessory Product",
                "verbose_name_plural": "Accessory Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccessoryStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_on_hand",
                    models.IntegerField(
                        default=0,
                        help_text="Current quantity in stock",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average cost per unit (MWK)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business that owns this stock",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_stocks",
                        to="tenants.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Store/warehouse location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessory_stocks",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Accessory product",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_entries",
                        to="inventory.accessoryproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessory Stock",
                "verbose_name_plural": "Accessory Stocks",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessoryStockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("STOCK_IN", "Stock In"),
                            ("SALE", "Sale"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("RETURN", "Return"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity moved (positive for stock-in, negative for sale/adjustment)"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per unit (for stock-in)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_stock_logs",
                        to="tenants.business",
                    ),
                ),
                (
                    "by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessory_stock_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessory_stock_logs",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_logs",
                        to="inventory.accessoryproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessory Stock Log",
                "verbose_name_plural": "Accessory Stock Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="accessoryproduct",
            index=models.Index(
                fields=["business", "name"], name="acc_prod_biz_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessoryproduct",
            index=models.Index(
                fields=["business", "category"], name="acc_prod_biz_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessoryproduct",
            index=models.Index(
                fields=["business", "barcode"], name="acc_prod_biz_barcode_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessoryproduct",
            index=models.Index(
                fields=["business", "is_active"], name="acc_prod_biz_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessoryproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("barcode__isnull", False), models.Q(("barcode", ""), _negated=True)
                ),
                fields=("business", "barcode"),
                name="uniq_accessory_barcode_per_business",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accessoryproduct",
            unique_together={("business", "name"), ("business", "sku")},
        ),
        migrations.AddIndex(
            model_name="accessorystock",
            index=models.Index(
                fields=["business", "location"], name="acc_stock_biz_loc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessorystock",
            index=models.Index(
                fields=["business", "product"], name="acc_stock_biz_prod_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessorystock",
            index=models.Index(
                fields=["product", "qty_on_hand"], name="acc_stock_prod_qty_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accessorystock",
            unique_together={("business", "location", "product")},
        ),
        migrations.AddIndex(
            model_name="accessorystocklog",
            index=models.Index(
                fields=["business", "action", "created_at"],
                name="acc_log_biz_act_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accessorystocklog",
            index=models.Index(
                fields=["product", "created_at"], name="acc_log_prod_time_idx"
            ),
        ),
    ]
