# Generated by Django 5.2.5 on 2025-12-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0059_add_rollback_fields_to_verticals"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clothingsale",
            name="clothing_rollback_idx",
        ),
        migrations.RemoveIndex(
            model_name="liquorsale",
            name="liquor_rollback_idx",
        ),
        migrations.RemoveIndex(
            model_name="pharmacysale",
            name="pharmacy_rollback_idx",
        ),
        migrations.RemoveField(
            model_name="clothingsale",
            name="is_rolled_back",
        ),
        migrations.RemoveField(
            model_name="clothingsale",
            name="rollback_notes",
        ),
        migrations.RemoveField(
            model_name="clothingsale",
            name="rollback_reason",
        ),
        migrations.RemoveField(
            model_name="clothingsale",
            name="rolled_back_at",
        ),
        migrations.RemoveField(
            model_name="clothingsale",
            name="rolled_back_by",
        ),
        migrations.RemoveField(
            model_name="liquorsale",
            name="is_rolled_back",
        ),
        migrations.RemoveField(
            model_name="liquorsale",
            name="rollback_notes",
        ),
        migrations.RemoveField(
            model_name="liquorsale",
            name="rollback_reason",
        ),
        migrations.RemoveField(
            model_name="liquorsale",
            name="rolled_back_at",
        ),
        migrations.RemoveField(
            model_name="liquorsale",
            name="rolled_back_by",
        ),
        migrations.RemoveField(
            model_name="pharmacysale",
            name="is_rolled_back",
        ),
        migrations.RemoveField(
            model_name="pharmacysale",
            name="rollback_notes",
        ),
        migrations.RemoveField(
            model_name="pharmacysale",
            name="rollback_reason",
        ),
        migrations.RemoveField(
            model_name="pharmacysale",
            name="rolled_back_at",
        ),
        migrations.RemoveField(
            model_name="pharmacysale",
            name="rolled_back_by",
        ),
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("cement", "Cement / Hardware"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
    ]
