# Generated by Django 5.2.5 on 2025-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0060_remove_clothingsale_clothing_rollback_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchproduct",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Product barcode (EAN, UPC, QR, etc.)",
                max_length=100,
                null=True,
            ),
        ),
    ]
