# Generated by Django 5.2.5 on 2025-12-25 17:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0061_make_barcode_nullable"),
        ("tenants", "0018_add_cement_grocery_sales_and_costs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CementCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("labor", "Labor"),
                            ("rent", "Rent"),
                            ("utilities", "Utilities"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "cost_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when cost was incurred",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cement_costs",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cement_costs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cement_costs",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-cost_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-cost_date"],
                        name="inventory_c_busines_0e08f0_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "-cost_date"],
                        name="inventory_c_busines_a32e1b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CementSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per unit sold (for profit calculation)",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total cost of goods sold",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        db_index=True,
                        default="cash",
                        help_text="Payment method used for this sale",
                        max_length=20,
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cement_sales",
                        to="tenants.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cement_sales",
                        to="inventory.merchproduct",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cement_sales_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-sold_at"],
                        name="inventory_c_busines_c31315_idx",
                    ),
                    models.Index(
                        fields=["business", "payment_method", "-sold_at"],
                        name="inventory_c_busines_35a20d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GrocerySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sale_mode",
                    models.CharField(
                        choices=[("retail", "Retail"), ("wholesale", "Wholesale")],
                        db_index=True,
                        default="retail",
                        help_text="Whether this was a retail or wholesale sale",
                        max_length=20,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per unit sold (for profit calculation)",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total cost of goods sold",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        db_index=True,
                        default="cash",
                        help_text="Payment method used for this sale",
                        max_length=20,
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_sales",
                        to="tenants.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grocery_sales",
                        to="inventory.merchproduct",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grocery_sales_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-sold_at"],
                        name="inventory_g_busines_12ab66_idx",
                    ),
                    models.Index(
                        fields=["business", "payment_method", "-sold_at"],
                        name="inventory_g_busines_0374a6_idx",
                    ),
                    models.Index(
                        fields=["business", "sale_mode", "-sold_at"],
                        name="inventory_g_busines_26bc9b_idx",
                    ),
                ],
            },
        ),
    ]
