# Generated by Django 5.2.5 on 2025-12-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0062_add_cement_grocery_sales_and_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchproduct",
            name="spec_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Product specification/size label (e.g., '5L', '10L', '9kg') - for groceries and other verticals where spec is separate from quantity",
                max_length=50,
            ),
        ),
    ]
