# Generated by Django 5.2.5 on 2025-12-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0103_backfill_internal_sku"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="merchproduct",
            name="merchprod_biz_isku_idx",
        ),
        migrations.AlterField(
            model_name="merchproduct",
            name="bottles_per_crate",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of base units in a pack (default 20 for Malawi beer crates, 6 for wine/spirits cases, 24 for grocery cartons)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="merchproduct",
            name="pack_label",
            field=models.CharField(
                blank=True,
                help_text="Pack label: Crate, Case, Pack, Carton, Bale, Bundle (e.g., 'Crate' for beer, 'Carton' for groceries)",
                max_length=20,
                null=True,
            ),
        ),
    ]
