# Generated by Django 5.2.5 on 2026-01-02 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0104_remove_merchproduct_merchprod_biz_isku_idx_and_more"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique badge code (e.g. 'first_sale', 'streak_7')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name (e.g. 'First Sale')", max_length=100),
                ),
                ("description", models.TextField(help_text="How to earn this badge")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales"),
                            ("STREAK", "Streak"),
                            ("REVENUE", "Revenue"),
                            ("SPEED", "Speed"),
                            ("SPECIAL", "Special"),
                        ],
                        default="SALES",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🏆", help_text="Emoji icon", max_length=10),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=0, help_text="XP awarded when badge is earned"),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AgentStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak_days",
                    models.PositiveIntegerField(default=0, help_text="Current consecutive days with activity"),
                ),
                (
                    "longest_streak_days",
                    models.PositiveIntegerField(default=0, help_text="All-time longest streak"),
                ),
                (
                    "last_activity_date",
                    models.DateField(blank=True, help_text="Last date with activity", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_streaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_streaks",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "-current_streak_days"],
                        name="inventory_a_busines_d69bf5_idx",
                    ),
                    models.Index(
                        fields=["business", "-longest_streak_days"],
                        name="inventory_a_busines_067ebd_idx",
                    ),
                ],
                "unique_together": {("business", "agent")},
            },
        ),
        migrations.CreateModel(
            name="AgentXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_xp",
                    models.PositiveIntegerField(default=0, help_text="Total experience points earned"),
                ),
                (
                    "current_level",
                    models.PositiveIntegerField(default=1, help_text="Current level (1-based)"),
                ),
                (
                    "xp_today",
                    models.PositiveIntegerField(default=0, help_text="XP earned today"),
                ),
                (
                    "last_xp_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Last date XP was earned",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_xp",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "-total_xp"],
                        name="inventory_a_busines_193ac2_idx",
                    ),
                    models.Index(
                        fields=["business", "-current_level"],
                        name="inventory_a_busines_d47870_idx",
                    ),
                ],
                "unique_together": {("business", "agent")},
            },
        ),
        migrations.CreateModel(
            name="AgentBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_badges",
                        to="tenants.business",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="inventory.badge",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "agent", "-earned_at"],
                        name="inventory_a_busines_a488f5_idx",
                    )
                ],
                "unique_together": {("business", "agent", "badge")},
            },
        ),
        migrations.CreateModel(
            name="DailyLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rank", models.PositiveIntegerField()),
                ("sales_count", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("items_sold", models.PositiveIntegerField(default=0)),
                ("xp_earned_today", models.PositiveIntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_leaderboards",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["business", "-date", "rank"],
                        name="inventory_d_busines_fb5bb8_idx",
                    )
                ],
                "unique_together": {("business", "date", "agent")},
            },
        ),
    ]
