# Generated by Django 5.2.5 on 2026-01-02 21:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0105_gamification_models"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquorAgentTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="First day of the target month")),
                (
                    "target_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Target revenue for the month",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "target_bottles",
                    models.PositiveIntegerField(default=0, help_text="Target number of bottles to sell"),
                ),
                (
                    "actual_revenue",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("actual_bottles", models.PositiveIntegerField(default=0)),
                ("set_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_agent_targets",
                        to="tenants.business",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquor_targets_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "agent"],
                "indexes": [
                    models.Index(
                        fields=["business", "-month"],
                        name="inventory_l_busines_88766e_idx",
                    ),
                    models.Index(
                        fields=["agent", "-month"],
                        name="inventory_l_agent_i_9ce123_idx",
                    ),
                ],
                "unique_together": {("business", "agent", "month")},
            },
        ),
        migrations.CreateModel(
            name="LiquorDailyReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "total_bottles_assigned",
                    models.PositiveIntegerField(default=0, help_text="Total bottles assigned today"),
                ),
                (
                    "total_bottles_sold",
                    models.PositiveIntegerField(default=0, help_text="Total bottles sold today"),
                ),
                (
                    "total_bottles_returned",
                    models.PositiveIntegerField(default=0, help_text="Total bottles returned today"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("is_reconciled", models.BooleanField(db_index=True, default=False)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquor_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_reconciliations",
                        to="tenants.business",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquor_daily_reconciliations_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "agent"],
                "indexes": [
                    models.Index(
                        fields=["business", "-date"],
                        name="inventory_l_busines_ef62fd_idx",
                    ),
                    models.Index(fields=["agent", "-date"], name="inventory_l_agent_i_989a75_idx"),
                    models.Index(
                        fields=["business", "date", "is_reconciled"],
                        name="inventory_l_busines_005211_idx",
                    ),
                ],
                "unique_together": {("business", "agent", "date")},
            },
        ),
        migrations.CreateModel(
            name="LiquorStockAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bottles_assigned",
                    models.PositiveIntegerField(default=0, help_text="Number of bottles assigned to agent"),
                ),
                (
                    "bottles_sold",
                    models.PositiveIntegerField(default=0, help_text="Number of bottles sold by agent"),
                ),
                (
                    "bottles_returned",
                    models.PositiveIntegerField(default=0, help_text="Number of bottles returned unsold"),
                ),
                (
                    "unit_cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost price per bottle at assignment time",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_sell_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected selling price per bottle",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SOLD_OUT", "Sold Out"),
                            ("RETURNED", "Returned to Stock"),
                            ("RECONCILED", "Reconciled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reconciled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this assignment was reconciled",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this assignment",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent who is assigned this stock",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquor_stock_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who made this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquor_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_stock_assignments",
                        to="tenants.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquor_assignments",
                        to="inventory.merchproduct",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquor_assignments_reconciled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "agent", "-assigned_at"],
                        name="inventory_l_busines_8bf7a3_idx",
                    ),
                    models.Index(
                        fields=["business", "status"],
                        name="inventory_l_busines_a9d5a1_idx",
                    ),
                    models.Index(
                        fields=["agent", "status", "-assigned_at"],
                        name="inventory_l_agent_i_6f27b2_idx",
                    ),
                ],
            },
        ),
    ]
