# Generated by Django 5.2.5 on 2026-01-02 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0106_liquor_agent_assignment"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gymmember",
            name="badge_level",
            field=models.CharField(
                choices=[
                    ("none", "No Badge"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                ],
                default="none",
                help_text="Achievement badge based on check-in consistency",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gymmember",
            name="last_checkin_date",
            field=models.DateField(
                blank=True,
                help_text="Date of last check-in (for streak calculation)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gymmember",
            name="monthly_checkins",
            field=models.IntegerField(default=0, help_text="Total check-ins this month"),
        ),
        migrations.AddField(
            model_name="gymmember",
            name="streak_days",
            field=models.IntegerField(default=0, help_text="Current check-in streak (consecutive days)"),
        ),
        migrations.AddField(
            model_name="gymmember",
            name="total_checkins",
            field=models.IntegerField(default=0, help_text="Total lifetime check-ins"),
        ),
        migrations.AddIndex(
            model_name="gymmember",
            index=models.Index(fields=["badge_level"], name="inventory_g_badge_l_2f4f6a_idx"),
        ),
    ]
