# Generated by Django 5.2.5 on 2026-01-03 00:41

import uuid

from django.conf import settings
from django.db import migrations, models


def populate_member_identifiers(apps, schema_editor):
    """Populate member_number and qr_token for existing members"""
    GymMember = apps.get_model("inventory", "GymMember")

    for member in GymMember.objects.all():
        # Generate unique qr_token
        if not member.qr_token:
            member.qr_token = str(uuid.uuid4())

        # Generate unique member_number
        if not member.member_number:
            # Get business prefix
            prefix = "GYM"
            try:
                if member.business and member.business.name:
                    business_name = member.business.name.upper().replace(" ", "")
                    prefix = business_name[:3] if len(business_name) >= 3 else business_name[:2]
            except Exception:
                pass

            # Find highest existing number for this business
            import re

            existing_members = GymMember.objects.filter(
                business=member.business, member_number__startswith=f"{prefix}-"
            ).exclude(member_number="")

            max_num = 0
            for existing in existing_members:
                match = re.search(r"-(\d+)$", existing.member_number)
                if match:
                    num = int(match.group(1))
                    if num > max_num:
                        max_num = num

            next_num = max_num + 1
            member.member_number = f"{prefix}-{next_num:06d}"

        member.save(update_fields=["member_number", "qr_token"])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear the fields"""
    GymMember = apps.get_model("inventory", "GymMember")
    GymMember.objects.all().update(member_number="", qr_token="")


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0107_add_gym_gamification_fields"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add fields WITHOUT unique constraint
        migrations.AddField(
            model_name="gymmember",
            name="member_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Human-friendly member number (e.g., EW-000123)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gymmember",
            name="qr_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Stable unique QR token for scanning (UUID-based)",
                max_length=64,
                unique=False,  # Will add unique constraint later
            ),
        ),
        # Step 2: Populate unique values for existing members
        migrations.RunPython(populate_member_identifiers, reverse_populate),
        # Step 3: Now add unique constraint to qr_token
        migrations.AlterField(
            model_name="gymmember",
            name="qr_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Stable unique QR token for scanning (UUID-based)",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="gymmember",
            name="member_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Legacy barcode/QR code (deprecated, use qr_token)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="gymmember",
            index=models.Index(fields=["member_number"], name="inventory_g_member__efd743_idx"),
        ),
        migrations.AddIndex(
            model_name="gymmember",
            index=models.Index(fields=["qr_token"], name="inventory_g_qr_toke_a433f7_idx"),
        ),
    ]
