# Generated by Django 5.2.5 on 2026-01-03 00:41
# Fixed: Cross-database compatible (Postgres + SQLite) using RunPython with vendor branching

import uuid

from django.conf import settings
from django.db import migrations, models


def populate_member_identifiers(apps, schema_editor):
    """Populate member_number and qr_token for existing members"""
    GymMember = apps.get_model("inventory", "GymMember")

    for member in GymMember.objects.all():
        # Generate unique qr_token
        if not member.qr_token:
            member.qr_token = str(uuid.uuid4())

        # Generate unique member_number
        if not member.member_number:
            # Get business prefix
            prefix = "GYM"
            try:
                if member.business and member.business.name:
                    business_name = member.business.name.upper().replace(" ", "")
                    prefix = business_name[:3] if len(business_name) >= 3 else business_name[:2]
            except Exception:
                pass

            # Find highest existing number for this business
            import re

            existing_members = GymMember.objects.filter(
                business=member.business, member_number__startswith=f"{prefix}-"
            ).exclude(member_number="")

            max_num = 0
            for existing in existing_members:
                match = re.search(r"-(\d+)$", existing.member_number)
                if match:
                    num = int(match.group(1))
                    if num > max_num:
                        max_num = num

            next_num = max_num + 1
            member.member_number = f"{prefix}-{next_num:06d}"

        member.save(update_fields=["member_number", "qr_token"])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear the fields"""
    GymMember = apps.get_model("inventory", "GymMember")
    GymMember.objects.all().update(member_number="", qr_token="")


def add_qr_token_unique_constraint(apps, schema_editor):
    """
    Add unique constraint to qr_token in a cross-database, idempotent way.
    - Postgres: Use PL/pgSQL DO blocks with IF NOT EXISTS checks
    - SQLite: Use CREATE UNIQUE INDEX IF NOT EXISTS
    """
    connection = schema_editor.connection
    vendor = connection.vendor

    with connection.cursor() as cursor:
        if vendor == "postgresql":
            # Postgres: Use PL/pgSQL for idempotent constraint creation
            cursor.execute("""
                DO $$
                BEGIN
                    -- Drop non-unique index if it exists (from partial migrations)
                    DROP INDEX IF EXISTS inventory_gymmember_qr_token_d804806a;
                    DROP INDEX IF EXISTS inventory_gymmember_qr_token_d804806a_like;
                    
                    -- Create unique constraint if not exists
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'inventory_gymmember_qr_token_key'
                    ) THEN
                        ALTER TABLE inventory_gymmember 
                        ADD CONSTRAINT inventory_gymmember_qr_token_key UNIQUE (qr_token);
                    END IF;
                    
                    -- Create like index if not exists (for LIKE queries)
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'inventory_gymmember_qr_token_like'
                    ) THEN
                        CREATE INDEX inventory_gymmember_qr_token_like 
                        ON inventory_gymmember (qr_token varchar_pattern_ops);
                    END IF;
                END $$;
            """)
        elif vendor == "sqlite":
            # SQLite: Use CREATE UNIQUE INDEX IF NOT EXISTS
            # SQLite doesn't have named constraints like Postgres, so we use a unique index
            cursor.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS inventory_gymmember_qr_token_key "
                "ON inventory_gymmember (qr_token);"
            )
            # SQLite doesn't need varchar_pattern_ops - skip the _like index
        else:
            # MySQL/other: Try generic CREATE UNIQUE INDEX IF NOT EXISTS
            try:
                cursor.execute(
                    "CREATE UNIQUE INDEX IF NOT EXISTS inventory_gymmember_qr_token_key "
                    "ON inventory_gymmember (qr_token);"
                )
            except Exception:
                pass  # Best effort


def remove_qr_token_unique_constraint(apps, schema_editor):
    """Reverse: Remove unique constraint from qr_token"""
    connection = schema_editor.connection
    vendor = connection.vendor

    with connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute("""
                DO $$
                BEGIN
                    ALTER TABLE inventory_gymmember 
                    DROP CONSTRAINT IF EXISTS inventory_gymmember_qr_token_key;
                    DROP INDEX IF EXISTS inventory_gymmember_qr_token_like;
                END $$;
            """)
        else:
            # SQLite and others: DROP INDEX IF EXISTS
            cursor.execute("DROP INDEX IF EXISTS inventory_gymmember_qr_token_key;")


def add_member_number_indexes(apps, schema_editor):
    """
    Add indexes for member_number in a cross-database, idempotent way.
    """
    connection = schema_editor.connection
    vendor = connection.vendor

    with connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'inventory_gymmember_member_number_idx'
                    ) THEN
                        CREATE INDEX inventory_gymmember_member_number_idx 
                        ON inventory_gymmember (member_number);
                    END IF;
                    
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'inventory_gymmember_member_number_like'
                    ) THEN
                        CREATE INDEX inventory_gymmember_member_number_like 
                        ON inventory_gymmember (member_number varchar_pattern_ops);
                    END IF;
                END $$;
            """)
        elif vendor == "sqlite":
            # SQLite: Simple CREATE INDEX IF NOT EXISTS
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS inventory_gymmember_member_number_idx "
                "ON inventory_gymmember (member_number);"
            )
            # SQLite doesn't need varchar_pattern_ops
        else:
            # MySQL/other: Try generic approach
            try:
                cursor.execute(
                    "CREATE INDEX IF NOT EXISTS inventory_gymmember_member_number_idx "
                    "ON inventory_gymmember (member_number);"
                )
            except Exception:
                pass


def remove_member_number_indexes(apps, schema_editor):
    """Reverse: Remove member_number indexes"""
    connection = schema_editor.connection
    vendor = connection.vendor

    with connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute("DROP INDEX IF EXISTS inventory_gymmember_member_number_idx;")
            cursor.execute("DROP INDEX IF EXISTS inventory_gymmember_member_number_like;")
        else:
            cursor.execute("DROP INDEX IF EXISTS inventory_gymmember_member_number_idx;")


def add_explicit_indexes(apps, schema_editor):
    """
    Add explicit named indexes for member_number and qr_token.
    Cross-database compatible using CREATE INDEX IF NOT EXISTS.
    """
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        # These use standard SQL that works on both Postgres and SQLite
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS inventory_g_member__efd743_idx "
            "ON inventory_gymmember (member_number);"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS inventory_g_qr_toke_a433f7_idx "
            "ON inventory_gymmember (qr_token);"
        )


def remove_explicit_indexes(apps, schema_editor):
    """Reverse: Remove explicit indexes"""
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS inventory_g_member__efd743_idx;")
        cursor.execute("DROP INDEX IF EXISTS inventory_g_qr_toke_a433f7_idx;")


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0107_add_gym_gamification_fields"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add fields WITHOUT indexes (we'll add them idempotently later)
        migrations.AddField(
            model_name="gymmember",
            name="member_number",
            field=models.CharField(
                blank=True,
                db_index=False,  # Will add index via RunPython
                default="",
                help_text="Human-friendly member number (e.g., EW-000123)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gymmember",
            name="qr_token",
            field=models.CharField(
                blank=True,
                db_index=False,  # Will add index via RunPython
                default="",
                help_text="Stable unique QR token for scanning (UUID-based)",
                max_length=64,
                unique=False,
            ),
        ),
        # Step 2: Populate unique values for existing members
        migrations.RunPython(populate_member_identifiers, reverse_populate),
        # Step 3: Add unique constraint using cross-database RunPython
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Tell Django the field is now unique with db_index
                migrations.AlterField(
                    model_name="gymmember",
                    name="qr_token",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stable unique QR token for scanning (UUID-based)",
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_qr_token_unique_constraint,
                    remove_qr_token_unique_constraint,
                ),
            ],
        ),
        # Update member_code field
        migrations.AlterField(
            model_name="gymmember",
            name="member_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Legacy barcode/QR code (deprecated, use qr_token)",
                max_length=20,
            ),
        ),
        # Add explicit indexes using cross-database RunPython
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="gymmember",
                    index=models.Index(fields=["member_number"], name="inventory_g_member__efd743_idx"),
                ),
                migrations.AddIndex(
                    model_name="gymmember",
                    index=models.Index(fields=["qr_token"], name="inventory_g_qr_toke_a433f7_idx"),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_explicit_indexes,
                    remove_explicit_indexes,
                ),
            ],
        ),
        # Update member_number field state to reflect db_index=True
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="gymmember",
                    name="member_number",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Human-friendly member number (e.g., EW-000123)",
                        max_length=20,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_member_number_indexes,
                    remove_member_number_indexes,
                ),
            ],
        ),
    ]
