# Generated by Django 5.2.5 on 2026-01-03 21:39
# UPDATED: This migration now depends on 0110 which adds the qr_uuid field first

import uuid

from django.db import migrations


def backfill_qr_uuid(apps, schema_editor):
    """Backfill qr_uuid for existing GymMember records"""
    GymMember = apps.get_model("inventory", "GymMember")

    for member in GymMember.objects.filter(qr_uuid__isnull=True):
        # Try to convert existing qr_token to UUID if it's a valid UUID string
        if member.qr_token:
            try:
                member.qr_uuid = uuid.UUID(member.qr_token)
                member.save(update_fields=["qr_uuid"])
                continue
            except (ValueError, AttributeError):
                # qr_token is not a valid UUID, generate new one
                pass

        # Generate new UUID
        member.qr_uuid = uuid.uuid4()
        member.save(update_fields=["qr_uuid"])


def reverse_backfill(apps, schema_editor):
    """Reverse migration - set qr_uuid to None"""
    GymMember = apps.get_model("inventory", "GymMember")
    GymMember.objects.all().update(qr_uuid=None)


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0110_gymmember_qr_uuid_and_more"),  # Field must exist before we can backfill
    ]

    operations = [
        migrations.RunPython(backfill_qr_uuid, reverse_backfill),
    ]
