# Generated by Django 5.2.5 on 2026-01-03 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0108_add_gym_member_number_qr_token"),  # Add field BEFORE backfilling
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gymmember",
            name="qr_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Immutable UUID for QR code scanning (preferred over qr_token)",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="gymmember",
            index=models.Index(fields=["qr_uuid"], name="inventory_g_qr_uuid_353e78_idx"),
        ),
    ]
