# Generated by Django 5.2.5
# Step 3: Make qr_uuid non-nullable with default after backfilling

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0109_backfill_qr_uuid_data"),  # After backfill completes
    ]

    operations = [
        migrations.AlterField(
            model_name="gymmember",
            name="qr_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Immutable UUID for QR code scanning (preferred over qr_token)",
                unique=True,
                db_index=True,
            ),
        ),
    ]
