# Generated by Django 5.2.5 on 2026-01-10 07:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0112_backfill_gympayment_amount_comprehensive"),
        ("tenants", "0027_add_farm_welding_business_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("hardware", "Hardware & General Dealers"),
                    ("cement", "Cement / Building Materials"),
                    ("farm", "Farm Manager"),
                    ("welding", "Welding Workshop"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FarmCropSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("maize", "Maize"),
                            ("soya", "Soya Beans"),
                            ("groundnuts", "Groundnuts"),
                            ("tobacco", "Tobacco"),
                            ("cotton", "Cotton"),
                            ("rice", "Rice"),
                            ("beans", "Beans"),
                            ("cassava", "Cassava"),
                            ("sweet_potato", "Sweet Potato"),
                            ("vegetables", "Vegetables"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="maize",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Season name, e.g. 'Maize 2026 Main Season'",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "area_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Area planted",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        choices=[("acre", "Acre"), ("ha", "Hectare")],
                        default="acre",
                        max_length=10,
                    ),
                ),
                (
                    "projected_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected yield (total)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "yield_unit",
                    models.CharField(
                        blank=True,
                        choices=[("kg", "Kilogram"), ("bag", "Bag (50kg)")],
                        default="bag",
                        max_length=10,
                    ),
                ),
                (
                    "projected_price_per_unit_mwk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected selling price per yield unit",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "actual_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "actual_price_per_unit_mwk",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active (Growing)"),
                            ("harvested", "Harvested"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_crop_seasons",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_crop_seasons_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_crop_seasons",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Crop Season",
                "verbose_name_plural": "Farm Crop Seasons",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="FarmLivestockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("pigs", "Pigs"),
                            ("cattle", "Cattle"),
                            ("goats", "Goats"),
                            ("chickens", "Chickens"),
                            ("ducks", "Ducks"),
                            ("rabbits", "Rabbits"),
                            ("sheep", "Sheep"),
                            ("fish", "Fish"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="pigs",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Batch name, e.g. 'Gilts Batch 1', 'Layer Chickens Group A'",
                        max_length=100,
                    ),
                ),
                (
                    "count_current",
                    models.PositiveIntegerField(
                        default=0, help_text="Current count of animals in this batch"
                    ),
                ),
                (
                    "valuation_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable estimated valuation for this batch",
                    ),
                ),
                (
                    "avg_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average weight per animal in kg",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "price_per_kg_mwk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per kg for valuation",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "price_per_animal_mwk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed price per animal for valuation",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_livestock_batches",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_livestock_batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_livestock_batches",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Livestock Batch",
                "verbose_name_plural": "Farm Livestock Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("expense", "Expense"),
                            ("sale", "Sale"),
                            ("other_income", "Other Income"),
                        ],
                        db_index=True,
                        default="expense",
                        max_length=20,
                    ),
                ),
                (
                    "enterprise_type",
                    models.CharField(
                        choices=[
                            ("livestock", "Livestock"),
                            ("crop", "Crop"),
                            ("general", "General"),
                            ("pigs", "Pigs"),
                            ("cattle", "Cattle"),
                            ("goats", "Goats"),
                            ("chickens", "Chickens"),
                            ("maize", "Maize"),
                            ("soya", "Soya"),
                            ("groundnuts", "Groundnuts"),
                            ("tobacco", "Tobacco"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fertiliser", "Fertiliser"),
                            ("feed", "Animal Feed"),
                            ("labour", "Labour"),
                            ("vet", "Veterinary Services"),
                            ("transport", "Transport"),
                            ("rentals", "Equipment Rentals"),
                            ("seeds", "Seeds & Seedlings"),
                            ("chemicals", "Pesticides & Chemicals"),
                            ("equipment", "Equipment Purchase"),
                            ("fuel", "Fuel & Diesel"),
                            ("utilities", "Utilities (Water/Electricity)"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "amount_mwk",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in MWK (Malawian Kwacha)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kg", "Kilogram"),
                            ("bag", "Bag (50kg)"),
                            ("litre", "Litre"),
                            ("day", "Day"),
                            ("item", "Item/Piece"),
                            ("head", "Head (Animal)"),
                            ("acre", "Acre"),
                            ("ha", "Hectare"),
                        ],
                        default="item",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("credit", "Credit/On Account"),
                            ("barter", "Barter/Exchange"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="farm/ledger/attachments/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_ledger_entries",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_ledger_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="inventory.farmcropseason",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_ledger_entries",
                        to="inventory.location",
                    ),
                ),
                (
                    "livestock_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="inventory.farmlivestockbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Ledger Entry",
                "verbose_name_plural": "Farm Ledger Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmLivestockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("birth", "Birth"),
                            ("death", "Death"),
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("slaughter", "Slaughter"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        help_text="Number of animals affected",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price_mwk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per animal for purchases/sales",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="inventory.farmlivestockbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_livestock_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target batch for transfers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to",
                        to="inventory.farmlivestockbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Livestock Event",
                "verbose_name_plural": "Farm Livestock Events",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeldingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated or manual job number",
                        max_length=50,
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "product_description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "estimated_bom",
                    models.JSONField(default=list, help_text="BOM from quote/estimate"),
                ),
                (
                    "actual_bom",
                    models.JSONField(
                        default=list,
                        help_text="Actual materials used (updated after completion)",
                    ),
                ),
                (
                    "estimated_labour_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "actual_labour_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("ready", "Ready for Pickup"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "correction_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for BOM/labour corrections (for learning)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_jobs",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_jobs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_jobs",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Job",
                "verbose_name_plural": "Welding Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeldingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Square Tube 40x40 (6m)', 'Red Oxide 5L'",
                        max_length=150,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional SKU/code for quick reference",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tube", "Square/Round Tube"),
                            ("flat_bar", "Flat Bar"),
                            ("angle_iron", "Angle Iron"),
                            ("sheet", "Sheet Metal"),
                            ("paint", "Paint & Finishes"),
                            ("consumable", "Consumables (Electrodes, Discs)"),
                            ("hardware", "Hardware (Hinges, Locks, Bolts)"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("length_6m", "6m Length"),
                            ("metre", "Metre"),
                            ("litre", "Litre"),
                            ("piece", "Piece"),
                            ("kg", "Kilogram"),
                            ("packet", "Packet"),
                            ("sheet", "Sheet (2.4x1.2m)"),
                        ],
                        default="piece",
                        max_length=20,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON with specs like {thickness: 1.5, width: 40, height: 40}",
                    ),
                ),
                ("has_barcode", models.BooleanField(default=False)),
                ("barcode", models.CharField(blank=True, default="", max_length=50)),
                (
                    "price_mwk",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current price per unit in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "is_seeded",
                    models.BooleanField(
                        default=False,
                        help_text="True if this was created by system seeding",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_materials",
                        to="tenants.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_materials",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Material",
                "verbose_name_plural": "Welding Materials",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeldingMaterialStockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In (Purchase)"),
                            ("out", "Stock Out (Usage)"),
                            ("adjust", "Adjustment"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_cost_mwk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase cost per unit (for IN moves)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_stock_moves_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_usage",
                        to="inventory.weldingjob",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_moves",
                        to="inventory.weldingmaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Material Stock Move",
                "verbose_name_plural": "Welding Material Stock Moves",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeldingQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated or manual quote number",
                        max_length=50,
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "customer_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "specs",
                    models.JSONField(
                        default=dict,
                        help_text="User-provided specifications for this quote",
                    ),
                ),
                (
                    "bom",
                    models.JSONField(
                        default=list, help_text="Generated bill of materials"
                    ),
                ),
                (
                    "cost_breakdown",
                    models.JSONField(default=dict, help_text="Detailed cost breakdown"),
                ),
                (
                    "materials_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "labour_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Minimum acceptable price (break-even)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Customer"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("terms", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_quotes",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_quotes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_quotes",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Quote",
                "verbose_name_plural": "Welding Quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="weldingjob",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="inventory.weldingquote",
            ),
        ),
        migrations.CreateModel(
            name="WeldingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("customer_name", models.CharField(max_length=150)),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "customer_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("customer_address", models.TextField(blank=True, default="")),
                (
                    "line_items",
                    models.JSONField(default=list, help_text="Invoice line items"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("terms", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_invoices",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_invoices",
                        to="inventory.location",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="inventory.weldingjob",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="inventory.weldingquote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Invoice",
                "verbose_name_plural": "Welding Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeldingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Template code, e.g. 'BED_4x6', 'DOOR_STANDARD'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Bed Frame (4ft x 6ft)'",
                        max_length=150,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "params_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON schema for required params, e.g. {"width": "number", "height": "number"}',
                    ),
                ),
                (
                    "base_bom",
                    models.JSONField(
                        default=dict,
                        help_text="Base BOM formulas keyed by material code/category",
                    ),
                ),
                (
                    "default_labour_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "default_overhead_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.0"),
                        help_text="Default overhead/wastage percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "default_margin_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25.0"),
                        help_text="Default profit margin percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_templates",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Template",
                "verbose_name_plural": "Welding Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="weldingquote",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="inventory.weldingtemplate",
            ),
        ),
        migrations.AddField(
            model_name="weldingjob",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.weldingtemplate",
            ),
        ),
        migrations.CreateModel(
            name="WeldingEstimatorTuning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tube_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("2.0")),
                        ],
                    ),
                ),
                (
                    "paint_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("2.0")),
                        ],
                    ),
                ),
                (
                    "consumable_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("2.0")),
                        ],
                    ),
                ),
                (
                    "labour_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("2.0")),
                        ],
                    ),
                ),
                ("samples_count", models.PositiveIntegerField(default=0)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_tuning",
                        to="tenants.business",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuning",
                        to="inventory.weldingtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Estimator Tuning",
                "verbose_name_plural": "Welding Estimator Tunings",
            },
        ),
        migrations.AddIndex(
            model_name="farmcropseason",
            index=models.Index(
                fields=["business", "-start_date"],
                name="inventory_f_busines_a31ad2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmcropseason",
            index=models.Index(
                fields=["business", "status"], name="inventory_f_busines_d20f76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmcropseason",
            index=models.Index(
                fields=["business", "crop_type"], name="inventory_f_busines_20fb8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmlivestockbatch",
            index=models.Index(
                fields=["business", "animal_type"],
                name="inventory_f_busines_7da471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmlivestockbatch",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_f_busines_c372af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmledgerentry",
            index=models.Index(
                fields=["business", "-date"], name="inventory_f_busines_9ddcde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmledgerentry",
            index=models.Index(
                fields=["business", "entry_type", "-date"],
                name="inventory_f_busines_9585c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmledgerentry",
            index=models.Index(
                fields=["business", "enterprise_type", "-date"],
                name="inventory_f_busines_607673_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmlivestockevent",
            index=models.Index(
                fields=["batch", "-date"], name="inventory_f_batch_i_a2e351_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmlivestockevent",
            index=models.Index(
                fields=["batch", "event_type"], name="inventory_f_batch_i_cb94ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldingmaterial",
            index=models.Index(
                fields=["business", "category"], name="inventory_w_busines_a0d37c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldingmaterial",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_w_busines_37e447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldingmaterial",
            index=models.Index(
                fields=["business", "barcode"], name="inventory_w_busines_d86f63_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weldingmaterial",
            unique_together={("business", "code")},
        ),
        migrations.AddIndex(
            model_name="weldingmaterialstockmove",
            index=models.Index(
                fields=["material", "-date"], name="inventory_w_materia_513800_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldingmaterialstockmove",
            index=models.Index(
                fields=["material", "move_type"], name="inventory_w_materia_158e28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldinginvoice",
            index=models.Index(
                fields=["business", "-created_at"],
                name="inventory_w_busines_370305_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weldinginvoice",
            index=models.Index(
                fields=["business", "status"], name="inventory_w_busines_0325d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldingquote",
            index=models.Index(
                fields=["business", "-created_at"],
                name="inventory_w_busines_47cbca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weldingquote",
            index=models.Index(
                fields=["business", "status"], name="inventory_w_busines_3822d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weldingquote",
            index=models.Index(
                fields=["business", "customer_phone"],
                name="inventory_w_busines_52a0c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weldingjob",
            index=models.Index(
                fields=["business", "-created_at"],
                name="inventory_w_busines_5a26b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weldingjob",
            index=models.Index(
                fields=["business", "status"], name="inventory_w_busines_d23dfa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weldingestimatortuning",
            unique_together={("business", "template")},
        ),
    ]
