# Generated by Django 5.2.5 on 2026-01-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0113_farm_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Product barcode (EAN, UPC, QR, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clothingsale",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product sold (may be null for barcode-based sales where unit has all info)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clothing_sales",
                to="inventory.merchproduct",
            ),
        ),
    ]
