# Generated by Django 5.2.5 on 2026-01-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0114_product_barcode_alter_clothingsale_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.location",
            ),
        ),
    ]
