# Generated by Django 5.2.5 on 2026-02-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0118_add_unique_constraint_after_dedupe"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gymmember",
            new_name="inventory_g_busines_baa0dc_idx",
            old_name="inventory_g_busines_name_ca_idx",
        ),
        migrations.RenameIndex(
            model_name="gymmember",
            new_name="inventory_g_is_dele_3bfe30_idx",
            old_name="inventory_g_is_dele_idx",
        ),
        migrations.AddField(
            model_name="clothingsale",
            name="barcode_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Barcode unit sold (null for common stock sales)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="inventory.clothingbarcodeunit",
            ),
        ),
        migrations.AlterField(
            model_name="gymmemberlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("purged", "Purged"),
                    ("archived", "Archived"),
                    ("restored", "Restored"),
                ],
                max_length=10,
            ),
        ),
    ]
