# Generated by Django 5.2.5 on 2025-12-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_add_gym_trainer_fees"),
        ("inventory", "0999_alert_model"),
    ]

    operations = []
