# Generated by Django 5.2.5 on 2025-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "1000_merge_0054_add_gym_trainer_fees_0999_alert_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
    ]
