# Generated by Django 5.2.5 on 2025-12-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1002_add_sold_by_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchproduct",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Product barcode (EAN, UPC, QR, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="pharmacybatch",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Batch-specific barcode for Fast Sell lookup",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="pharmacybatch",
            name="batch_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Manufacturer batch/lot number (optional)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="pharmacybatch",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Expiry date (day/month/year, optional for cosmetics)",
                null=True,
            ),
        ),
    ]
