# Generated by Django 5.2.5 on 2025-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1003_merchproduct_barcode_pharmacybatch_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchproduct",
            name="bottles_per_crate",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Number of bottles in a crate (default 20 for Malawi beers)",
            ),
        ),
        migrations.AddField(
            model_name="merchproduct",
            name="supports_crates",
            field=models.BooleanField(
                default=False, help_text="True for beer/cider/wine; False for spirits"
            ),
        ),
    ]
