# Generated by Django 5.2.5 on 2025-12-19 13:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1002_add_sold_by_field"),
        ("tenants", "0018_add_pharmacy_cosmetics_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grains_cereals", "Grains & Cereals"),
                            ("cooking_oil", "Cooking Oil"),
                            ("sugar_salt", "Sugar & Salt"),
                            ("beverages", "Beverages"),
                            ("dairy", "Dairy Products"),
                            ("snacks", "Snacks"),
                            ("household", "Household Items"),
                            ("personal_care", "Personal Care"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Product category",
                        max_length=30,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram (kg)"),
                            ("unit", "Unit (piece)"),
                            ("bag", "Bag"),
                            ("dozen", "Dozen"),
                            ("litre", "Litre"),
                            ("gram", "Gram"),
                            ("packet", "Packet"),
                        ],
                        default="unit",
                        help_text="Unit of measurement",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current stock quantity",
                        max_digits=10,
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Alert when stock drops to or below this level",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_products",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grocery Product",
                "verbose_name_plural": "Grocery Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GrocerySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Sale"),
                            ("wholesale", "Wholesale Sale"),
                        ],
                        default="retail",
                        help_text="Retail or Wholesale",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity sold",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost price per unit (for profit calculation)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale amount (quantity * unit_price)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK", "Bank Transfer"),
                            ("CREDIT", "Credit"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_sales",
                        to="tenants.business",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grocery_sales_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="inventory.groceryproduct",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grocery_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grocery Sale",
                "verbose_name_plural": "Grocery Sales",
                "ordering": ["-sold_at"],
            },
        ),
        migrations.CreateModel(
            name="GroceryStockIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity added",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost (quantity * cost_price)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("supplier", models.CharField(blank=True, default="", max_length=200)),
                (
                    "added_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grocery_stock_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_stock_ins",
                        to="tenants.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ins",
                        to="inventory.groceryproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grocery Stock In",
                "verbose_name_plural": "Grocery Stock Ins",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="GroceryCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("UTILITIES", "Utilities (Water, Electricity)"),
                            ("TRANSPORT", "Transport"),
                            ("WAGES", "Wages"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "cost_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_costs",
                        to="tenants.business",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grocery_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grocery Cost",
                "verbose_name_plural": "Grocery Costs",
                "ordering": ["-cost_date"],
                "indexes": [
                    models.Index(
                        fields=["business", "-cost_date"],
                        name="inventory_g_busines_f63ed7_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="groceryproduct",
            index=models.Index(
                fields=["business", "name"], name="inventory_g_busines_72d3ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groceryproduct",
            index=models.Index(
                fields=["business", "category"], name="inventory_g_busines_1c5be4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groceryproduct",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_g_busines_983c70_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groceryproduct",
            unique_together={("business", "name", "unit_type")},
        ),
        migrations.AddIndex(
            model_name="grocerysale",
            index=models.Index(
                fields=["business", "-sold_at"], name="inventory_g_busines_12ab66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grocerysale",
            index=models.Index(
                fields=["product", "-sold_at"], name="inventory_g_product_701288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grocerysale",
            index=models.Index(
                fields=["sold_by", "-sold_at"], name="inventory_g_sold_by_cbc3e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grocerysale",
            index=models.Index(
                fields=["is_deleted"], name="inventory_g_is_dele_0ee977_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grocerystockin",
            index=models.Index(
                fields=["business", "-added_at"], name="inventory_g_busines_35204f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grocerystockin",
            index=models.Index(
                fields=["product", "-added_at"], name="inventory_g_product_ee8a9b_idx"
            ),
        ),
    ]
