# Generated by Django 5.2.5 on 2025-12-19 14:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1004_add_grocery_models"),
        ("tenants", "0018_add_pharmacy_cosmetics_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CementProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cement", "Cement"),
                            ("sand", "Sand"),
                            ("gravel", "Gravel / Aggregate"),
                            ("bricks", "Bricks / Blocks"),
                            ("steel", "Steel / Rebar"),
                            ("timber", "Timber / Wood"),
                            ("paint", "Paint"),
                            ("tools", "Tools"),
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("other", "Other"),
                        ],
                        default="cement",
                        help_text="Product category",
                        max_length=30,
                    ),
                ),
                (
                    "cement_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ppc", "PPC (Portland Pozzolana Cement)"),
                            ("opc", "OPC (Ordinary Portland Cement)"),
                            ("psc", "PSC (Portland Slag Cement)"),
                            ("rhc", "RHC (Rapid Hardening Cement)"),
                            ("src", "SRC (Sulphate Resisting Cement)"),
                            ("other", "Other"),
                        ],
                        default="",
                        help_text="Type of cement (if applicable)",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current stock quantity (bags/units)",
                        max_digits=10,
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Alert when stock drops to or below this level",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit/bag",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit/bag",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cement_products",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cement/Hardware Product",
                "verbose_name_plural": "Cement/Hardware Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CementSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity sold (bags/units)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per bag/unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost price per bag/unit (for profit calculation)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total sale amount (quantity * unit_price)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK", "Bank Transfer"),
                            ("CREDIT", "Credit"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cement_sales",
                        to="tenants.business",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cement_sales_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="inventory.cementproduct",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cement_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cement/Hardware Sale",
                "verbose_name_plural": "Cement/Hardware Sales",
                "ordering": ["-sold_at"],
            },
        ),
        migrations.CreateModel(
            name="CementStockIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity added (bags/units)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per bag/unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per bag/unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost (quantity * cost_price)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("supplier", models.CharField(blank=True, default="", max_length=200)),
                (
                    "added_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cement_stock_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cement_stock_ins",
                        to="tenants.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ins",
                        to="inventory.cementproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cement/Hardware Stock In",
                "verbose_name_plural": "Cement/Hardware Stock Ins",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="CementCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("UTILITIES", "Utilities"),
                            ("TRANSPORT", "Transport / Delivery"),
                            ("WAGES", "Wages"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "cost_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cement_costs",
                        to="tenants.business",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cement_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cement/Hardware Cost",
                "verbose_name_plural": "Cement/Hardware Costs",
                "ordering": ["-cost_date"],
                "indexes": [
                    models.Index(
                        fields=["business", "-cost_date"],
                        name="inventory_c_busines_0e08f0_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cementproduct",
            index=models.Index(
                fields=["business", "name"], name="inventory_c_busines_0d917a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cementproduct",
            index=models.Index(
                fields=["business", "category"], name="inventory_c_busines_211794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cementproduct",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_c_busines_eb85f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cementproduct",
            unique_together={("business", "name", "category")},
        ),
        migrations.AddIndex(
            model_name="cementsale",
            index=models.Index(
                fields=["business", "-sold_at"], name="inventory_c_busines_c31315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cementsale",
            index=models.Index(
                fields=["product", "-sold_at"], name="inventory_c_product_1811fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cementsale",
            index=models.Index(
                fields=["sold_by", "-sold_at"], name="inventory_c_sold_by_44d2d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cementsale",
            index=models.Index(
                fields=["is_deleted"], name="inventory_c_is_dele_a8f837_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cementstockin",
            index=models.Index(
                fields=["business", "-added_at"], name="inventory_c_busines_34d562_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cementstockin",
            index=models.Index(
                fields=["product", "-added_at"], name="inventory_c_product_e5a1c8_idx"
            ),
        ),
    ]
