# Generated by Django 5.2.5 on 2025-12-19 14:04

from django.db import migrations, models
import uuid
import hashlib


def generate_qr_tokens(apps, schema_editor):
    """Generate QR tokens for existing gym members"""
    GymMember = apps.get_model("inventory", "GymMember")
    
    for member in GymMember.objects.all():
        if not member.qr_token:
            # Generate unique QR token
            raw_token = f"{member.business_id}:{member.phone}:{uuid.uuid4().hex}"
            member.qr_token = hashlib.sha256(raw_token.encode()).hexdigest()[:32]
            member.save(update_fields=["qr_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1005_add_cement_models"),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name="gymmember",
            name="qr_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique QR code token for member check-in",
                max_length=64,
                unique=False,  # Temporarily not unique
            ),
        ),
        # Step 2: Generate QR tokens for existing members
        migrations.RunPython(generate_qr_tokens, reverse_code=migrations.RunPython.noop),
        # Step 3: Make field unique
        migrations.AlterField(
            model_name="gymmember",
            name="qr_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique QR code token for member check-in",
                max_length=64,
                unique=True,  # Now enforce uniqueness
            ),
        ),
    ]
