# Generated by Django 5.2.5 on 2025-12-19 15:02
# Custom migration - only adds UniqueProduct models without touching other tables

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1006_add_gym_qr_token"),
        ("tenants", "0018_add_pharmacy_cosmetics_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing"),
                            ("pharmacy", "Pharmacy"),
                            ("cosmetics", "Cosmetics"),
                            ("groceries", "Groceries"),
                        ],
                        help_text="Vertical this product belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        db_index=True,
                        help_text="Barcode or SKU code (must be unique per business)",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name with any attributes (e.g., 'White Dress XL', 'Sugar 9kg bundle')",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current stock quantity",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="unit",
                        help_text="Unit of measurement (pieces, kg, liters, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per unit (optional)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit (required)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unique_products",
                        to="tenants.business",
                        db_index=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unique_products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unique Product",
                "verbose_name_plural": "Unique Products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "barcode"], name="uniq_prod_biz_barcode_idx"
                    ),
                    models.Index(
                        fields=["business", "vertical", "is_active"],
                        name="uniq_prod_biz_vert_active_idx",
                    ),
                    models.Index(
                        fields=["business", "is_active", "name"],
                        name="uniq_prod_biz_active_name_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("business", "barcode"),
                        name="unique_barcode_per_business",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniqueProductStockIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("supplier", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unique_product_stock_ins",
                        to="tenants.business",
                        db_index=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_ins",
                        to="inventory.uniqueproduct",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unique_product_stock_ins_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unique Product Stock In",
                "verbose_name_plural": "Unique Product Stock Ins",
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-added_at"], name="inventory_u_busines_c0d602_idx"
                    ),
                    models.Index(
                        fields=["product", "-added_at"], name="inventory_u_product_2d7006_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniqueSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per unit at time of sale",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("sold_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unique_sales",
                        to="tenants.business",
                        db_index=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="inventory.uniqueproduct",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unique_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unique Sale",
                "verbose_name_plural": "Unique Sales",
                "ordering": ["-sold_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-sold_at"], name="inventory_u_busines_6d6c91_idx"
                    ),
                    models.Index(
                        fields=["product", "-sold_at"], name="inventory_u_product_60e0b6_idx"
                    ),
                    models.Index(
                        fields=["business", "is_deleted", "-sold_at"],
                        name="inventory_u_busines_040fe9_idx",
                    ),
                ],
            },
        ),
    ]

