# Generated by Django 5.2.5 on 2025-12-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "1007_change_liquorshift_users_to_set_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivebatch",
            name="counts_snapshot",
            field=models.JSONField(
                default=dict,
                help_text="JSON snapshot of affected records: products, stock_items, barcodes, etc.",
            ),
        ),
    ]
