# Generated by Django 5.2.5 on 2025-12-30 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "1009_add_liquor_simple_pack_fields"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquorStockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(help_text="Quantity change (positive for additions, negative for deductions)"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BARMAN_SHOTS", "Barman Shots (Staff Consumption)"),
                            ("SPILLAGE", "Spillage"),
                            ("BREAKAGE", "Breakage"),
                            ("EXPIRED", "Expired"),
                            ("THEFT", "Theft"),
                            ("CORRECTION", "Stock Correction"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "adjusted_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquor_adjustments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_stock_adjustments",
                        to="tenants.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquor_stock_adjustments",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_stock_adjustments",
                        to="inventory.merchproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-adjusted_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-adjusted_at"],
                        name="inventory_l_busines_e27f65_idx",
                    ),
                    models.Index(
                        fields=["business", "reason", "-adjusted_at"],
                        name="inventory_l_busines_55d79f_idx",
                    ),
                    models.Index(
                        fields=["product", "-adjusted_at"],
                        name="inventory_l_product_f3833f_idx",
                    ),
                ],
            },
        ),
    ]
