# Generated by Django 5.2.5 on 2025-12-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "1010_add_liquor_stock_adjustment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchproduct",
            name="box_size",
            field=models.PositiveIntegerField(blank=True, help_text="Number of strips per box (optional)", null=True),
        ),
        migrations.AddField(
            model_name="merchproduct",
            name="strip_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of tablets/capsules per strip (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="merchproduct",
            name="tablets_per_box",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Direct tablets per box (alternative to box_size, optional)",
                null=True,
            ),
        ),
    ]
