# Generated by Django 5.2.5 on 2026-01-05 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0111_make_qr_uuid_non_nullable"),
        ("inventory", "1012_add_cementsale_total_price_and_cost"),
    ]

    operations = []
