# Generated by Django 5.2.5 on 2026-01-05 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "1014_add_cementcost_location"),
        ("tenants", "0020_merge_20250105_1200"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CementSaleUndo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "undone_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", help_text="Reason for undoing the sale"),
                ),
                (
                    "original_quantity",
                    models.PositiveIntegerField(help_text="Original quantity sold"),
                ),
                (
                    "original_total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original sale amount",
                        max_digits=12,
                    ),
                ),
                (
                    "original_product_name",
                    models.CharField(help_text="Product name at time of undo", max_length=255),
                ),
            ],
            options={
                "ordering": ["-undone_at"],
            },
        ),
        migrations.AddField(
            model_name="cementsale",
            name="is_void",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this sale was undone/voided (do not include in reports)",
            ),
        ),
        migrations.AddIndex(
            model_name="cementsale",
            index=models.Index(
                fields=["business", "is_void", "-sold_at"],
                name="inventory_c_busines_2fbbc2_idx",
            ),
        ),
        migrations.AddField(
            model_name="cementsaleundo",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cement_sale_undos",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="cementsaleundo",
            name="sale",
            field=models.OneToOneField(
                help_text="The sale that was undone",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="undo_record",
                to="inventory.cementsale",
            ),
        ),
        migrations.AddField(
            model_name="cementsaleundo",
            name="undone_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager who undid the sale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cement_sales_undone",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cementsaleundo",
            index=models.Index(fields=["business", "-undone_at"], name="inventory_c_busines_1b20c4_idx"),
        ),
    ]
