# Generated by Django 5.2.5 on 2026-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "1015_cement_premium_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("cement", "Hardware & General Dealers"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
    ]
