# Generated by Django 5.2.5 on 2026-01-06 16:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1017_add_clothing_barcode_unit"),
        ("tenants", "0023_add_currency_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingBarcodeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        db_index=True,
                        help_text="Barcode (unique per business, required)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        help_text="Size for this unit (e.g., M, 42, 32x30)",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Category (e.g., shoes, shirt, jeans)",
                        max_length=50,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subcategory (e.g., sneaker, boot, t-shirt)",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Color (optional)",
                        max_length=50,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brand (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost price when purchased",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price (required, must be > 0)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_STOCK", "In Stock"), ("SOLD", "Sold")],
                        db_index=True,
                        default="IN_STOCK",
                        help_text="Current status of this unit",
                        max_length=10,
                    ),
                ),
                (
                    "received_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Date unit was received/stocked",
                    ),
                ),
                (
                    "sold_at",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date unit was sold (null if not sold)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False if archived/deleted",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_clothing_barcode_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business this unit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothing_barcode_units",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this unit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clothing_barcode_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where this unit is stocked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clothing_barcode_units",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent product (optional, for grouping)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barcode_units",
                        to="inventory.merchproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clothing Barcode Unit",
                "verbose_name_plural": "Clothing Barcode Units",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "status", "is_active"],
                        name="inventory_c_busines_56b515_idx",
                    ),
                    models.Index(
                        fields=["business", "barcode"],
                        name="inventory_c_busines_70f4e7_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "status"],
                        name="inventory_c_busines_f6ec43_idx",
                    ),
                    models.Index(
                        fields=["location", "status"],
                        name="inventory_c_locatio_d94ea1_idx",
                    ),
                    models.Index(
                        fields=["sold_at"], name="inventory_c_sold_at_1482d9_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "barcode"),
                        name="unique_clothing_barcode_per_business",
                    )
                ],
            },
        ),
    ]
