# Generated by Django 5.2.5 on 2026-01-15 15:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1019_add_gym_public_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price at this point in time",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost/order price at this point in time",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when this price became effective",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label for this price period (e.g. 'Week 3', 'Q2 2026')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_history_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product whose price is being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="inventory.merchproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Price History",
                "verbose_name_plural": "Product Price Histories",
                "ordering": ["-effective_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-effective_date"],
                        name="inventory_p_product_a344bc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "effective_date"),
                        name="unique_product_price_per_date",
                    )
                ],
            },
        ),
    ]
