# Generated by Django 5.2.5 on 2026-01-16 09:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1020_add_product_price_history"),
        ("tenants", "0030_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Crop name, e.g. 'Maize'", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("staples", "Staples"),
                            ("cash_crops", "Cash Crops"),
                            ("legumes", "Legumes"),
                            ("roots_tubers", "Roots & Tubers"),
                            ("vegetables", "Vegetables"),
                        ],
                        db_index=True,
                        default="staples",
                        max_length=20,
                    ),
                ),
                ("emoji", models.CharField(blank=True, default="🌾", max_length=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("bag", "Bag (50kg)"),
                            ("litre", "Litre"),
                            ("day", "Day"),
                            ("item", "Item/Piece"),
                            ("head", "Head (Animal)"),
                            ("acre", "Acre"),
                            ("ha", "Hectare"),
                        ],
                        default="bag",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Current available quantity (updated by harvests/sales)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_crops",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Crop",
                "verbose_name_plural": "Farm Crops",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FarmCropSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price_mwk",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_crop_sales",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_crop_sales_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="inventory.farmcrop",
                    ),
                ),
                (
                    "ledger_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_sale",
                        to="inventory.farmledgerentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Crop Sale",
                "verbose_name_plural": "Farm Crop Sales",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        help_text="Asset type code, e.g. 'tractor'", max_length=50
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=150)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "value_mwk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_assets",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_assets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Asset",
                "verbose_name_plural": "Farm Assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "is_active"],
                        name="inventory_f_busines_ee0060_idx",
                    ),
                    models.Index(
                        fields=["business", "asset_type"],
                        name="inventory_f_busines_e4af16_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="farmcrop",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_f_busines_e6087c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmcrop",
            index=models.Index(
                fields=["business", "category"], name="inventory_f_busines_d54678_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmcrop",
            unique_together={("business", "name")},
        ),
        migrations.AddIndex(
            model_name="farmcropsale",
            index=models.Index(
                fields=["business", "-date"], name="inventory_f_busines_89f0b7_idx"
            ),
        ),
    ]
