# Generated by Django 5.2.5 on 2026-01-06 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "1021_add_price_change_log_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceChangeLog",
        ),
    ]
