# Generated by Django 5.2.5 on 2026-01-17 07:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1021_farm_premium_crops_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weldingmaterial",
            name="category",
            field=models.CharField(
                choices=[
                    ("tube", "Tubes (Square/Round)"),
                    ("flat_bar", "Flat Bar"),
                    ("angle_iron", "Angle Iron"),
                    ("sheet", "Sheet Metal"),
                    ("board", "Boards & Panels"),
                    ("aluminum", "Aluminum Profiles"),
                    ("electrode", "Electrodes"),
                    ("disc", "Discs (Cutting/Grinding)"),
                    ("sanding", "Sanding Discs"),
                    ("paint", "Paint & Finishes"),
                    ("hardware", "Hardware"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weldingmaterial",
            name="unit",
            field=models.CharField(
                choices=[
                    ("length_6m", "6m Length"),
                    ("length_5_8m", "5.8m Length"),
                    ("metre", "Metre"),
                    ("litre", "Litre"),
                    ("piece", "Piece"),
                    ("kg", "Kilogram"),
                    ("packet", "Packet"),
                    ("sheet", "Sheet (2.4x1.2m)"),
                    ("board", "Board (8ft x 4ft)"),
                ],
                default="piece",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WeldingQuoteCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("labour", "Labour"),
                            ("transport", "Transport"),
                            ("other", "Other"),
                            ("profit", "Profit/Markup"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="inventory.weldingquote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Quote Cost",
                "verbose_name_plural": "Welding Quote Costs",
                "ordering": ["cost_type", "position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["quote", "cost_type"],
                        name="inventory_w_quote_i_195077_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeldingQuoteLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=150)),
                ("material_unit", models.CharField(default="piece", max_length=20)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unit price in MWK - left blank until manager enters",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to material (optional, snapshots name/unit)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.weldingmaterial",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="inventory.weldingquote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Quote Line Item",
                "verbose_name_plural": "Welding Quote Line Items",
                "ordering": ["position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["quote", "position"],
                        name="inventory_w_quote_i_678429_idx",
                    )
                ],
            },
        ),
    ]
