# Generated by Django 5.2.5 on 2026-01-17 10:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1022_welding_manual_quote_builder"),
        ("tenants", "0030_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeldingCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost amount in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("labor", "Labor"),
                            ("rent", "Rent"),
                            ("utilities", "Utilities"),
                            ("equipment", "Equipment/Maintenance"),
                            ("consumables", "Consumables"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "incurred_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when cost was incurred",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_costs",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_costs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_costs",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Cost",
                "verbose_name_plural": "Welding Costs",
                "ordering": ["-incurred_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-incurred_on"],
                        name="inventory_w_busines_277f95_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "-incurred_on"],
                        name="inventory_w_busines_fa529e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeldingRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Revenue amount in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("repair", "Repair Work"),
                            ("custom_job", "Custom Job"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "received_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when revenue was received",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_revenues",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_revenues_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_revenues",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Revenue",
                "verbose_name_plural": "Welding Revenues",
                "ordering": ["-received_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-received_on"],
                        name="inventory_w_busines_b2b4b0_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "-received_on"],
                        name="inventory_w_busines_d762f0_idx",
                    ),
                ],
            },
        ),
    ]
