# Generated by Django 5.2.5 on 2026-01-18 16:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1023_welding_revenue_costs"),
        ("tenants", "0030_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCorrectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Model name (e.g., 'InventoryItem', 'AccessoryStock', 'LiquorSale')",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        db_index=True, help_text="ID of the corrected object"
                    ),
                ),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("EDIT_SALE", "Edit Sale"),
                            ("EDIT_STOCK_IN", "Edit Stock-In"),
                            ("EDIT_ACCESSORY", "Edit Accessory"),
                            ("VOID_SALE", "Void Sale"),
                            ("VOID_STOCK_IN", "Void Stock-In"),
                            ("VOID_ACCESSORY", "Void Accessory"),
                            ("RESTORE", "Restore Voided Record"),
                        ],
                        db_index=True,
                        help_text="Type of correction made",
                        max_length=32,
                    ),
                ),
                (
                    "corrected_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the correction was made",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Required: Reason for making this correction"
                    ),
                ),
                (
                    "field_changes",
                    models.JSONField(
                        default=dict,
                        help_text="JSON dict of field changes: {field: {old: val, new: val}}",
                    ),
                ),
                (
                    "revenue_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Change in revenue caused by this correction",
                        max_digits=12,
                    ),
                ),
                (
                    "profit_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Change in profit caused by this correction",
                        max_digits=12,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User agent string",
                        max_length=255,
                    ),
                ),
                (
                    "is_restoration",
                    models.BooleanField(
                        default=False,
                        help_text="True if this log entry is a restoration of a voided record",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business where correction was made",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_correction_logs",
                        to="tenants.business",
                    ),
                ),
                (
                    "corrected_by",
                    models.ForeignKey(
                        help_text="Manager who made the correction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Correction Log",
                "verbose_name_plural": "Data Correction Logs",
                "ordering": ["-corrected_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-corrected_at"],
                        name="inventory_d_busines_b89c6f_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="inventory_d_model_n_563103_idx",
                    ),
                    models.Index(
                        fields=["corrected_by", "-corrected_at"],
                        name="inventory_d_correct_4f3401_idx",
                    ),
                    models.Index(
                        fields=["correction_type", "-corrected_at"],
                        name="inventory_d_correct_34144a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoidedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Model name of the voided record",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        db_index=True, help_text="ID of the voided object"
                    ),
                ),
                (
                    "record_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="JSON snapshot of the record before voiding",
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("reason", models.TextField(help_text="Required: Reason for voiding")),
                (
                    "revenue_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Revenue removed from totals by this void",
                        max_digits=12,
                    ),
                ),
                (
                    "profit_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Profit removed from totals by this void",
                        max_digits=12,
                    ),
                ),
                (
                    "is_restored",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record was later restored",
                    ),
                ),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voided_records",
                        to="tenants.business",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        help_text="Manager who voided the record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voided_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voided Record",
                "verbose_name_plural": "Voided Records",
                "ordering": ["-voided_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-voided_at"],
                        name="inventory_v_busines_b5ea52_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="inventory_v_model_n_d10255_idx",
                    ),
                    models.Index(
                        fields=["is_restored", "-voided_at"],
                        name="inventory_v_is_rest_5172d3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_restored", False)),
                        fields=("model_name", "object_id"),
                        name="unique_active_void_per_object",
                    )
                ],
            },
        ),
    ]
