# Generated by Django 5.2.5 on 2026-01-20 09:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1024_data_correction_models"),
        ("tenants", "0031_car_hire_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("hardware", "Hardware & General Dealers"),
                    ("cement", "Cement / Building Materials"),
                    ("farm", "Farm Manager"),
                    ("welding", "Welding Workshop"),
                    ("car_hire", "Car Hire Service"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Toyota Fortuner 2019'",
                        max_length=150,
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        choices=[
                            ("toyota", "Toyota"),
                            ("ford", "Ford"),
                            ("mazda", "Mazda"),
                            ("honda", "Honda"),
                            ("nissan", "Nissan"),
                            ("isuzu", "Isuzu"),
                            ("mitsubishi", "Mitsubishi"),
                            ("hyundai", "Hyundai"),
                            ("suzuki", "Suzuki"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="toyota",
                        max_length=30,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model name, e.g. 'Fortuner', 'Ranger', 'Hiace', 'Bongo'",
                        max_length=100,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year of manufacture", null=True
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        db_index=True,
                        help_text="Vehicle registration/plate number",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_trip", "On Trip"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily rental rate in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "current_odometer",
                    models.PositiveIntegerField(
                        default=0, help_text="Current odometer reading in km"
                    ),
                ),
                (
                    "next_maintenance_km",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Odometer reading for next scheduled maintenance",
                        null=True,
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=50)),
                (
                    "seats",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of seats", null=True
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="car_hire/vehicles/"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_hire_vehicles",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_hire_vehicles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(help_text="Customer's name", max_length=150),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer's phone number",
                        max_length=20,
                    ),
                ),
                (
                    "customer_id_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer's ID/passport number",
                        max_length=30,
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        db_index=True, help_text="Trip start date and time"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Trip end date and time", null=True
                    ),
                ),
                (
                    "destination",
                    models.CharField(help_text="Destination or route", max_length=255),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("passenger", "Passenger"),
                            ("cargo", "Cargo"),
                            ("empty", "Empty/Repositioning"),
                        ],
                        db_index=True,
                        default="passenger",
                        max_length=20,
                    ),
                ),
                (
                    "price_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for the trip in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "deposit_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Deposit amount paid",
                        max_digits=12,
                    ),
                ),
                (
                    "start_odometer",
                    models.PositiveIntegerField(
                        blank=True, help_text="Odometer at trip start", null=True
                    ),
                ),
                (
                    "end_odometer",
                    models.PositiveIntegerField(
                        blank=True, help_text="Odometer at trip end", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_hire_trips",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_hire_trips_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="inventory.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("service", "Scheduled Service"),
                            ("repair", "Repair"),
                            ("tyres", "Tyre Replacement"),
                            ("brakes", "Brake Service"),
                            ("oil_change", "Oil Change"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="service",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("description", models.TextField(help_text="Description of work done")),
                (
                    "odometer",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Odometer reading at maintenance",
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total maintenance cost in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Garage or service provider",
                        max_length=150,
                    ),
                ),
                (
                    "next_maintenance_km",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Odometer for next maintenance (auto-updates vehicle)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_hire_maintenance_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="inventory.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["business", "status"], name="inventory_v_busines_7404f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_v_busines_5796d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["business", "make"], name="inventory_v_busines_52191c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("business", "plate_number")},
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["business", "-start_datetime"],
                name="inventory_t_busines_dd21c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["business", "status"], name="inventory_t_busines_16ce40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["vehicle", "-start_datetime"],
                name="inventory_t_vehicle_2cccd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["vehicle", "-date"], name="inventory_m_vehicle_8109d3_idx"
            ),
        ),
    ]
