# Generated by Django 5.2.5 on 2026-01-20 12:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1026_add_trip_driver"),
        ("tenants", "0031_car_hire_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarHireCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost amount in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel"),
                            ("maintenance", "Maintenance/Repairs"),
                            ("driver", "Driver Wages"),
                            ("insurance", "Insurance"),
                            ("cleaning", "Cleaning/Wash"),
                            ("taxes", "Taxes/Licenses"),
                            ("parking", "Parking/Tolls"),
                            ("rent", "Office/Parking Rent"),
                            ("utilities", "Utilities"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "incurred_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when cost was incurred",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_hire_costs",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_hire_costs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs",
                        to="inventory.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Hire Cost",
                "verbose_name_plural": "Car Hire Costs",
                "ordering": ["-incurred_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-incurred_on"],
                        name="inventory_c_busines_fca8cb_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "-incurred_on"],
                        name="inventory_c_busines_1e0a96_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CarHireRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Revenue amount in MWK",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("trip", "Trip/Booking"),
                            ("extra_charges", "Extra Charges"),
                            ("insurance", "Insurance Claim"),
                            ("late_fee", "Late Return Fee"),
                            ("damage", "Damage Recovery"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "received_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when revenue was received",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_hire_revenues",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_hire_revenues_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additional_revenues",
                        to="inventory.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenues",
                        to="inventory.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Hire Revenue",
                "verbose_name_plural": "Car Hire Revenues",
                "ordering": ["-received_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-received_on"],
                        name="inventory_c_busines_71bfc4_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "-received_on"],
                        name="inventory_c_busines_3c6ec9_idx",
                    ),
                ],
            },
        ),
    ]
