# Generated by Django 5.2.5 on 2026-01-20 17:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1027_add_car_hire_revenue_cost_models"),
        ("tenants", "0031_car_hire_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily rental rate (for reference/calculation)",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="dropoff_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dropoff location/address (if different from pickup)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="fuel_level_in",
            field=models.CharField(
                blank=True, default="", help_text="Fuel level at return", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="fuel_level_out",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fuel level at pickup (e.g., 'Full', '3/4', '1/2')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="fuel_policy",
            field=models.CharField(
                choices=[
                    ("full_to_full", "Full to Full"),
                    ("same_level", "Same Level Return"),
                    ("prepaid", "Prepaid Fuel"),
                    ("no_fuel", "No Fuel (Driver provides)"),
                ],
                default="full_to_full",
                help_text="Fuel policy for this booking",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="num_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of rental days (for multi-day bookings)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pickup location/address",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="datacorrectionlog",
            name="correction_type",
            field=models.CharField(
                choices=[
                    ("EDIT_SALE", "Edit Sale"),
                    ("EDIT_STOCK_IN", "Edit Stock-In"),
                    ("EDIT_ACCESSORY", "Edit Accessory"),
                    ("VOID_SALE", "Void Sale"),
                    ("VOID_STOCK_IN", "Void Stock-In"),
                    ("VOID_ACCESSORY", "Void Accessory"),
                    ("RESTORE", "Restore Voided Record"),
                    ("EDIT_LIQUOR_SALE", "Edit Liquor Sale"),
                    ("VOID_LIQUOR_SALE", "Void Liquor Sale"),
                    ("EDIT_LIQUOR_STOCK", "Edit Liquor Stock"),
                    ("VOID_LIQUOR_STOCK", "Void Liquor Stock"),
                    ("EDIT_WELDING_QUOTE", "Edit Welding Quote"),
                    ("VOID_WELDING_QUOTE", "Void Welding Quote"),
                    ("EDIT_WELDING_JOB", "Edit Welding Job"),
                    ("VOID_WELDING_JOB", "Void Welding Job"),
                    ("EDIT_WELDING_INVOICE", "Edit Welding Invoice"),
                    ("EDIT_FARM_ENTRY", "Edit Farm Entry"),
                    ("VOID_FARM_ENTRY", "Void Farm Entry"),
                    ("EDIT_POULTRY_RECORD", "Edit Poultry Record"),
                    ("EDIT_PIG_RECORD", "Edit Pig Record"),
                    ("EDIT_CAR_HIRE_TRIP", "Edit Trip/Booking"),
                    ("VOID_CAR_HIRE_TRIP", "Void Trip/Booking"),
                    ("EDIT_VEHICLE", "Edit Vehicle"),
                    ("EDIT_EXPENSE", "Edit Expense"),
                    ("VOID_EXPENSE", "Void Expense"),
                    ("EDIT_COST", "Edit Cost"),
                    ("VOID_COST", "Void Cost"),
                ],
                db_index=True,
                help_text="Type of correction made",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PigPen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pen name, e.g. 'Pen A', 'Farrowing 1', 'Grower House 2'",
                        max_length=100,
                    ),
                ),
                (
                    "pen_type",
                    models.CharField(
                        choices=[
                            ("farrowing", "Farrowing (Sows with piglets)"),
                            ("grower", "Grower"),
                            ("finisher", "Finisher"),
                            ("boar", "Boar"),
                            ("gilt", "Gilt (Young females)"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum pigs this pen can hold",
                        null=True,
                    ),
                ),
                (
                    "current_pigs",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of pigs in pen"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pig_pens",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pig_pens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pig_pens",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pig Pen",
                "verbose_name_plural": "Pig Pens",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PigDailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "pigs_count",
                    models.PositiveIntegerField(
                        help_text="Number of pigs in pen at end of day"
                    ),
                ),
                (
                    "feed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total feed given to pen today in kg",
                        max_digits=10,
                    ),
                ),
                (
                    "average_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average weight per pig in kg (if weighed)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Treatment/medication given today",
                        max_length=255,
                    ),
                ),
                (
                    "births",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of piglets born today"
                    ),
                ),
                (
                    "deaths",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of deaths today"
                    ),
                ),
                (
                    "transfers_in",
                    models.PositiveIntegerField(
                        default=0, help_text="Pigs transferred into this pen"
                    ),
                ),
                (
                    "transfers_out",
                    models.PositiveIntegerField(
                        default=0, help_text="Pigs transferred out of this pen"
                    ),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(
                        default=0, help_text="Pigs sold from this pen today"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pig_daily_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="inventory.pigpen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pig Daily Record",
                "verbose_name_plural": "Pig Daily Records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PoultryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Batch name, e.g. 'Broilers Batch 1 - Jan 2026'",
                        max_length=100,
                    ),
                ),
                (
                    "poultry_type",
                    models.CharField(
                        choices=[
                            ("broilers", "Broilers"),
                            ("layers", "Layers"),
                            ("indigenous", "Indigenous/Village Chickens"),
                            ("ducks", "Ducks"),
                            ("turkeys", "Turkeys"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="broilers",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date batch was started/received",
                    ),
                ),
                (
                    "initial_birds",
                    models.PositiveIntegerField(
                        default=0, help_text="Initial number of birds in batch"
                    ),
                ),
                (
                    "current_birds",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of birds alive"
                    ),
                ),
                (
                    "total_deaths",
                    models.PositiveIntegerField(
                        default=0, help_text="Total deaths to date"
                    ),
                ),
                (
                    "total_feed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total feed consumed in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "total_eggs",
                    models.PositiveIntegerField(
                        default=0, help_text="Total eggs collected (for layers)"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total costs incurred (feed, meds, chicks, etc.)",
                        max_digits=14,
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total sales revenue",
                        max_digits=14,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poultry_batches",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poultry_batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poultry_batches",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poultry Batch",
                "verbose_name_plural": "Poultry Batches",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmCashbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feed", "Feed"),
                            ("medication", "Medication/Vaccines"),
                            ("chicks", "Day-old Chicks/Piglets"),
                            ("labour", "Labour/Wages"),
                            ("utilities", "Utilities (Water/Electricity)"),
                            ("transport", "Transport"),
                            ("equipment", "Equipment/Tools"),
                            ("sales_birds", "Sales - Birds"),
                            ("sales_eggs", "Sales - Eggs"),
                            ("sales_pigs", "Sales - Pigs"),
                            ("sales_crops", "Sales - Crops"),
                            ("other_income", "Other Income"),
                            ("other_expense", "Other Expense"),
                        ],
                        db_index=True,
                        default="other_expense",
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in MWK (positive for income, negative for expense)",
                        max_digits=14,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_cashbook_entries",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_cashbook_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pig_pen",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to pig pen if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_entries",
                        to="inventory.pigpen",
                    ),
                ),
                (
                    "poultry_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to poultry batch if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_entries",
                        to="inventory.poultrybatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Cashbook Entry",
                "verbose_name_plural": "Farm Cashbook Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PoultryDailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "birds_alive",
                    models.PositiveIntegerField(
                        help_text="Number of birds alive at end of day"
                    ),
                ),
                (
                    "deaths",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of deaths today"
                    ),
                ),
                (
                    "feed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Feed given today in kg",
                        max_digits=10,
                    ),
                ),
                (
                    "eggs_collected",
                    models.PositiveIntegerField(
                        default=0, help_text="Eggs collected today (for layers)"
                    ),
                ),
                (
                    "medication",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Medication/vaccination given today",
                        max_length=255,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="inventory.poultrybatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poultry_daily_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Poultry Daily Record",
                "verbose_name_plural": "Poultry Daily Records",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="pigpen",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_p_busines_f4dcac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pigpen",
            index=models.Index(
                fields=["business", "pen_type"], name="inventory_p_busines_0c8d9c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pigpen",
            unique_together={("business", "name")},
        ),
        migrations.AddIndex(
            model_name="pigdailyrecord",
            index=models.Index(
                fields=["pen", "-date"], name="inventory_p_pen_id_566769_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pigdailyrecord",
            unique_together={("pen", "date")},
        ),
        migrations.AddIndex(
            model_name="poultrybatch",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_p_busines_631948_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poultrybatch",
            index=models.Index(
                fields=["business", "poultry_type"],
                name="inventory_p_busines_69765e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="farmcashbook",
            index=models.Index(
                fields=["business", "-date"], name="inventory_f_busines_0b8b66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmcashbook",
            index=models.Index(
                fields=["business", "category"], name="inventory_f_busines_320409_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poultrydailyrecord",
            index=models.Index(
                fields=["batch", "-date"], name="inventory_p_batch_i_072686_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="poultrydailyrecord",
            unique_together={("batch", "date")},
        ),
    ]
