# Generated by Django 5.2.5 on 2026-02-05 20:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1028_add_poultry_pig_cashbook_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymsettings",
            name="default_trainer_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50000.00"),
                help_text="Default trainer fee per month",
                max_digits=10,
            ),
        ),
    ]
