# Generated by Django 5.2.5 on 2026-02-05 20:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1029_alter_gymsettings_default_trainer_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymsettings",
            name="default_membership_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("50000.00"),
                help_text="Default monthly membership fee (30 days)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gymsettings",
            name="default_trainer_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("50000.00"),
                help_text="Default trainer fee per month",
                max_digits=10,
                null=True,
            ),
        ),
    ]
