# Generated by Django 5.2.5 on 2026-02-06 08:33

from django.db import migrations, models


def convert_empty_strings_to_null(apps, schema_editor):
    """
    Convert existing empty string phone numbers to NULL.
    This allows multiple members without phone numbers.
    """
    GymMember = apps.get_model("inventory", "GymMember")
    # Update all members with empty string phone to NULL
    updated_count = GymMember.objects.filter(phone="").update(phone=None)
    print(f"  -> Converted {updated_count} empty phone strings to NULL")


def reverse_null_to_empty_strings(apps, schema_editor):
    """Reverse migration: convert NULL back to empty strings."""
    GymMember = apps.get_model("inventory", "GymMember")
    GymMember.objects.filter(phone__isnull=True).update(phone="")


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1030_gym_settings_nullable_defaults"),
    ]

    operations = [
        # First, convert empty strings to NULL before altering the field
        migrations.RunPython(
            convert_empty_strings_to_null,
            reverse_null_to_empty_strings,
        ),
        # Then, alter the field to allow NULL
        migrations.AlterField(
            model_name="gymmember",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
