# Generated by Django 5.2.5 on 2026-02-06 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1031_gym_member_phone_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gympayment",
            name="delete_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional notes about why this payment was deleted",
            ),
        ),
        migrations.AddField(
            model_name="gympayment",
            name="delete_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason for deletion (e.g., 'duplicate', 'wrong_member', 'wrong_amount')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="gympayment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this payment was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gympayment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gym_payments_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gympayment",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Soft delete flag - set by corrections when payment is removed as duplicate",
            ),
        ),
    ]
