# Generated by Django 5.2.5 on 2026-02-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0117_gym_member_auto_dedupe'),
        ('inventory', '1032_add_gym_payment_soft_delete'),
    ]

    operations = [
    ]
