# Generated by Django 5.2.5 on 2026-02-12 18:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1034_add_marketplace_models"),
        ("tenants", "0031_car_hire_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquorStockInTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_added",
                    models.IntegerField(help_text="Quantity added (in bottles)"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per bottle",
                        max_digits=12,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total cost of this stock-in",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="marketplaceenquiry",
            new_name="inventory_m_busines_595aab_idx",
            old_name="inventory_m_busines_7a2d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplaceenquiry",
            new_name="inventory_m_listing_295cdd_idx",
            old_name="inventory_m_listing_5c8b9f_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplaceenquiry",
            new_name="inventory_m_created_89aaf6_idx",
            old_name="inventory_m_created_1e6a7c_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacelisting",
            new_name="inventory_m_busines_b3b99a_idx",
            old_name="inventory_m_busines_e6b7e3_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacelisting",
            new_name="inventory_m_vertica_7bba40_idx",
            old_name="inventory_m_vertica_8f4c2a_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacelisting",
            new_name="inventory_m_created_e9d9e2_idx",
            old_name="inventory_m_created_9d3f1b_idx",
        ),
        migrations.AddField(
            model_name="liquorstockintransaction",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liquor_stock_in_transactions",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="liquorstockintransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liquor_stock_in_transactions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="liquorstockintransaction",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liquor_stock_in_transactions",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="liquorstockintransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liquor_stock_in_transactions",
                to="inventory.merchproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorstockintransaction",
            index=models.Index(
                fields=["business", "-created_at"],
                name="inventory_l_busines_ec6126_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorstockintransaction",
            index=models.Index(
                fields=["business", "product", "-created_at"],
                name="inventory_l_busines_41f390_idx",
            ),
        ),
    ]
