# Generated by Django 5.2.5 on 2026-02-12 18:33

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1035_liquorstockintransaction_and_more"),
        ("tenants", "0031_car_hire_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="liquorstockintransaction",
            name="date_received",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.localdate,
                help_text="Business date when stock was received (for 30-day COGS window)",
            ),
        ),
        migrations.AddIndex(
            model_name="liquorstockintransaction",
            index=models.Index(
                fields=["business", "-date_received"],
                name="inventory_l_busines_823565_idx",
            ),
        ),
    ]
