# Generated by Django 5.2.5 on 2026-03-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1038_electronics_payment_battery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phoneproductcatalog",
            options={
                "ordering": ["category", "brand", "model_name", "ram_gb", "rom_gb"]
            },
        ),
        migrations.AlterField(
            model_name="electronicsstockitem",
            name="catalog_product",
            field=models.ForeignKey(
                help_text="Catalog model (Laptop or Desktop)",
                limit_choices_to={"category__in": ["LAPTOP", "DESKTOP"]},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_items",
                to="inventory.phoneproductcatalog",
            ),
        ),
    ]
