# Generated by Django 5.2.5 on 2026-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1039_alter_phoneproductcatalog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquorstockintransaction",
            name="selling_price_at_time",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Selling price per bottle set during this stock-in event",
                max_digits=12,
                null=True,
            ),
        ),
    ]
