# Generated by Django 5.2.5 on 2026-03-06 15:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models_marketplace
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1040_liquor_stockin_selling_price_at_time"),
        ("tenants", "0032_marketplace_upgrade_and_car_dealer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=inventory.models_marketplace.marketplace_media_upload_path,
                        validators=[
                            inventory.models_marketplace.validate_marketplace_media_size
                        ],
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "uploaded_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="marketplacelisting",
            name="inventory_m_busines_b3b99a_idx",
        ),
        migrations.RemoveIndex(
            model_name="marketplacelisting",
            name="inventory_m_vertica_7bba40_idx",
        ),
        migrations.RemoveField(
            model_name="marketplacelisting",
            name="is_active",
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked inventory item (optional; for stock-based businesses)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketplace_listings",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="listing_slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Unique URL slug for this listing within the business",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="location_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable location (e.g. Area 25, Lilongwe)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("live", "Live"),
                    ("offline", "Offline"),
                    ("sold", "Sold"),
                    ("out_of_stock", "Out of Stock"),
                ],
                db_index=True,
                default="draft",
                help_text="Listing status (draft/live/offline/sold/out_of_stock)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="marketplacelisting",
            name="vertical_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Vertical-specific extra fields (e.g. specs, condition, size)",
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceenquiry",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceenquiry",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="marketplaceenquiry",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enquiries",
                to="inventory.marketplacelisting",
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceenquiry",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="marketplaceenquiry",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="marketplaceenquiry",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="marketplaceenquiry",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_listings",
                to="tenants.business",
            ),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketplace_listings_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="Primary product photo or video (max 10 MB)",
                null=True,
                upload_to=inventory.models_marketplace.marketplace_media_upload_path,
                validators=[
                    inventory.models_marketplace.validate_marketplace_media_size,
                    inventory.models_marketplace.validate_marketplace_media_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("hardware", "Hardware & General Dealers"),
                    ("cement", "Cement / Building Materials"),
                    ("farm", "Farm Manager"),
                    ("welding", "Welding Workshop"),
                    ("car_hire", "Car Hire Service"),
                    ("car_dealer", "Car Dealer"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["business", "status"], name="inventory_m_busines_7c9c74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["vertical", "status"], name="inventory_m_vertica_9183b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["business", "listing_slug"],
                name="inventory_m_busines_b0bd78_idx",
            ),
        ),
        migrations.AddField(
            model_name="marketplacelistingimage",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="inventory.marketplacelisting",
            ),
        ),
    ]
