# Generated by Django 5.2.5 on 2026-03-06 15:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1042_backfill_marketplace_listing_status"),
        ("tenants", "0032_marketplace_upgrade_and_car_dealer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="car_dealer/makes/"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Show prominently in dropdowns (for common makes)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Make",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(blank=True, max_length=80)),
                (
                    "body_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedan", "Sedan"),
                            ("hatchback", "Hatchback"),
                            ("suv", "SUV / Crossover"),
                            ("pickup", "Pickup / Truck"),
                            ("minivan", "Minivan / MPV"),
                            ("wagon", "Station Wagon"),
                            ("coupe", "Coupe"),
                            ("convertible", "Convertible"),
                            ("bus", "Bus / Minibus"),
                            ("van", "Van"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "common_years",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. '2010-2020' or '2015+'",
                        max_length=40,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="inventory.carmake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Model",
                "ordering": ["sort_order", "name"],
                "unique_together": {("make", "name")},
            },
        ),
        migrations.CreateModel(
            name="CarDealerVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make_text", models.CharField(blank=True, default="", max_length=80)),
                ("model_text", models.CharField(blank=True, default="", max_length=80)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Model year (e.g. 2019)", null=True
                    ),
                ),
                (
                    "trim",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Trim/grade (e.g. GL, SE, GLS, Touring)",
                        max_length=80,
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedan", "Sedan"),
                            ("hatchback", "Hatchback"),
                            ("suv", "SUV / Crossover"),
                            ("pickup", "Pickup / Truck"),
                            ("minivan", "Minivan / MPV"),
                            ("wagon", "Station Wagon"),
                            ("coupe", "Coupe"),
                            ("convertible", "Convertible"),
                            ("bus", "Bus / Minibus"),
                            ("van", "Van"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto", "Automatic"),
                            ("manual", "Manual"),
                            ("cvt", "CVT"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "drivetrain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fwd", "Front-Wheel Drive"),
                            ("rwd", "Rear-Wheel Drive"),
                            ("awd", "All-Wheel Drive"),
                            ("4wd", "4-Wheel Drive"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "engine_size",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. '1.5L', '2000cc'",
                        max_length=20,
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, help_text="Odometer reading in km", null=True
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=40)),
                (
                    "interior_color",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "chassis_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Chassis / VIN number",
                        max_length=50,
                    ),
                ),
                (
                    "stock_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Internal stock reference number",
                        max_length=40,
                    ),
                ),
                (
                    "buying_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase / cost price",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Asking / selling price",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("certified", "Certified Pre-Owned"),
                        ],
                        default="used",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("offline", "Offline / Hidden"),
                        ],
                        db_index=True,
                        default="in_stock",
                        max_length=10,
                    ),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Physical location of the vehicle",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "features_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Key features, highlights, or import notes",
                    ),
                ),
                (
                    "import_source_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Import source details (e.g. 'Japan direct, Be Forward')",
                    ),
                ),
                (
                    "date_stocked",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="When this vehicle was stocked in",
                    ),
                ),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "buyer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual price at point of sale",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. CASH, BANK_TRANSFER, INSTALLMENT",
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_dealer_vehicles",
                        to="tenants.business",
                    ),
                ),
                (
                    "marketplace_listing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked marketplace listing (auto-managed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_dealer_vehicles",
                        to="inventory.marketplacelisting",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_dealer_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_dealer_stocked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="inventory.carmake",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="inventory.carmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Dealer Vehicle",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "status"],
                        name="inventory_c_busines_90a26c_idx",
                    ),
                    models.Index(
                        fields=["business", "-created_at"],
                        name="inventory_c_busines_fdce3f_idx",
                    ),
                    models.Index(
                        fields=["make", "model"], name="inventory_c_make_id_1002fb_idx"
                    ),
                ],
            },
        ),
    ]
