# Generated by Django 5.2.5 on 2026-04-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1043_car_dealer_vehicle_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("hardware", "Hardware & General Dealers"),
                    ("cement", "Cement / Building Materials"),
                    ("farm", "Farm Manager"),
                    ("welding", "Welding Workshop"),
                    ("car_hire", "Car Hire Service"),
                    ("car_dealer", "Car Dealer"),
                    ("energy", "Renewable Energy"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
    ]
