# Generated by Django 5.2.5 on 2026-04-02 18:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1044_energy_vertical"),
        ("tenants", "0033_energy_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("solar_panel", "Solar Panel"),
                            ("battery", "Battery Bank"),
                            ("inverter", "Inverter"),
                            ("charge_controller", "Charge Controller"),
                            ("meter", "Meter"),
                            ("generator", "Generator"),
                            ("smart_appliance", "Smart Appliance"),
                            ("ev_charger", "EV Charger"),
                            ("breaker", "Breaker / Switch"),
                            ("sensor", "Sensor"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("degraded", "Degraded"),
                            ("faulty", "Faulty"),
                            ("maintenance", "Under Maintenance"),
                            ("replaced", "Replaced / Retired"),
                        ],
                        db_index=True,
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rated capacity (kW for panels/inverters, kWh for batteries, etc.)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "capacity_unit",
                    models.CharField(blank=True, default="kW", max_length=20),
                ),
                ("install_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                (
                    "expected_lifespan_years",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Expected operational lifespan in years",
                        null=True,
                    ),
                ),
                (
                    "maintenance_interval_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=180,
                        help_text="Recommended maintenance interval in days",
                        null=True,
                    ),
                ),
                (
                    "health_score",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="0–100 health score (100=perfect, 0=failed). [AI_HOOK] ML-derived.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "asset_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase cost of this asset (MWK)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "iot_device_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IoT device ID (MQTT topic, API device ID, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "telemetry_ready",
                    models.BooleanField(
                        default=False,
                        help_text="True when this asset can receive live telemetry",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_assets",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Energy Asset",
                "verbose_name_plural": "Energy Assets",
                "ordering": ["site", "asset_type", "brand"],
            },
        ),
        migrations.CreateModel(
            name="AssetMaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Inspection"),
                            ("cleaning", "Panel / Equipment Cleaning"),
                            ("replacement", "Part Replacement"),
                            ("repair", "Repair"),
                            ("calibration", "Calibration / Testing"),
                            ("emergency", "Emergency Response"),
                            ("audit", "Performance Audit"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateField(default=django.utils.timezone.now)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="What was done / observed"
                    ),
                ),
                (
                    "parts_used",
                    models.TextField(
                        blank=True, default="", help_text="Spare parts replaced"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "health_score_after",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("root_cause_notes", models.TextField(blank=True, default="")),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_maintenance_records",
                        to="tenants.business",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="inventory.energyasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Maintenance Record",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="EnergySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Site / customer name", max_length=200),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("household", "Household / Residential"),
                            ("commercial", "Commercial / Business"),
                            ("community", "Community / Mini-grid"),
                            ("agricultural", "Agricultural"),
                            ("industrial", "Industrial"),
                            ("other", "Other"),
                        ],
                        default="household",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("installing", "Under Installation"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Physical address / GPS description",
                        max_length=300,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "installed_capacity_kw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total installed capacity in kW",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("commissioning_date", models.DateField(blank=True, null=True)),
                (
                    "energy_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g. ['solar', 'battery', 'grid', 'generator', 'hybrid']",
                    ),
                ),
                (
                    "installation_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total installation cost (MWK)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "monthly_grid_bill_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated monthly grid/fuel bill before solar (MWK)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary technician responsible for this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_energy_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_sites",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Energy Site",
                "verbose_name_plural": "Energy Sites",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="energyasset",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="inventory.energysite",
            ),
        ),
        migrations.CreateModel(
            name="EnergyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("maintenance_due", "Maintenance Due / Overdue"),
                            ("asset_degraded", "Asset Health Deterioration"),
                            ("low_generation", "Unusual Generation Drop"),
                            ("unusual_consumption", "Unusual Consumption"),
                            ("overload_risk", "Overload Risk"),
                            ("low_battery_health", "Low Battery Health"),
                            ("demand_spike", "Demand Spike Detected"),
                            ("data_missing", "Data Missing / Stale"),
                            ("recurring_fault", "Recurring Site Incident"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("suggested_action", models.TextField(blank=True, default="")),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_alerts",
                        to="tenants.business",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_alerts_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.energyasset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.energysite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Energy Alert",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnergyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_date", models.DateField(db_index=True)),
                (
                    "generation_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Energy generated (kWh) — from solar/generator",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "consumption_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Energy consumed (kWh) — from load",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "battery_soc_pct",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Battery state of charge (%)",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual Entry"), ("iot", "IoT / API")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_readings",
                        to="tenants.business",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="inventory.energysite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Energy Reading",
                "ordering": ["-reading_date"],
                "unique_together": {("site", "reading_date")},
            },
        ),
        migrations.CreateModel(
            name="SavingsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the month this record covers"
                    ),
                ),
                (
                    "estimated_savings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="MWK saved vs. baseline grid/fuel cost",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "operational_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Maintenance + operational cost this month",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "generation_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_savings",
                        to="tenants.business",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_records",
                        to="inventory.energysite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Record",
                "ordering": ["-month"],
                "unique_together": {("site", "month")},
            },
        ),
    ]
