# inventory/migrations/1050_rebuild_carmake_carmodel_tables.py
#
# Removes stale columns from inventory_carmake and inventory_carmodel that
# were present in the old schema (before migration 1043 was faked) but are
# not declared in the current Django models.  Those stale NOT NULL columns
# (e.g. created_at) cause INSERT failures because Django omits them.
#
# Data preservation strategy:
#   - CarMake:  preserve id, name (slug auto-generated by model.save())
#   - CarModel: preserve id, name, make_id (slug auto-generated)
#   The old year_introduced / year_discontinued data is discarded — they are
#   not part of the current model.
#
# Implementation is cross-database:
#   - PostgreSQL:  ALTER TABLE … DROP COLUMN (standard DDL, no rebuild needed)
#   - SQLite:      Full table rebuild (CREATE new / copy / DROP old / RENAME)
#                  because SQLite ≥3.35 supports DROP COLUMN but only when the
#                  column is not referenced by an index; the safer path is the
#                  traditional rebuild, which also strips stale indexes cleanly.
#
# All operations are guarded by introspection checks — safe to re-run.

from django.db import migrations


# ---------------------------------------------------------------------------
# Cross-database introspection helper
# ---------------------------------------------------------------------------

def _col_exists(conn, table, col):
    """
    Return True if `col` exists in `table`.

    Uses Django's built-in introspection API — never touches SQLite-only
    PRAGMA or sqlite_master.  Works on PostgreSQL, SQLite, MySQL.
    """
    with conn.cursor() as cursor:
        try:
            cols = conn.introspection.get_table_description(cursor, table)
        except Exception:
            return False
    return any(c.name == col for c in cols)


# ---------------------------------------------------------------------------
# Migration function
# ---------------------------------------------------------------------------

def rebuild_tables(apps, schema_editor):
    conn = schema_editor.connection
    vendor = conn.vendor

    if vendor == "postgresql":
        _rebuild_postgresql(conn)
    else:
        _rebuild_sqlite(conn)


def _rebuild_postgresql(conn):
    """
    PostgreSQL path: use ALTER TABLE … DROP COLUMN IF EXISTS.
    No table rebuild needed — Postgres supports DDL column removal natively.
    """
    with conn.cursor() as cursor:
        # inventory_carmake: drop stale created_at
        cursor.execute(
            'ALTER TABLE "inventory_carmake" DROP COLUMN IF EXISTS "created_at"'
        )

        # inventory_carmodel: drop stale year_introduced, year_discontinued, created_at
        cursor.execute(
            'ALTER TABLE "inventory_carmodel" DROP COLUMN IF EXISTS "year_introduced"'
        )
        cursor.execute(
            'ALTER TABLE "inventory_carmodel" DROP COLUMN IF EXISTS "year_discontinued"'
        )
        cursor.execute(
            'ALTER TABLE "inventory_carmodel" DROP COLUMN IF EXISTS "created_at"'
        )

        # Null-out FK references that point to rows deleted during rebuild
        # (defensive; should be a no-op on a clean database)
        cursor.execute("""
            UPDATE "inventory_cardealervehicle"
            SET "make_id" = NULL
            WHERE "make_id" IS NOT NULL
              AND "make_id" NOT IN (SELECT id FROM "inventory_carmake")
        """)
        cursor.execute("""
            UPDATE "inventory_cardealervehicle"
            SET "model_id" = NULL
            WHERE "model_id" IS NOT NULL
              AND "model_id" NOT IN (SELECT id FROM "inventory_carmodel")
        """)


def _rebuild_sqlite(conn):
    """
    SQLite path: traditional table rebuild to strip stale columns and
    constraints.  Safer than ALTER TABLE … DROP COLUMN on SQLite because it
    avoids index-interference edge cases and clears all stale schema debris.
    """
    with conn.cursor() as cursor:
        # ----------------------------------------------------------------
        # CarMake rebuild
        # ----------------------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS "_new_inventory_carmake" (
                "id"         integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "name"       varchar(80) NOT NULL UNIQUE,
                "slug"       varchar(80) NOT NULL DEFAULT '',
                "logo"       varchar(100) NULL,
                "sort_order" smallint unsigned NOT NULL DEFAULT 0,
                "is_popular" bool NOT NULL DEFAULT 0
            )
        """)
        cursor.execute("""
            INSERT INTO "_new_inventory_carmake" (id, name, slug, sort_order, is_popular)
            SELECT id, name, '', 0, 0
            FROM "inventory_carmake"
            WHERE id NOT IN (SELECT id FROM "_new_inventory_carmake")
        """)
        cursor.execute('DROP TABLE "inventory_carmake"')
        cursor.execute(
            'ALTER TABLE "_new_inventory_carmake" RENAME TO "inventory_carmake"'
        )
        cursor.execute(
            'CREATE INDEX IF NOT EXISTS "inventory_carmake_sort_order_3e7c34b3" '
            'ON "inventory_carmake" ("sort_order")'
        )

        # ----------------------------------------------------------------
        # CarModel rebuild
        # ----------------------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS "_new_inventory_carmodel" (
                "id"           integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "name"         varchar(80) NOT NULL,
                "slug"         varchar(80) NOT NULL DEFAULT '',
                "body_type"    varchar(20) NOT NULL DEFAULT '',
                "common_years" varchar(40) NOT NULL DEFAULT '',
                "sort_order"   smallint unsigned NOT NULL DEFAULT 0,
                "make_id"      bigint NOT NULL
                               REFERENCES "inventory_carmake" ("id")
                               DEFERRABLE INITIALLY DEFERRED
            )
        """)
        cursor.execute("""
            INSERT INTO "_new_inventory_carmodel"
                   (id, name, slug, body_type, common_years, sort_order, make_id)
            SELECT id, name, '', '', '', 0, make_id
            FROM "inventory_carmodel"
            WHERE id NOT IN (SELECT id FROM "_new_inventory_carmodel")
        """)
        cursor.execute('DROP TABLE "inventory_carmodel"')
        cursor.execute(
            'ALTER TABLE "_new_inventory_carmodel" RENAME TO "inventory_carmodel"'
        )
        cursor.execute(
            'CREATE INDEX IF NOT EXISTS "inventory_carmodel_sort_order_idx" '
            'ON "inventory_carmodel" ("sort_order")'
        )
        cursor.execute(
            'CREATE INDEX IF NOT EXISTS "inventory_carmodel_make_id_aed37374" '
            'ON "inventory_carmodel" ("make_id")'
        )

        # ----------------------------------------------------------------
        # Fix CarDealerVehicle FK integrity after rebuild
        # ----------------------------------------------------------------
        cursor.execute("""
            UPDATE "inventory_cardealervehicle"
            SET "make_id" = NULL
            WHERE "make_id" IS NOT NULL
              AND "make_id" NOT IN (SELECT id FROM "inventory_carmake")
        """)
        cursor.execute("""
            UPDATE "inventory_cardealervehicle"
            SET "model_id" = NULL
            WHERE "model_id" IS NOT NULL
              AND "model_id" NOT IN (SELECT id FROM "inventory_carmodel")
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1049_fix_carmake_carmodel_schema"),
    ]

    operations = [
        migrations.RunPython(
            rebuild_tables,
            migrations.RunPython.noop,
        ),
    ]
