# Generated by Django 5.2.5 on 2026-04-04 13:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models_car_dealer
import inventory.models_car_hire
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1051_energy_commerce_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="photo",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="marketplace_listing",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked marketplace listing (auto-managed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="car_hire_vehicles",
                to="inventory.marketplacelisting",
            ),
        ),
        migrations.AlterField(
            model_name="copilotinsight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="confidence_pct",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Confidence level (0–100%)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="forecast_date",
            field=models.DateField(
                db_index=True, help_text="Date this forecast was generated"
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="horizon_days",
            field=models.PositiveSmallIntegerField(
                default=7, help_text="Forecast horizon (days)"
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="energydataupload",
            name="data_quality_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Overall data quality score (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="energydataupload",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="loadprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="loadprofile",
            name="load_breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Category-wise load breakdown {'lighting': 30, 'hvac': 45, ...} in %",
            ),
        ),
        migrations.AlterField(
            model_name="loadprofile",
            name="load_factor_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Load factor = avg demand / peak demand * 100",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loadprofile",
            name="utilization_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="System utilization (demand vs installed capacity)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="days_per_week",
            field=models.PositiveSmallIntegerField(
                default=7, help_text="Days used per week (1–7)"
            ),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="efficiency_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Efficiency correction (1.0 = no correction)",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="hours_per_day",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("1.0"),
                help_text="Hours of use per day",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="is_critical",
            field=models.BooleanField(
                default=False, help_text="Must run during outage"
            ),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="name",
            field=models.CharField(help_text="Appliance / load name", max_length=150),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="surge_wattage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Surge / starting wattage per unit (W)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sizingappliance",
            name="wattage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Running wattage per unit (W)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="autonomy_days",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("1.0"),
                help_text="Days of autonomy required",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="battery_dod_pct",
            field=models.PositiveSmallIntegerField(
                default=80, help_text="Battery depth of discharge (%)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="battery_replacement_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated battery replacement cost (MWK)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="battery_replacement_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=10,
                help_text="Expected year for battery replacement",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="battery_voltage",
            field=models.PositiveSmallIntegerField(
                default=48, help_text="System battery voltage (V)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="component_summary",
            field=models.JSONField(
                blank=True, default=dict, help_text="Recommended component breakdown"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="diesel_escalation_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("7.0"),
                help_text="Annual diesel price escalation (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="discount_rate_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.0"),
                help_text="Discount rate for NPV calculation (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="diversity_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.80"),
                help_text="Diversity factor (0.0–1.0)",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="estimated_runtime_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Estimated battery runtime under full load (hours)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="future_growth_pct",
            field=models.PositiveSmallIntegerField(
                default=20, help_text="Planned future load growth (%)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="grid_reliability_pct",
            field=models.PositiveSmallIntegerField(
                default=80, help_text="Estimated grid reliability (0-100%)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="growth_headroom_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Available capacity headroom for future growth (%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="inflation_rate_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8.0"),
                help_text="Annual inflation assumption (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="irr_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Internal Rate of Return (%)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="is_recommended_scenario",
            field=models.BooleanField(
                default=False,
                help_text="Flagged as the recommended option in a comparison",
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="linked_project_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site created when proposal is converted to active project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originating_proposals",
                to="inventory.energysite",
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="npv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net Present Value of the project (MWK)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="panel_efficiency_pct",
            field=models.PositiveSmallIntegerField(
                default=85, help_text="Derating factor for panels (%)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="panel_wattage",
            field=models.PositiveSmallIntegerField(
                default=550, help_text="Individual panel wattage (Wp)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="peak_sun_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("5.0"),
                help_text="Average peak sun hours/day for this location",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="recommendations",
            field=models.JSONField(
                blank=True, default=list, help_text="List of recommendation strings"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="safety_margin_pct",
            field=models.PositiveSmallIntegerField(
                default=15, help_text="Engineering safety margin (%)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="scenario_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Group ID to link scenarios for side-by-side comparison",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="scenario_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label within scenario group (e.g. 'Low Cost', 'Balanced', 'High Reliability')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="sensitivity_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sensitivity analysis results: {'pessimistic': {...}, 'base': {...}, 'optimistic': {...}}",
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="simultaneity_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.70"),
                help_text="Simultaneity factor (0.0–1.0)",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="tariff_escalation_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.0"),
                help_text="Annual tariff/energy cost escalation (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="unmet_load_risk_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Percentage of load that may go unmet (%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="warnings",
            field=models.JSONField(
                blank=True, default=list, help_text="List of warning strings"
            ),
        ),
        migrations.AlterField(
            model_name="technicianvisit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="CarDealerVehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=inventory.models_car_dealer._car_dealer_vehicle_image_path
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the primary/cover image shown on cards and marketplace",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="inventory.cardealervehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Image",
                "verbose_name_plural": "Vehicle Images",
                "ordering": ["-is_cover", "sort_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="HireVehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=inventory.models_car_hire._hire_vehicle_image_path
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, help_text="Mark as the primary/cover image"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="inventory.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hire Vehicle Image",
                "verbose_name_plural": "Hire Vehicle Images",
                "ordering": ["-is_cover", "sort_order", "uploaded_at"],
            },
        ),
    ]
