# Generated by Django 5.2.5 on 2026-04-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1053_farm_premium_marketplace"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="farmlivestockbatch",
            new_name="inventory_f_busines_25a1aa_idx",
            old_name="inventory_f_business_3e7a8d_idx",
        ),
        migrations.AddField(
            model_name="systemsizingrun",
            name="annual_maintenance_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual maintenance cost as % of CapEx (overrides default 2%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemsizingrun",
            name="diesel_cost_per_litre",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Diesel fuel cost per litre (MWK) — used when generator enabled",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemsizingrun",
            name="energy_tariff_per_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Grid electricity tariff (MWK/kWh) — overrides default if set",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemsizingrun",
            name="installation_cost_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Installation cost as % of CapEx (overrides default 15%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
