# Generated by Django 5.2.5 on 2026-04-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1055_sizing_component_costs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsizingrun",
            name="cost_breakers_lump",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Breakers/protection lump-sum (MWK). Default: 80,000",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="cost_mounting_lump",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mounting structure lump-sum (MWK). Default: 50,000",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="cost_per_battery_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Battery cost per kWh (MWK). Default: 450,000",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="cost_per_cc_amp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charge controller cost per Amp (MWK). Default: 12,000",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="cost_per_inverter_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Inverter cost per kW (MWK). Default: 180,000",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="cost_per_panel_wp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Solar panel cost per Wp (MWK). Default: 650",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsizingrun",
            name="cost_wiring_lump",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cable/wiring lump-sum (MWK). Default: 150,000",
                max_digits=12,
                null=True,
            ),
        ),
    ]
