# Generated by Django 5.2.5 on 2026-04-28 06:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1059_grocerysale_legacy_fields_state_only"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="iotreading",
            new_name="inventory_i_device__aa70ae_idx",
            old_name="inventory_iot_device_type_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="mobilemoneytransaction",
            new_name="inventory_m_busines_a55f62_idx",
            old_name="inventory_mm_biz_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="mobilemoneytransaction",
            new_name="inventory_m_busines_4413f7_idx",
            old_name="inventory_mm_biz_type_ts_idx",
        ),
        migrations.AlterField(
            model_name="grocerysale",
            name="sale_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("discount", "Discount"),
                    ("wholesale", "Wholesale"),
                    ("correction", "Correction"),
                ],
                default="regular",
                help_text="Type of sale (regular, discount, wholesale, correction)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="grocerysale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Legacy field: mirrors total_price for backward DB compatibility",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="grocerysale",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="iotdevice",
            name="api_key",
            field=models.CharField(
                help_text="Secret token used by device in Authorization header",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="iotdevice",
            name="device_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique device identifier (e.g. esp32-energy-001)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="iotdevice",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Device metadata (firmware, location, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="iotdevice",
            name="vertical",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Associated vertical (e.g. energy, farm)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="iotreading",
            name="reading_type",
            field=models.CharField(
                db_index=True,
                help_text="e.g. voltage, current, power, temperature, humidity",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="iotreading",
            name="unit",
            field=models.CharField(
                blank=True, default="", help_text="e.g. V, A, W, °C, %", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("hardware", "Hardware & General Dealers"),
                    ("cement", "Cement / Building Materials"),
                    ("farm", "Farm Manager"),
                    ("welding", "Welding Workshop"),
                    ("car_hire", "Car Hire Service"),
                    ("car_dealer", "Car Dealer"),
                    ("energy", "Renewable Energy"),
                    ("mobile_money", "Mobile Money Agent"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mobilemoneyreconciliation",
            name="difference",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="actual_closing_cash - expected_closing_cash (negative = shortage)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="mobilemoneytransaction",
            name="cash_movement",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Change in physical cash (+inflow, -outflow)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="mobilemoneytransaction",
            name="commission",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Commission/fee earned by agent",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="mobilemoneytransaction",
            name="float_movement",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Change in e-float (+inflow, -outflow)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="mobilemoneytransaction",
            name="reference_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Transaction reference from network",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mobilemoneytransaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("cash_in", "Cash In"),
                    ("cash_out", "Cash Out"),
                    ("airtime", "Airtime Top-Up"),
                    ("bill_payment", "Bill Payment"),
                    ("reversal", "Reversal"),
                    ("adjustment", "Adjustment"),
                ],
                db_index=True,
                default="cash_in",
                help_text="Type of transaction",
                max_length=20,
            ),
        ),
    ]
