# Generated by Django 5.2.5 on 2026-05-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1061_mobilemoney_operations_upgrade"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mobilemoneycredit",
            new_name="inventory_m_busines_b10da4_idx",
            old_name="inventory_m_biz_status_idx",
        ),
        migrations.RenameIndex(
            model_name="mobilemoneycredit",
            new_name="inventory_m_busines_82ed78_idx",
            old_name="inventory_m_biz_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="mobilemoneytransaction",
            new_name="inventory_m_busines_a05378_idx",
            old_name="inventory_m_biz_net_ts_idx",
        ),
    ]
