# Generated by Django 5.2.5 on 2026-05-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1065_repair_marketplace_stale_is_active_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="accuracy_m",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timelog",
            name="distance_m",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timelog",
            name="geofence_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="timelog",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
