# Generated by Django 5.2.5 on 2026-05-03 04:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models_welding
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1066_timelog_attendance_geo_fields"),
        ("tenants", "0034_alter_business_business_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="weldingquote",
            name="branding_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Business branding snapshot used when the quote was created",
            ),
        ),
        migrations.AddField(
            model_name="weldingquote",
            name="customer_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="weldingquote",
            name="customer_contact_person",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="weldingquote",
            name="customer_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="WeldingBrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=inventory.models_welding.welding_brand_logo_upload_path,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "business_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "business_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("business_address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("payment_instructions", models.TextField(blank=True, default="")),
                ("default_terms", models.TextField(blank=True, default="")),
                (
                    "authorized_signature_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=inventory.models_welding.welding_signature_upload_path,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_branding",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Branding Settings",
                "verbose_name_plural": "Welding Branding Settings",
            },
        ),
        migrations.CreateModel(
            name="WeldingNotebookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_customer_name", models.CharField(max_length=180)),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("customer_address", models.TextField(blank=True, default="")),
                (
                    "visit_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("trellidor", "Trellidor"),
                            ("gate", "Gate"),
                            ("window", "Window"),
                            ("table", "Table"),
                            ("bed", "Bed"),
                            ("roofing", "Roofing"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=30,
                    ),
                ),
                ("measurements", models.TextField(blank=True, default="")),
                ("materials_needed", models.TextField(blank=True, default="")),
                (
                    "estimated_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("quoted", "Quoted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=inventory.models_welding.welding_notebook_image_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welding_notebook_entries",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_notebook_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="welding_notebook_entries",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welding Notebook Entry",
                "verbose_name_plural": "Welding Notebook Entries",
                "ordering": ["-visit_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-visit_at"],
                        name="inventory_w_busines_ce73c2_idx",
                    ),
                    models.Index(
                        fields=["business", "status"],
                        name="inventory_w_busines_8035ee_idx",
                    ),
                    models.Index(
                        fields=["business", "job_type"],
                        name="inventory_w_busines_7d5b0e_idx",
                    ),
                ],
            },
        ),
    ]
