# Generated by Django 5.2.5 on 2026-05-03 06:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1067_weldingquote_branding_snapshot_and_more"),
        ("tenants", "0034_alter_business_business_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("customer_message", models.TextField(blank=True, default="")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("quote_request", "Quote Request"),
                            ("whatsapp_click", "WhatsApp Click"),
                            ("phone_click", "Phone Click"),
                            ("email_click", "Email Click"),
                            ("marketplace_form", "Marketplace Form"),
                        ],
                        db_index=True,
                        default="marketplace_form",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("negotiating", "Negotiating"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("invalid", "Invalid"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "deal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("commission_amount_overridden", models.BooleanField(default=False)),
                (
                    "commission_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("pending", "Pending"),
                            ("due", "Due"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                        ],
                        db_index=True,
                        default="not_applicable",
                        max_length=24,
                    ),
                ),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("hq_notes", models.TextField(blank=True, default="")),
                (
                    "visitor_session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                ("visitor_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="inventory.marketplacelisting",
                    ),
                ),
                (
                    "seller_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_leads",
                        to="tenants.business",
                    ),
                ),
                (
                    "welding_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_leads",
                        to="inventory.weldingjob",
                    ),
                ),
                (
                    "welding_notebook_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_leads",
                        to="inventory.weldingnotebookentry",
                    ),
                ),
                (
                    "welding_quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_leads",
                        to="inventory.weldingquote",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller_business", "status"],
                        name="inventory_m_seller__729483_idx",
                    ),
                    models.Index(
                        fields=["seller_business", "commission_status"],
                        name="inventory_m_seller__bb3af6_idx",
                    ),
                    models.Index(
                        fields=["source_type", "-created_at"],
                        name="inventory_m_source__0aa603_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="inventory_m_status_43c8c8_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="inventory_m_created_e843a1_idx"
                    ),
                ],
            },
        ),
    ]
