# Generated by Django 5.2.5 on 2026-05-03 15:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models_marketplace
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1069_marketplacelead_commission_paid_at_and_more"),
        ("tenants", "0034_alter_business_business_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplacelead",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("quote_request", "Quote Request"),
                    ("whatsapp_click", "WhatsApp Click"),
                    ("phone_click", "Phone Click"),
                    ("email_click", "Email Click"),
                    ("marketplace_form", "Marketplace Form"),
                    ("marketplace_checkout", "Marketplace Checkout"),
                ],
                db_index=True,
                default="marketplace_form",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="MarketplaceStorefrontProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=inventory.models_marketplace.marketplace_storefront_upload_path,
                        validators=[
                            inventory.models_marketplace.validate_marketplace_media_size
                        ],
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=inventory.models_marketplace.marketplace_storefront_upload_path,
                        validators=[
                            inventory.models_marketplace.validate_marketplace_media_size
                        ],
                    ),
                ),
                (
                    "store_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                (
                    "opening_hours",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("social_links", models.JSONField(blank=True, default=dict)),
                (
                    "categories",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("trust_badges", models.JSONField(blank=True, default=list)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_storefront",
                        to="tenants.business",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_storefront_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["business__name"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_name", models.CharField(max_length=200)),
                ("buyer_phone", models.CharField(max_length=40)),
                (
                    "buyer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("delivery_notes", models.TextField(blank=True, default="")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "platform_commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "platform_commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "seller_gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "seller_net_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paychangu_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "paychangu_transaction_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                ("raw_payment_payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, default="")),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_orders",
                        to="inventory.marketplacelead",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="inventory.marketplacelisting",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_orders_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_orders",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller_business", "payment_status"],
                        name="inventory_m_seller__6e983b_idx",
                    ),
                    models.Index(
                        fields=["listing", "payment_status"],
                        name="inventory_m_listing_0b016d_idx",
                    ),
                    models.Index(
                        fields=["payment_status", "-created_at"],
                        name="inventory_m_payment_4cb09a_idx",
                    ),
                    models.Index(
                        fields=["paychangu_reference"],
                        name="inventory_m_paychan_05c504_idx",
                    ),
                ],
            },
        ),
    ]
