# Generated by Django 5.2.5 on 2026-05-03 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1070_alter_marketplacelead_source_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacestorefrontprofile",
            name="featured_status",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="marketplacestorefrontprofile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketplace_storefronts_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marketplacestorefrontprofile",
            name="verified_status",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
