# Generated by Django 5.2.5 on 2026-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1071_marketplacestorefrontprofile_featured_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacestorefrontprofile",
            name="currency",
            field=models.CharField(
                choices=[
                    ("MWK", "MWK - Malawi Kwacha"),
                    ("USD", "USD - US Dollar"),
                    ("ZAR", "ZAR - South African Rand"),
                    ("GBP", "GBP - British Pound"),
                    ("EUR", "EUR - Euro"),
                    ("TZS", "TZS - Tanzanian Shilling"),
                    ("ZMW", "ZMW - Zambian Kwacha"),
                ],
                default="MWK",
                max_length=3,
            ),
        ),
    ]
