# Generated by Django 5.2.5 on 2026-05-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1074_recurringcost"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recurringcost",
            new_name="inventory_r_busines_635041_idx",
            old_name="inv_recurr_biz_active_idx",
        ),
        migrations.RenameIndex(
            model_name="recurringcost",
            new_name="inventory_r_busines_633b10_idx",
            old_name="inv_recurr_biz_nextrun_idx",
        ),
    ]
