# Generated by Django 5.2.5 on 2026-05-26 23:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1081_butchery_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="butcheryintake",
            name="business",
        ),
        migrations.RemoveField(
            model_name="butcheryintake",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="butcheryintakeallocation",
            name="intake",
        ),
        migrations.RemoveField(
            model_name="butcheryintakeallocation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="butcheryproduct",
            name="business",
        ),
        migrations.RemoveField(
            model_name="butcheryproduct",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="butcherysale",
            name="product",
        ),
        migrations.RemoveField(
            model_name="butcherysale",
            name="business",
        ),
        migrations.RemoveField(
            model_name="butcherysale",
            name="created_by",
        ),
        migrations.AlterModelOptions(
            name="consultancyclient",
            options={
                "ordering": ["name"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="consultancyproject",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterField(
            model_name="commissionrule",
            name="network",
            field=models.CharField(
                choices=[
                    ("airtel", "Airtel Money"),
                    ("tnm", "TNM Mpamba"),
                    ("bank", "Bank Agent"),
                    ("other", "Other / Custom"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultancyclient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultancyexpense",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultancyinvoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultancyinvoice",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                help_text="Quote this invoice was generated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="inventory.consultancyquote",
            ),
        ),
        migrations.AlterField(
            model_name="consultancyinvoiceitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultancypayment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultancypayment",
            name="reference",
            field=models.CharField(
                blank=True, help_text="Reference / transaction number", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="consultancyproject",
            name="agreed_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Agreed contract/project value",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consultancyproject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultancyproject",
            name="monthly_retainer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly retainer fee (for retainer projects)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consultancyquote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultancyquoteitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="farmlivestockevent",
            name="count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of animals affected (0 for non-count events like vaccination)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="farmlivestockevent",
            name="quantity_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unit for quantity (e.g. 'eggs', 'litres', 'kg')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="merchproduct",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phones", "Phones & Electronics"),
                    ("liquor", "Liquor / Bar"),
                    ("grocery", "Grocery / General"),
                    ("pharmacy", "Cosmetics & Pharmacy"),
                    ("clothing", "Clothing"),
                    ("gym", "Gym / Fitness"),
                    ("hardware", "Hardware & General Dealers"),
                    ("cement", "Cement / Building Materials"),
                    ("farm", "Farm Manager"),
                    ("welding", "Welding Workshop"),
                    ("car_hire", "Car Hire Service"),
                    ("car_dealer", "Car Dealer"),
                    ("energy", "Renewable Energy"),
                    ("mobile_money", "Mobile Money Agent"),
                    ("mixed_retail", "Mixed Retail"),
                    ("consultancy", "Consultancy & Services"),
                    ("butchery", "Butchery"),
                ],
                default="grocery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mobilemoneytransaction",
            name="network",
            field=models.CharField(
                choices=[
                    ("airtel", "Airtel Money"),
                    ("tnm", "TNM Mpamba"),
                    ("bank", "Bank Agent"),
                    ("other", "Other / Custom"),
                ],
                db_index=True,
                default="airtel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="retailcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="retaildepartment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="retailexpense",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="retailexpense",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="retailproduct",
            name="dimensions",
            field=models.CharField(
                blank=True, help_text="e.g. 120cm x 80cm x 75cm", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="retailproduct",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="retailproduct",
            name="imei",
            field=models.CharField(
                blank=True, help_text="IMEI for phones/tablets", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="retailproduct",
            name="size",
            field=models.CharField(
                blank=True, help_text="e.g. S, M, L, XL, 42", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="retailsale",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount actually paid (for credit sales)",
                max_digits=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="retailsale",
            name="cost_price_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Cost price at time of sale — for profit tracking",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="retailsale",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="retailsale",
            name="receipt_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Groups multiple sale lines from one transaction",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="retailsale",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Actual selling price at time of sale (may differ from product price)",
                max_digits=14,
            ),
        ),
        migrations.DeleteModel(
            name="ButcheryExpense",
        ),
        migrations.DeleteModel(
            name="ButcheryIntake",
        ),
        migrations.DeleteModel(
            name="ButcheryIntakeAllocation",
        ),
        migrations.DeleteModel(
            name="ButcheryProduct",
        ),
        migrations.DeleteModel(
            name="ButcherySale",
        ),
    ]
