# Generated by Django 5.2.5 on 2026-05-27 09:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "1084_mixed_retail_dept_enrollments_and_templates"),
        ("tenants", "0035_add_new_business_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="butcheryproduct",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Butchery Product",
                "verbose_name_plural": "Butchery Products",
            },
        ),
        migrations.AddField(
            model_name="butcheryintake",
            name="storage_location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="butcheryproduct",
            name="category",
            field=models.CharField(
                choices=[
                    ("pork", "Pork"),
                    ("sausage", "Sausage"),
                    ("beef", "Beef"),
                    ("goat", "Goat"),
                    ("chicken", "Chicken / Zinziri"),
                    ("lamb", "Lamb"),
                    ("fish", "Fish"),
                    ("drinks", "Drinks"),
                    ("sides", "Sides & Other"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="butcherysale",
            name="sale_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="butcheryproduct",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("pcs", "Pieces"),
                    ("pack", "Pack"),
                    ("portion", "Portion"),
                    ("bottle", "Bottle"),
                    ("box", "Box"),
                    ("bird", "Bird"),
                    ("service", "Service"),
                    ("other", "Other"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="retailbusinessdepartment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="retailproduct",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "Pieces"),
                    ("kg", "Kilograms"),
                    ("g", "Grams"),
                    ("litre", "Litres"),
                    ("ml", "Millilitres"),
                    ("pair", "Pair"),
                    ("pack", "Pack"),
                    ("box", "Box"),
                    ("roll", "Roll"),
                    ("set", "Set"),
                    ("m", "Metres"),
                    ("service", "Service"),
                    ("other", "Other"),
                ],
                default="pcs",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="retailproducttemplate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="ButcheryProcessingBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "meat_type",
                    models.CharField(
                        choices=[
                            ("beef", "Beef"),
                            ("goat", "Goat"),
                            ("chicken", "Chicken"),
                            ("pork", "Pork"),
                            ("lamb", "Lamb"),
                            ("fish", "Fish"),
                            ("other", "Other"),
                        ],
                        default="beef",
                        max_length=20,
                    ),
                ),
                (
                    "input_kg",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Total kg of raw meat going into processing",
                        max_digits=12,
                    ),
                ),
                (
                    "waste_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Loss/waste kg (bones, trimmings not sold, etc.)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("complete", "Complete")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="butchery_processing_batches",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_batches",
                        to="inventory.butcheryintake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Batch",
                "verbose_name_plural": "Processing Batches",
                "ordering": ["-batch_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ButcheryProcessingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "cost_per_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.butcheryprocessingbatch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_lines",
                        to="inventory.butcheryproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Line",
                "verbose_name_plural": "Processing Lines",
            },
        ),
        migrations.CreateModel(
            name="TimeGeofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("radius_m", models.PositiveIntegerField(default=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("business", "name")},
            },
        ),
        migrations.CreateModel(
            name="TimeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("arrival_at", models.DateTimeField(blank=True, null=True)),
                ("departure_at", models.DateTimeField(blank=True, null=True)),
                ("work_s", models.IntegerField(default=0)),
                ("offsite_s", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("onsite", "On site"),
                            ("offsite", "Off site"),
                            ("closed", "Closed"),
                        ],
                        default="offsite",
                        max_length=12,
                    ),
                ),
                (
                    "state_since",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_sessions",
                        to="tenants.business",
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="inventory.timegeofence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ping", "Ping"),
                            ("arrive", "Arrive"),
                            ("depart", "Depart"),
                            ("onsite", "On site"),
                            ("offsite", "Off site"),
                            ("close", "Close"),
                        ],
                        max_length=16,
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="inventory.timesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="ButcheryDailyLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("locked", "Locked")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="butchery_daily_ledgers",
                        to="tenants.business",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Ledger",
                "verbose_name_plural": "Daily Ledgers",
                "ordering": ["-date"],
                "unique_together": {("business", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="timesession",
            index=models.Index(
                fields=["business", "user", "day"],
                name="inventory_t_busines_a23657_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timesession",
            index=models.Index(
                fields=["business", "state"], name="inventory_t_busines_468977_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timesession",
            unique_together={("business", "user", "geofence", "day")},
        ),
    ]
