# Generated by Django 5.2.5 on 2025-08-12 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EDIT', 'Edit'), ('DELETE', 'Delete'), ('DELETE_DENIED', 'Delete denied')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
