# Generated by Django 5.2.5 on 2025-08-13 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_timelog_wallettxn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imei', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=32)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='activation_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_status',
            field=models.CharField(choices=[('UNDER_WARRANTY', 'Under warranty'), ('WAITING_ACTIVATION', 'Waiting to be activated'), ('NOT_IN_COUNTRY', 'Not in country'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=32),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['imei'], name='inventory_i_imei_36d8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['warranty_status', 'warranty_expires_at'], name='inventory_i_warrant_49f638_idx'),
        ),
        migrations.AddField(
            model_name='warrantychecklog',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warrantychecklog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='warrantychecklog',
            index=models.Index(fields=['imei', 'created_at'], name='inventory_w_imei_c8f3df_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantychecklog',
            index=models.Index(fields=['result', 'created_at'], name='inventory_w_result_6c6fb7_idx'),
        ),
    ]
