# Generated by Django 4.2.23 on 2025-08-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auditlog_alter_inventoryaudit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaudit',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='inventory.inventoryitem'),
        ),
    ]
