# Generated by Django 4.2.23 on 2025-08-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventoryaudit_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='joined_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(default=150, help_text='Meters around (lat, lon) considered on-site.'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='checkin_type',
            field=models.CharField(choices=[('ARRIVAL', 'Arrival'), ('DEPARTURE', 'Departure')], default='ARRIVAL', max_length=12),
        ),
        migrations.AddField(
            model_name='timelog',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='within_geofence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='wallettxn',
            name='reason',
            field=models.CharField(choices=[('EARLY_BIRD', 'Early-bird bonus'), ('LATE_PENALTY', 'Late penalty'), ('SUNDAY_BONUS', 'Sunday bonus'), ('ADJUSTMENT', 'Adjustment'), ('COMMISSION', 'Commission'), ('ADVANCE', 'Advance payment to agent'), ('PAYOUT', 'Payout to agent')], default='ADJUSTMENT', max_length=32),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['joined_on'], name='inventory_a_joined__91d0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['location'], name='inventory_a_locatio_dc6b09_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='inventory_l_city_472d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user', 'logged_at'], name='inventory_t_user_id_b2ec1f_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['location', 'logged_at'], name='inventory_t_locatio_f0c00b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettxn',
            index=models.Index(fields=['user', 'created_at'], name='inventory_w_user_id_28ba62_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettxn',
            index=models.Index(fields=['reason', 'created_at'], name='inventory_w_reason_c4c694_idx'),
        ),
    ]
