# Generated by Django 4.2.23 on 2025-09-09 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('low_runway', 'low_runway'), ('budget_overshoot', 'budget_overshoot'), ('payroll_risk', 'payroll_risk'), ('unusual_spend', 'unusual_spend'), ('stockout_risk', 'stockout_risk')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=10)),
                ('subject_type', models.CharField(max_length=30)),
                ('subject_id', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('state', models.CharField(default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('operational', 'operational'), ('capital', 'capital'), ('variable', 'variable')], default='operational', max_length=20)),
                ('is_personal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('horizon_days', models.PositiveIntegerField(default=30)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_inflows', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_outflows', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_runway_days', models.PositiveIntegerField()),
                ('method', models.CharField(default='moving_avg', max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(default='admin', max_length=10)),
                ('audience_id', models.CharField(default='admin', max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('rationale', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.6)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MWK', max_length=8)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_type', models.CharField(choices=[('agent', 'agent'), ('landlord', 'landlord'), ('supplier', 'supplier')], max_length=15)),
                ('payee_id', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MWK', max_length=8)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED')], default='CREATED', max_length=10)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('external_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, help_text='FK to BRANCH_MODEL when available; otherwise a text identifier.', max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MWK', max_length=8)),
                ('date', models.DateField()),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='cfo.expensecategory')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('inflow', 'inflow'), ('outflow', 'outflow'), ('commit', 'commit')], max_length=10)),
                ('branch', models.CharField(blank=True, help_text='FK to BRANCH_MODEL when available; otherwise a text identifier.', max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MWK', max_length=8)),
                ('date', models.DateField()),
                ('ref_type', models.CharField(max_length=30)),
                ('ref_id', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'ref_type'], name='cfo_cashled_date_49a5c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, help_text='FK to BRANCH_MODEL when available; otherwise a text identifier.', max_length=64, null=True)),
                ('month', models.DateField(help_text='Use first day of month, e.g., 2025-09-01')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='cfo.expensecategory')),
            ],
            options={
                'unique_together': {('branch', 'month', 'category')},
            },
        ),
    ]
