# Generated by Django 6.0.5 on 2026-05-26 10:22

from django.db import migrations, models


def migrate_manager_to_underwriter(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    Group = apps.get_model("auth", "Group")
    manager_group = Group.objects.filter(name="Manager").first()
    underwriter_group, _ = Group.objects.get_or_create(name="Underwriter")

    UserProfile.objects.filter(role="manager").update(role="underwriter")

    if manager_group:
        for user in manager_group.user_set.all():
            user.groups.add(underwriter_group)
            user.groups.remove(manager_group)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(migrate_manager_to_underwriter, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No role assigned"),
                    ("merchant", "Merchant"),
                    ("underwriter", "Underwriter"),
                    ("hq", "HQ"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
