# Generated by Django 6.0.5 on 2026-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_staff_superusers_default_hq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant", "Merchant"),
                    ("merchant_admin", "Merchant Administrator"),
                    ("underwriter", "Underwriter"),
                    ("tech_support", "Tech Support"),
                    ("hq", "HQ"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
