# Generated by Django 5.2.5 on 2025-12-01 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0028_alter_merchproduct_kind"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentWorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="First ping inside the geofence radius.",
                        null=True,
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Most recent ping inside the geofence radius.",
                        null=True,
                    ),
                ),
                (
                    "total_on_site_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Total minutes spent inside the geofence."
                    ),
                ),
                (
                    "total_idle_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total minutes away from the store during working hours.",
                    ),
                ),
                ("scheduled_start", models.TimeField(blank=True, null=True)),
                ("scheduled_end", models.TimeField(blank=True, null=True)),
                (
                    "arrived_early_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutes arrived before scheduled_start (positive = early).",
                    ),
                ),
                (
                    "left_late_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutes stayed after scheduled_end (positive = late).",
                    ),
                ),
                (
                    "arrived_late_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutes arrived after scheduled_start (positive = late).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to="tenants.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_logs",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "-first_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "is_inside_geofence",
                    models.BooleanField(
                        default=False,
                        help_text="True if this ping was within the location's geofence radius.",
                    ),
                ),
                (
                    "work_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings",
                        to="timelogs.agentworklog",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent user for this time log.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelogs",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeLogSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("in_range", models.BooleanField(default=False)),
                ("source", models.CharField(default="gps", max_length=16)),
                (
                    "timelog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="timelogs.timelog",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Leave blank for all days.",
                        null=True,
                    ),
                ),
                (
                    "scheduled_start",
                    models.TimeField(
                        default="08:00", help_text="Expected start time (e.g., 08:00)."
                    ),
                ),
                (
                    "scheduled_end",
                    models.TimeField(
                        default="17:00", help_text="Expected end time (e.g., 17:00)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="tenants.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, this is the business-wide default.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Working Hours",
                "verbose_name_plural": "Working Hours",
                "ordering": ["business", "location", "day_of_week"],
            },
        ),
        migrations.AddIndex(
            model_name="agentworklog",
            index=models.Index(
                fields=["business", "work_date"], name="timelogs_ag_busines_15326f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentworklog",
            index=models.Index(
                fields=["agent", "work_date"], name="timelogs_ag_agent_i_fdb3b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentworklog",
            index=models.Index(
                fields=["location", "work_date"], name="timelogs_ag_locatio_7d7bb5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentworklog",
            unique_together={("agent", "business", "work_date")},
        ),
        migrations.AddIndex(
            model_name="locationping",
            index=models.Index(
                fields=["work_log", "timestamp"], name="timelogs_lo_work_lo_681a5e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workinghours",
            unique_together={("business", "location", "day_of_week")},
        ),
    ]
