# Generated by Django 5.2.5 on 2025-12-02 10:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentworklog",
            name="bonus_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Bonus amount added for early arrival (MWK).",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="agentworklog",
            name="penalty_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Penalty amount deducted for lateness/absence (MWK).",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="agentworklog",
            name="wallet_processed",
            field=models.BooleanField(
                default=False,
                help_text="True if penalty/bonus has been applied to agent wallet.",
            ),
        ),
    ]
