"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3mtl0z7s^6z9g$yac8tv*(^($um4o=592tmtrym6o&33**xjo^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts.apps.AccountsConfig",
    "merchants",
    "core",
    "geography",
    "applications",
    "deals",
    "earnings",
    "commissions",
    "rewards",
    "approvals",
    "contracts",
    "financing",
    "dashboard",
    "sales",
    "portal",
    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.tengasale_support",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

TENGASALE_WHATSAPP_NUMBER = os.environ.get("TENGASALE_WHATSAPP_NUMBER", "+265883596135")
TENGASALE_WHATSAPP_LINK = f"https://wa.me/{''.join(char for char in TENGASALE_WHATSAPP_NUMBER if char.isdigit())}"

TRUSTONIC_API_KEY = os.environ.get("TRUSTONIC_API_KEY", "")
TRUSTONIC_API_URL = os.environ.get("TRUSTONIC_API_URL", "")
UPYA_API_KEY = os.environ.get("UPYA_API_KEY", "")
UPYA_API_URL = os.environ.get("UPYA_API_URL", "")
PAYMENT_PROVIDER_API_KEY = os.environ.get("PAYMENT_PROVIDER_API_KEY", "")
PAYMENT_PROVIDER_API_URL = os.environ.get("PAYMENT_PROVIDER_API_URL", "")
SMS_PROVIDER_API_KEY = os.environ.get("SMS_PROVIDER_API_KEY", "")
SMS_PROVIDER_API_URL = os.environ.get("SMS_PROVIDER_API_URL", "")

# Payment providers
MOCK_PAYMENTS = os.environ.get("MOCK_PAYMENTS", "true").lower() == "true"
PAYCHANGU_PUBLIC_KEY = os.environ.get("PAYCHANGU_PUBLIC_KEY", "")
PAYCHANGU_SECRET_KEY = os.environ.get("PAYCHANGU_SECRET_KEY", "")
PAYCHANGU_WEBHOOK_SECRET = os.environ.get("PAYCHANGU_WEBHOOK_SECRET", "")
AIRTEL_MONEY_CLIENT_ID = os.environ.get("AIRTEL_MONEY_CLIENT_ID", "")
AIRTEL_MONEY_CLIENT_SECRET = os.environ.get("AIRTEL_MONEY_CLIENT_SECRET", "")
TNM_MPAMBA_API_KEY = os.environ.get("TNM_MPAMBA_API_KEY", "")
PAYTRIGGER_API_KEY = os.environ.get("PAYTRIGGER_API_KEY", "")

# Device locking integration flags
MOCK_DEVICE_LOCKING = os.environ.get("MOCK_DEVICE_LOCKING", "true").lower() == "true"
ENABLE_KNOX = os.environ.get("ENABLE_KNOX", "false").lower() == "true"
ENABLE_NUOVOPAY = os.environ.get("ENABLE_NUOVOPAY", "false").lower() == "true"
ENABLE_UPYA = os.environ.get("ENABLE_UPYA", "false").lower() == "true"
ENABLE_PAYTRIGGER = os.environ.get("ENABLE_PAYTRIGGER", "false").lower() == "true"
ENABLE_PAYCHANGU = os.environ.get("ENABLE_PAYCHANGU", "false").lower() == "true"

# Knox MDM
KNOX_API_KEY = os.environ.get("KNOX_API_KEY", "")
KNOX_API_URL = os.environ.get("KNOX_API_URL", "https://api.samsungknox.com")

# NuovoPay MDM
NUOVOPAY_API_KEY = os.environ.get("NUOVOPAY_API_KEY", "")
NUOVOPAY_API_URL = os.environ.get("NUOVOPAY_API_URL", "https://api.nuovopay.com")

# File upload security
MAX_UPLOAD_SIZE_MB = int(os.environ.get("MAX_UPLOAD_SIZE_MB", "5"))
ALLOWED_KYC_MIME_TYPES = ["image/jpeg", "image/png", "image/webp", "application/pdf"]

APP_VERSION = "1.0.0"

if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
