# Generated by Django 5.2.5 on 2025-09-06 19:38

import django.db.models.deletion
import wallet.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('NB', 'National Bank (future)'), ('SB', 'Standard Bank (future)'), ('AM', 'Airtel Money (future)'), ('MANUAL', 'Manual')], default='MANUAL', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('txn_ref', models.CharField(blank=True, default='', max_length=48)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('day_of_month', models.PositiveSmallIntegerField(default=28)),
                ('at_hour', models.PositiveSmallIntegerField(default=9)),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ('-issued_at',)},
        ),
        migrations.AddField(
            model_name='payslip',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=wallet.models._default_base_salary, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bonuses_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='email_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='payslip',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payslip',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=24),
        ),
        migrations.AddField(
            model_name='payslip',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='DRAFT', max_length=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['agent', 'year', 'month'], name='wallet_pays_agent_i_731d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['status'], name='wallet_pays_status_a64291_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallet.payslip'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='payout_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='wallet_paym_status_bc3734_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='wallet_paym_method_055c56_idx'),
        ),
    ]
