# Generated by Django 5.2.5 on 2025-09-07 09:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_orderprice'),
        ('wallet', '0002_payment_payoutschedule_alter_payslip_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('supplier_phone', models.CharField(blank=True, max_length=40)),
                ('agent_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='MWK', max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_pos_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdminPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wallet.adminpurchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='adminpurchaseorder',
            index=models.Index(fields=['status', 'created_at'], name='wallet_admi_status_a0eb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpurchaseorder',
            index=models.Index(fields=['supplier_name'], name='wallet_admi_supplie_1c27ec_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpurchaseorderitem',
            index=models.Index(fields=['po'], name='wallet_admi_po_id_2488b2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpurchaseorderitem',
            index=models.Index(fields=['product'], name='wallet_admi_product_67d6b5_idx'),
        ),
    ]
