# Generated by Django 4.2.24 on 2025-09-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_adminpurchaseorder_adminpurchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['agent', 'status', 'created_at'], name='wallet_budg_agent_i_ff1536_idx'),
        ),
    ]
