# Generated by Django 4.2.23 on 2025-10-10 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_budgetrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
