# Generated by Django 5.2.5 on 2025-12-03 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        ("wallet", "0005_alter_wallettransaction_effective_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="business",
            field=models.ForeignKey(
                blank=True,
                help_text="Business this transaction belongs to (for company costs/revenue)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_transactions",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="effective_from",
            field=models.DateField(
                blank=True,
                help_text="When recurring costs start being applied (relevant for recurring costs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="is_recurring",
            field=models.BooleanField(
                default=False, help_text="If True, this cost recurs monthly"
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="recurrence",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly")],
                default="monthly",
                help_text="Recurrence pattern (only used if is_recurring=True)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("commission", "Commission"),
                    ("bonus", "Bonus"),
                    ("deduction", "Deduction"),
                    ("advance", "Advance (Cash out)"),
                    ("penalty", "Penalty"),
                    ("payslip", "Payslip Payment"),
                    ("adjustment", "Manual Adjustment"),
                    ("budget", "Budget Payout/Recovery"),
                    ("cost_once_off", "Cost (Once-off)"),
                    ("cost_recurring", "Cost (Recurring)"),
                    ("revenue", "Revenue"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["business", "type", "effective_date"],
                name="wallet_wall_busines_2dc8de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["business", "is_recurring", "effective_from"],
                name="wallet_wall_busines_a68802_idx",
            ),
        ),
    ]
