# Generated by Django 5.2.5 on 2026-05-10 08:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0034_alter_business_business_kind"),
        ("wallet", "0006_wallettransaction_business_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashBankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("cash_in", "Cash In"), ("cash_out", "Cash Out")],
                        max_length=12,
                    ),
                ),
                ("category", models.CharField(max_length=80)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("airtel_money", "Airtel Money"),
                            ("mpamba", "Mpamba"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "related_sale_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-date", "-id"),
            },
        ),
        migrations.AddField(
            model_name="adminpurchaseorder",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_purchase_orders",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="adminpurchaseorder",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminpurchaseorder",
            name="payment_terms",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="adminpurchaseorder",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="purchase_orders/"),
        ),
        migrations.AddIndex(
            model_name="adminpurchaseorder",
            index=models.Index(
                fields=["business", "created_at"], name="wallet_admi_busines_9ebf16_idx"
            ),
        ),
        migrations.AddField(
            model_name="cashbanktransaction",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_bank_transactions",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="cashbanktransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_bank_transactions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cashbanktransaction",
            index=models.Index(
                fields=["business", "date"], name="wallet_cash_busines_5ba4fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashbanktransaction",
            index=models.Index(
                fields=["business", "payment_method", "date"],
                name="wallet_cash_busines_0da5b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashbanktransaction",
            index=models.Index(
                fields=["business", "direction", "date"],
                name="wallet_cash_busines_dff882_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashbanktransaction",
            index=models.Index(
                fields=["business", "category", "date"],
                name="wallet_cash_busines_8aae30_idx",
            ),
        ),
    ]
