# Generated by Django 5.2.5 on 2026-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_payslip_business_payslip_employee_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Prepared"),
                    ("sent", "Sent"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Prepared"),
                    ("SENT", "Issued"),
                    ("PAID", "Paid"),
                    ("FAILED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=12,
            ),
        ),
    ]
