# Generated by Django 5.2.5 on 2026-01-02 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_price_audit_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="priceadjustment",
            new_name="audit_price_sale_id_f046a3_idx",
            old_name="audit_price_sale_ad_idx",
        ),
        migrations.RenameIndex(
            model_name="priceadjustment",
            new_name="audit_price_busines_7c9315_idx",
            old_name="audit_price_busines_idx",
        ),
        migrations.RenameIndex(
            model_name="priceadjustment",
            new_name="audit_price_adjuste_d339a4_idx",
            old_name="audit_price_adjuste_idx",
        ),
        migrations.RenameIndex(
            model_name="unsoldpriceedit",
            new_name="audit_unsol_item_id_94b797_idx",
            old_name="audit_unsol_item_ed_idx",
        ),
        migrations.RenameIndex(
            model_name="unsoldpriceedit",
            new_name="audit_unsol_busines_e48df1_idx",
            old_name="audit_unsol_busines_idx",
        ),
        migrations.RenameIndex(
            model_name="unsoldpriceedit",
            new_name="audit_unsol_edited__895159_idx",
            old_name="audit_unsol_edited__idx",
        ),
    ]
