# Generated by Django 6.0.5 on 2026-05-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0008_financingapplication_review_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnderwriterReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_clear", models.BooleanField(blank=True, null=True)),
                (
                    "identity_signature_matches",
                    models.BooleanField(blank=True, null=True),
                ),
                ("identity_info_matches", models.BooleanField(blank=True, null=True)),
                ("momo_name_matches", models.BooleanField(blank=True, null=True)),
                ("customer_spoken", models.BooleanField(blank=True, null=True)),
                ("customer_intro_done", models.BooleanField(blank=True, null=True)),
                (
                    "customer_confirmed_application",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "customer_confirmed_device",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "customer_confirmed_deposit",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "customer_confirmed_repayment",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "customer_understands_direct_payment",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "customer_understands_nonpayment",
                    models.BooleanField(blank=True, null=True),
                ),
                ("income_understood", models.BooleanField(blank=True, null=True)),
                ("income_contact_spoken", models.BooleanField(blank=True, null=True)),
                ("income_confirmed", models.BooleanField(blank=True, null=True)),
                (
                    "income_source_dependable",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "income_contact_confident",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "location_neighbour_spoken",
                    models.BooleanField(blank=True, null=True),
                ),
                ("location_confirmed", models.BooleanField(blank=True, null=True)),
                ("location_traceable", models.BooleanField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="underwriter_review",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "underwriter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
