# Generated by Django 6.0.5 on 2026-05-28 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_applicationfieldreview"),
        ("approvals", "0002_callevidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("identity", "Identity Check"),
                            ("address", "Address Check"),
                            ("customer_call", "Customer Call"),
                            ("guarantor_call", "Guarantor Call"),
                            ("employer_call", "Employer / Income Call"),
                            ("income", "Income Check"),
                            ("final_review", "Final Review"),
                        ],
                        max_length=30,
                    ),
                ),
                ("question_key", models.CharField(max_length=80, unique=True)),
                ("question_text", models.TextField()),
                ("help_text", models.TextField(blank=True)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes / No"),
                            ("text", "Text"),
                            ("number", "Number"),
                            ("choice", "Choice"),
                            ("file", "File"),
                            ("audio", "Audio"),
                        ],
                        default="yes_no",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("risk_weight", models.PositiveIntegerField(default=1)),
                (
                    "fail_if_no",
                    models.BooleanField(
                        default=False,
                        help_text="If True, a 'No' answer flags this as a risk factor",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Review Question",
                "verbose_name_plural": "Review Questions",
                "ordering": ["stage", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_value", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_answers_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_answers",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_answers",
                        to="approvals.underwriterreview",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="approvals.reviewquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Answer",
                "verbose_name_plural": "Review Answers",
                "ordering": ["question__order"],
                "unique_together": {("review", "question")},
            },
        ),
    ]
