# Generated by Django 6.0.5 on 2026-05-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "ordering": ["region__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TraditionalAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traditional_authorities",
                        to="geography.district",
                    ),
                ),
            ],
            options={
                "ordering": ["district__region__name", "district__name", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("region", "name"), name="unique_district_per_region"
            ),
        ),
        migrations.AddConstraint(
            model_name="traditionalauthority",
            constraint=models.UniqueConstraint(
                fields=("district", "name"), name="unique_ta_per_district"
            ),
        ),
    ]
