# Generated by Django 6.0.5 on 2026-05-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0002_alter_merchantlead_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spoke_to_owner",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Did you speak to the owner?",
                    ),
                ),
                (
                    "shop_physically_traceable",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Is the shop physically traceable?",
                    ),
                ),
                (
                    "documents_verified",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Were documents verified?"
                    ),
                ),
                (
                    "bank_name_matches",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Does bank/mobile money name match owner/shop?",
                    ),
                ),
                (
                    "understands_settlement",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Does merchant understand TengaSale settlement rules?",
                    ),
                ),
                (
                    "understands_no_wht",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Does merchant understand no WHT applies to merchant payouts?",
                    ),
                ),
                (
                    "understands_fraud_consequences",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Does merchant understand fraud consequences?",
                    ),
                ),
                (
                    "approved_for_pilot",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Is merchant approved for pilot?",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approve", "Recommend Approval"),
                            ("reject", "Recommend Rejection"),
                            ("escalate", "Escalate to HQ"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("site_visit_completed", models.BooleanField(default=False)),
                ("site_visit_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="website.merchantlead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Checklist",
                "verbose_name_plural": "Merchant Checklists",
            },
        ),
        migrations.CreateModel(
            name="MerchantKYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_id_number", models.CharField(blank=True, max_length=50)),
                ("business_reg_number", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("physical_address", models.TextField(blank=True)),
                ("trading_area", models.CharField(blank=True, max_length=200)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=200)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("airtel_money_number", models.CharField(blank=True, max_length=30)),
                ("tnm_mpamba_number", models.CharField(blank=True, max_length=30)),
                (
                    "business_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="merchant_docs/certs/"
                    ),
                ),
                (
                    "tax_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="merchant_docs/tax/"
                    ),
                ),
                (
                    "shop_photo_1",
                    models.ImageField(
                        blank=True, null=True, upload_to="merchant_docs/photos/"
                    ),
                ),
                (
                    "shop_photo_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="merchant_docs/photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_kyc_collected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="website.merchantlead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant KYC",
                "verbose_name_plural": "Merchant KYC Records",
            },
        ),
    ]
