# Generated by Django 4.2.23 on 2025-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginsecurity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginsecurity',
            table='accounts_loginsecurity',
        ),
        migrations.AlterModelTable(
            name='passwordresetcode',
            table='accounts_passwordresetcode',
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(db_index=True, default='login', max_length=32)),
                ('code_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'accounts_emailotp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'expires_at'], name='accounts_em_email_d5111a_idx'), models.Index(fields=['email', 'purpose', 'consumed_at'], name='accounts_em_email_0204e8_idx')],
            },
        ),
    ]
