# Generated by Django 4.2.23 on 2025-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_country_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_manager'], name='accounts_pr_is_mana_e87dfc_idx'),
        ),
    ]
