# Generated by Django 4.2.23 on 2025-09-21 08:07

import circuitcity.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=circuitcity.accounts.models.avatar_upload_to),
        ),
    ]
