# Generated by Django 5.2.5 on 2025-12-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="force_password_change",
            field=models.BooleanField(
                default=False,
                help_text="If True, user must change password on next login.",
            ),
        ),
    ]
