# Generated by Django 5.2.5 on 2025-12-02 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_force_password_change"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_stop_theft",
                    models.BooleanField(
                        default=False, help_text="Stop theft and missing stock"
                    ),
                ),
                (
                    "goal_see_profit",
                    models.BooleanField(
                        default=False, help_text="See profit and losses clearly"
                    ),
                ),
                (
                    "goal_track_performance",
                    models.BooleanField(
                        default=False, help_text="Track agent performance and rankings"
                    ),
                ),
                (
                    "goal_move_off_notebooks",
                    models.BooleanField(
                        default=False, help_text="Move off hardcover notebooks"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wizard_version",
                    models.CharField(
                        default="v1",
                        help_text="Wizard version for A/B testing",
                        max_length=20,
                    ),
                ),
                (
                    "first_business_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "first_location_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "chosen_vertical",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_onboarding_profile",
                "indexes": [
                    models.Index(
                        fields=["user"], name="accounts_on_user_id_daaf43_idx"
                    ),
                    models.Index(
                        fields=["completed_at"], name="accounts_on_complet_a1f91b_idx"
                    ),
                ],
            },
        ),
    ]
