# Generated by Django 5.2.5 on 2025-12-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_emailotp_index_database(apps, schema_editor):
    """Drop emailotp index using idempotent SQL. Safe to run even if index doesn't exist."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor in ("postgresql", "sqlite"):
            cursor.execute("DROP INDEX IF EXISTS accounts_em_email_d5111a_idx")


def reverse_drop_emailotp_index_database(apps, schema_editor):
    """Reverse: no-op (index is being removed)"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_onboardingprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_emailotp_index_database,
                    reverse_drop_emailotp_index_database,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="emailotp",
                    name="accounts_em_email_d5111a_idx",
                ),
            ],
        ),
        migrations.AddField(
            model_name="emailotp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional user reference (for signup, user may not exist yet)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="user_agent",
            field=models.TextField(blank=True, help_text="User agent string", null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="If True, user's email address has been verified via OTP.",
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="attempts",
            field=models.PositiveIntegerField(default=0, help_text="Number of verification attempts"),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="code_hash",
            field=models.CharField(help_text="Hashed OTP code (never store plaintext)", max_length=256),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(db_index=True, help_text="Normalized lowercase email", max_length=254),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup"),
                    ("login", "Login"),
                    ("reset", "Password Reset"),
                    ("2fa", "Two-Factor Authentication"),
                ],
                db_index=True,
                default="login",
                help_text="Purpose of this OTP (signup, login, reset, 2fa)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="requester_ip",
            field=models.GenericIPAddressField(blank=True, help_text="IP address of requester", null=True),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "purpose", "-created_at"],
                name="accounts_em_email_814cb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["user", "purpose", "-created_at"],
                name="accounts_em_user_id_dc4b02_idx",
            ),
        ),
    ]
