# Generated by Django 5.2.5 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_email_verified_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_currency",
            field=models.CharField(
                max_length=3,
                choices=[("MWK", "MWK"), ("USD", "USD")],
                default="MWK",
                help_text="Currency to display amounts in (MWK is base currency, USD is converted)",
                db_index=True,
            ),
        ),
    ]

