# Generated by Django 5.2.5 on 2025-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_profile_display_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_currency",
            field=models.CharField(
                choices=[("MWK", "MWK"), ("USD", "USD")],
                default="MWK",
                help_text="Currency to display amounts in (MWK is base currency, USD is converted)",
                max_length=3,
            ),
        ),
    ]
