# Generated by Django 5.2.5 on 2025-12-27 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_profile_display_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_email_0204e8_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_email_814cb4_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_user_id_dc4b02_idx",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="meta",
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="code_hash",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="consumed_at",
            field=models.DateTimeField(blank=True, help_text="When OTP was successfully used", null=True),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Email address (normalized lowercase)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup"),
                    ("login", "Login"),
                    ("reset", "Password Reset"),
                    ("2fa", "Two-Factor Authentication"),
                    ("verify_email", "Verify Email"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="requester_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User if account exists (null for signup)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "purpose", "created_at"],
                name="accounts_em_email_377460_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["user", "purpose", "created_at"],
                name="accounts_em_user_id_bcbb30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="accounts_em_expires_4bccd7_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="emailotp",
            table="accounts_email_otp",
        ),
    ]
