# Generated by Django 5.2.5 on 2025-12-27 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_emailotp_table_if_needed(apps, schema_editor):
    """
    Conditionally rename emailotp table to accounts_emailotp.
    Safe across environments: only renames if emailotp exists and accounts_emailotp does not exist.
    """
    connection = schema_editor.connection
    introspection = connection.introspection
    table_names = introspection.table_names()

    # Source table name (what might exist)
    source_table = "emailotp"
    # Target table name (what we want)
    target_table = "accounts_emailotp"

    # Normalize table names for case-insensitive comparison
    table_names_lower = [t.lower() for t in table_names]

    # Only rename if source exists AND target does not exist
    if source_table.lower() in table_names_lower and target_table.lower() not in table_names_lower:
        quoted_source = schema_editor.quote_name(source_table)
        quoted_target = schema_editor.quote_name(target_table)
        with connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE {quoted_source} RENAME TO {quoted_target}")


def reverse_rename_emailotp_table(apps, schema_editor):
    """
    Reverse: rename accounts_emailotp back to emailotp if needed.
    """
    connection = schema_editor.connection
    introspection = connection.introspection
    table_names = introspection.table_names()

    source_table = "accounts_emailotp"
    target_table = "emailotp"

    if source_table.lower() in [t.lower() for t in table_names]:
        if target_table.lower() not in [t.lower() for t in table_names]:
            quoted_source = schema_editor.quote_name(source_table)
            quoted_target = schema_editor.quote_name(target_table)
            with connection.cursor() as cursor:
                cursor.execute(f"ALTER TABLE {quoted_source} RENAME TO {quoted_target}")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_emailotp_accounts_em_email_0204e8_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_email_377460_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_user_id_bcbb30_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_expires_4bccd7_idx",
        ),
        migrations.AddField(
            model_name="emailotp",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="code_hash",
            field=models.CharField(help_text="Hashed OTP code (never store plaintext)", max_length=256),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(db_index=True, help_text="Normalized lowercase email", max_length=254),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup"),
                    ("login", "Login"),
                    ("reset", "Password Reset"),
                    ("2fa", "Two-Factor Authentication"),
                ],
                db_index=True,
                default="login",
                help_text="Purpose of this OTP (signup, login, reset, 2fa)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="requester_ip",
            field=models.GenericIPAddressField(blank=True, help_text="IP address of requester", null=True),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional user reference (for signup, user may not exist yet)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="user_agent",
            field=models.TextField(blank=True, help_text="User agent string", null=True),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "purpose", "-created_at"],
                name="accounts_em_email_814cb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "purpose", "consumed_at"],
                name="accounts_em_email_0204e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["user", "purpose", "-created_at"],
                name="accounts_em_user_id_dc4b02_idx",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_emailotp_table_if_needed,
                    reverse_rename_emailotp_table,
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="emailotp",
                    table="accounts_emailotp",
                ),
            ],
        ),
    ]
