# Generated by Django 5.2.5 on 2025-12-31 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_fix_emailotp_table_name_variants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTwoFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether SMS 2FA is enabled for this user",
                    ),
                ),
                (
                    "phone_e164",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phone number in E.164 format (e.g. +265991234567)",
                        max_length=32,
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the phone number was last verified",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twofactor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_usertwofa",
                "indexes": [
                    models.Index(
                        fields=["user"], name="accounts_us_user_id_551f65_idx"
                    ),
                    models.Index(
                        fields=["sms_enabled"], name="accounts_us_sms_ena_076d28_idx"
                    ),
                ],
            },
        ),
    ]
