# Generated by Django 5.2.5 on 2026-01-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_add_usertwofa"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, default="Lilongwe", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, default="Malawi", max_length=80),
        ),
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(blank=True, default="English", max_length=80),
        ),
    ]
