# Generated by Django 5.2.5 on 2026-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_ensure_profile_city_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True,
                default="MW",
                help_text="ISO-2 country code (e.g. MW for Malawi, ZM for Zambia).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_currency",
            field=models.CharField(
                default="MWK",
                help_text="Preferred display currency (ISO 4217 code, e.g. MWK, USD).",
                max_length=5,
            ),
        ),
    ]
