# Generated by Django 5.2.5 on 2026-04-28 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0034_alter_business_business_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("iot", "IoT Monitoring"),
                            ("mobile_money", "Mobile Money"),
                            ("credit", "Credit / Lending"),
                            ("pos", "Point of Sale"),
                            ("accounting", "Accounting"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                (
                    "api_key_hint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Last 8 chars of token for UI display only — never the full key",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="developer_integrations",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer Integration",
                "verbose_name_plural": "Developer Integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="External customer identifier (e.g. CUST-001, phone number)",
                        max_length=200,
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=200)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("repayment", "Repayment"),
                            ("missed_payment", "Missed Payment"),
                            ("partial_payment", "Partial Payment"),
                            ("stock_turnover", "Stock Turnover"),
                            ("sales_velocity", "Sales Velocity"),
                            ("mobile_money_activity", "Mobile Money Activity"),
                            ("asset_usage", "Asset Usage"),
                            ("manual_adjustment", "Manual Adjustment"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "score_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional numeric impact on credit score (positive = good, negative = bad)",
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_signals",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Signal",
                "verbose_name_plural": "Credit Signals",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_ref", "-occurred_at"],
                        name="integration_custome_57946d_idx",
                    ),
                    models.Index(
                        fields=["signal_type", "-occurred_at"],
                        name="integration_signal__37fc73_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=200)),
                (
                    "event_type",
                    models.CharField(db_index=True, default="generic", max_length=100),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="tenants.business",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="integrations.developerintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-received_at"],
                        name="integration_source_57b528_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-received_at"],
                        name="integration_event_t_a99cb7_idx",
                    ),
                ],
            },
        ),
    ]
