# Generated by Django 6.0.5 on 2026-05-25 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="agreed_to_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_daily_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_monthly_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_total_loan",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="correction_customer_phone_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="correction_id_back_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="correction_id_front_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="correction_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="customer_phone_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="kyc/customer_phone/"
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="district",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="exact_monthly_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="id_back_image",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/id_back/"),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="id_front_image",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/id_front/"),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="income_band",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="map_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="locations/maps/"),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="next_of_kin_1_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="next_of_kin_1_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Enter exactly 9 digits."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="next_of_kin_1_relationship",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="next_of_kin_2_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="next_of_kin_2_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Enter exactly 9 digits."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="next_of_kin_2_relationship",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="occupation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="precise_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="proof_contact_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="proof_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Enter exactly 9 digits."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="proof_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="proof_of_income_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="region",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="selected_cash_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="selected_deposit_percent",
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="traditional_authority",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="work_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Enter exactly 9 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{8}$",
                        "National ID must be exactly 8 letters or numbers.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Start"),
                    ("customer_details", "Customer Details"),
                    ("device_selection", "Device Selection"),
                    ("kyc_capture", "KYC Capture"),
                    ("location_details", "Location Details"),
                    ("work_details", "Work Details"),
                    ("signature", "Signature"),
                    ("correction_requested", "Correction Requested"),
                    ("imei_required", "IMEI Required"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="started",
                max_length=40,
            ),
        ),
    ]
