# Generated by Django 6.0.5 on 2026-05-25 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_financingapplication_agreed_to_terms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financingapplication",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Phone number must be exactly 9 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{8}$",
                        "National ID must be exactly 8 letters or numbers.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="next_of_kin_1_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Phone number must be exactly 9 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="next_of_kin_2_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Phone number must be exactly 9 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="proof_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "Phone number must be exactly 9 digits."
                    )
                ],
            ),
        ),
    ]
