# Generated by Django 6.0.5 on 2026-05-25 20:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_financingapplication_customer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_3_month_daily",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_3_month_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_3_month_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_6_month_daily",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_6_month_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="calculated_6_month_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="selected_loan_multiplier",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2.5"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="selected_deposit_percent",
            field=models.DecimalField(decimal_places=2, default=13, max_digits=5),
        ),
    ]
