# Generated by Django 6.0.5 on 2026-05-25 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_rename_customer_phone_kyc_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="correction_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("started", "Start"),
                    ("customer_details", "Customer Details"),
                    ("device_selection", "Device Selection"),
                    ("kyc", "KYC"),
                    ("kyc_capture", "KYC Capture"),
                    ("location", "Location"),
                    ("location_details", "Location Details"),
                    ("work", "Work"),
                    ("work_details", "Work Details"),
                    ("signature", "Signature"),
                    ("submitted", "Submitted"),
                    ("pending_review", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("correction_requested", "Correction Requested"),
                    ("resubmitted", "Resubmitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("contract_terms", "Contract Terms"),
                    ("contract_signature", "Contract Signature"),
                    ("imei_entry", "IMEI Entry"),
                    ("contract_creating", "Contract Creating"),
                    ("warranty_check", "Warranty Check"),
                    ("locking", "Locking"),
                    ("deposit_pending", "Deposit Pending"),
                    ("contract_complete", "Contract Complete"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("imei_required", "IMEI Required"),
                ],
                default="started",
                max_length=40,
            ),
        ),
    ]
