# Generated by Django 6.0.5 on 2026-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_financingapplication_correction_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="address_check_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="correction_customer_phone_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="customer_phone_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="kyc/customer_phone/"
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="gps_coordinates",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="income_check_answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="proof_income_file",
            field=models.FileField(blank=True, null=True, upload_to="proof_income/"),
        ),
    ]
