# Generated by Django 6.0.5 on 2026-05-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_financingapplication_address_check_answers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="review_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="financingapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("started", "Start"),
                    ("customer_details", "Customer Details"),
                    ("device_selection", "Device Selection"),
                    ("kyc", "KYC"),
                    ("kyc_capture", "KYC Capture"),
                    ("location", "Location"),
                    ("location_details", "Location Details"),
                    ("work", "Work"),
                    ("work_details", "Work Details"),
                    ("signature", "Signature"),
                    ("submitted", "Submitted"),
                    ("pending_review", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("correction_requested", "Correction Requested"),
                    ("sent_back", "Sent Back"),
                    ("resubmitted", "Resubmitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("contract_terms", "Contract Terms"),
                    ("contract_signature", "Contract Signature"),
                    ("imei_entry", "IMEI Entry"),
                    ("contract_creating", "Contract Creating"),
                    ("warranty_check", "Warranty Check"),
                    ("locking", "Locking"),
                    ("deposit_pending", "Deposit Pending"),
                    ("contract_complete", "Contract Complete"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("imei_required", "IMEI Required"),
                ],
                default="started",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=120)),
                ("section", models.CharField(blank=True, max_length=120)),
                ("label", models.CharField(max_length=180)),
                ("note", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["application", "resolved"],
                        name="application_applica_216528_idx",
                    ),
                    models.Index(
                        fields=["field_name"], name="application_field_n_941c02_idx"
                    ),
                ],
            },
        ),
    ]
