# Generated by Django 6.0.5 on 2026-05-26 16:23

from django.db import migrations, models


def normalize_review_status(apps, schema_editor):
    FinancingApplication = apps.get_model("applications", "FinancingApplication")
    FinancingApplication.objects.filter(status="pending_review", review_status="").update(
        review_status="pending_review"
    )
    FinancingApplication.objects.filter(status="approved", review_status="").update(
        review_status="approved"
    )
    FinancingApplication.objects.filter(status="rejected", review_status="").update(
        review_status="rejected"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_financingapplication_review_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financingapplication",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not reviewed"),
                    ("pending_review", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("sent_back", "Sent Back"),
                    ("resubmitted", "Resubmitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="",
                max_length=40,
            ),
        ),
        migrations.RunPython(normalize_review_status, migrations.RunPython.noop),
    ]
