# Generated by Django 6.0.5 on 2026-05-28 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_applicationcorrectiontoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationFieldReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.CharField(max_length=80)),
                ("field_label", models.CharField(max_length=180)),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("income", "Income"),
                            ("contacts", "Contacts"),
                            ("location", "Location"),
                            ("documents", "Documents"),
                        ],
                        max_length=30,
                    ),
                ),
                ("current_value_snapshot", models.TextField(blank=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("incorrect_information", "Incorrect information"),
                            ("missing_information", "Missing information"),
                            ("unclear_document", "Unclear document"),
                            (
                                "needs_customer_confirmation",
                                "Needs customer confirmation",
                            ),
                            ("needs_updated_proof", "Needs updated proof"),
                            ("other", "Other"),
                        ],
                        default="incorrect_information",
                        max_length=40,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("marked", "Needs Review"),
                            ("customer_updated", "Customer Updated"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="marked",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_reviews",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_reviews_marked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Field Review",
                "verbose_name_plural": "Application Field Reviews",
                "ordering": ["section", "field_key"],
                "indexes": [
                    models.Index(
                        fields=["application", "status"],
                        name="application_applica_203401_idx",
                    ),
                    models.Index(
                        fields=["field_key"], name="application_field_k_55880c_idx"
                    ),
                ],
            },
        ),
    ]
