# Generated by Django 6.0.5 on 2026-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_applicationfieldreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingapplication",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="device_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select purpose"),
                    ("personal", "Personal use"),
                    ("business", "Business use"),
                    ("school", "School / education"),
                    ("family_use", "Family use"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select gender"),
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Prefer not to say"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="household_income_contributors",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select marital status"),
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="num_dependents",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="phone_user",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select who will use the phone"),
                    ("customer_self", "The customer themselves"),
                    ("spouse", "Spouse"),
                    ("child", "Child"),
                    ("parent", "Parent"),
                    ("family_member", "Other family member"),
                    ("friend", "Friend"),
                    ("business_employee", "Business employee"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="phone_user_other",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="rent_or_own_home",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("rent", "Renting"),
                    ("own", "Owned home"),
                    ("family_home", "Family/parental home"),
                    ("employer_provided", "Employer-provided"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="financingapplication",
            name="third_party_phone_user_risk_flagged",
            field=models.BooleanField(
                default=False,
                help_text="Auto-flagged when phone will be used by someone other than the applicant",
            ),
        ),
    ]
