# Generated by Django 5.2.5 on 2026-02-05 13:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0031_car_hire_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        db_index=True,
                        help_text="Vertical slug (phones, clothing, gym, liquor, etc.)",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PREVIEW", "Previewed"),
                            ("APPLIED", "Applied"),
                            ("ROLLED_BACK", "Rolled Back"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.TextField(
                        help_text="Required: Why are these corrections needed?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this batch",
                    ),
                ),
                (
                    "items_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of correction items in this batch",
                    ),
                ),
                (
                    "items_applied",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of items successfully applied"
                    ),
                ),
                (
                    "items_failed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of items that failed to apply"
                    ),
                ),
                (
                    "revenue_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue impact of this batch",
                        max_digits=12,
                    ),
                ),
                (
                    "profit_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total profit impact of this batch",
                        max_digits=12,
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who applied this batch",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_correction_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business where corrections are being made",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_batches",
                        to="tenants.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Manager who created this batch",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_correction_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rolled_back_correction_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Correction Batch",
                "verbose_name_plural": "Correction Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorrectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_label",
                    models.CharField(
                        db_index=True,
                        help_text='Entity label from vertical adapter (e.g., "sale", "accessory", "member")',
                        max_length=100,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text='Full model name (e.g., "inventory.InventoryItem")',
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        db_index=True, help_text="ID of the object being corrected"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text='Field being corrected (e.g., "selling_price")',
                        max_length=100,
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(help_text="Original value (JSON-serialized)"),
                ),
                (
                    "new_value",
                    models.JSONField(help_text="New value (JSON-serialized)"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this correction was applied (null if not yet applied)",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if application failed",
                        null=True,
                    ),
                ),
                (
                    "revenue_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Revenue impact of this correction (null if not applicable)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "profit_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Profit impact of this correction (null if not applicable)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="corrections.correctionbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correction Item",
                "verbose_name_plural": "Correction Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CorrectionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text='Action performed (e.g., "batch_created", "batch_applied", "item_applied")',
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Additional details about this action (JSON)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_audit_logs",
                        to="tenants.business",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="corrections.correctionbatch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="corrections.correctionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correction Audit Log",
                "verbose_name_plural": "Correction Audit Logs",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="correctionbatch",
            index=models.Index(
                fields=["business", "vertical", "-created_at"],
                name="corrections_busines_268c63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correctionbatch",
            index=models.Index(
                fields=["status", "-created_at"], name="corrections_status_15932e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correctionbatch",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="corrections_created_6e6c1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correctionitem",
            index=models.Index(
                fields=["batch", "entity_label"], name="corrections_batch_i_03791f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correctionitem",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="corrections_model_n_7700e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correctionitem",
            index=models.Index(
                fields=["applied_at"], name="corrections_applied_aa083a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correctionauditlog",
            index=models.Index(
                fields=["business", "-performed_at"],
                name="corrections_busines_da9535_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correctionauditlog",
            index=models.Index(
                fields=["batch", "-performed_at"], name="corrections_batch_i_43f3b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correctionauditlog",
            index=models.Index(
                fields=["action", "-performed_at"], name="corrections_action_d94960_idx"
            ),
        ),
    ]
