# Generated by Django 6.0.5 on 2026-05-25 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0006_financingapplication_correction_fields_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=9, unique=True),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("deal_name", models.CharField(blank=True, max_length=200)),
                ("imei_number", models.CharField(blank=True, max_length=15)),
                (
                    "cash_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_loan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "daily_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("terms_accepted_by_merchant", models.BooleanField(default=False)),
                (
                    "customer_contract_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="contract_signatures/"
                    ),
                ),
                ("customer_terms_accepted", models.BooleanField(default=False)),
                ("warranty_checked", models.BooleanField(default=False)),
                ("phone_locked", models.BooleanField(default=False)),
                ("deposit_paid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("terms_accepted", "Terms Accepted"),
                            ("signed", "Signed"),
                            ("imei_entered", "IMEI Entered"),
                            ("contract_created", "Contract Created"),
                            ("warranty_checked", "Warranty Checked"),
                            ("locking", "Locking"),
                            ("locked", "Locked"),
                            ("deposit_pending", "Deposit Pending"),
                            ("complete", "Complete"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="applications.financingapplication",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
