# Generated by Django 5.2.5 on 2025-12-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="International format (e.g. +265888123456)",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch for all WhatsApp notifications",
                    ),
                ),
                (
                    "receive_sale_alerts",
                    models.BooleanField(
                        default=True, help_text="Notify on sales (for managers)"
                    ),
                ),
                (
                    "receive_profit_milestones",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when profit milestones are reached (for managers)",
                    ),
                ),
                (
                    "receive_low_stock_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when stock is low (for managers)",
                    ),
                ),
                (
                    "receive_commission_alerts",
                    models.BooleanField(
                        default=False,
                        help_text="Notify on commission earnings (for agents)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Preference",
                "verbose_name_plural": "WhatsApp Preferences",
                "indexes": [
                    models.Index(
                        fields=["user", "is_enabled"],
                        name="notificatio_user_id_09ff89_idx",
                    )
                ],
            },
        ),
    ]
