# Generated by Django 5.2.5 on 2025-12-05 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_whatsapppreference"),
        ("tenants", "0012_add_business_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="business",
            field=models.ForeignKey(
                blank=True,
                help_text="Business this notification belongs to (for multi-tenant support)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tenants.business",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("payslip_reminder", "Payslip Reminder"),
                    ("commission", "Commission"),
                    ("stock", "Stock"),
                    ("sale", "Sale"),
                    ("system", "System"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["business", "category", "created_at"],
                name="notificatio_busines_79da94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "category", "read_at"],
                name="notificatio_user_id_b2ea19_idx",
            ),
        ),
    ]
