# Generated by Django 5.2.5 on 2025-12-27 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_category_and_business"),
        ("tenants", "0019_add_section_flags_with_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WELCOME_MANAGER", "Welcome Manager"),
                            ("WELCOME_AGENT", "Welcome Agent"),
                            ("OTP_CODE", "OTP Code"),
                            ("SALE_INSTANT", "Sale Instant"),
                            ("SALE_BATCH", "Sale Batch"),
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("HIGH_SALES_ALERT", "High Sales Alert"),
                            ("IMPORTANT_ALERT", "Important Alert"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("dedupe_key", models.CharField(db_index=True, max_length=255)),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Email template context data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notification_events",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Notification Event",
                "verbose_name_plural": "Email Notification Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "status"],
                        name="notificatio_event_t_1f40fa_idx",
                    ),
                    models.Index(
                        fields=["business", "created_at"],
                        name="notificatio_busines_1d54ea_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "created_at"],
                        name="notificatio_recipie_c42c76_idx",
                    ),
                    models.Index(
                        fields=["dedupe_key"], name="notificatio_dedupe__a1e111_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_type", "recipient_email", "dedupe_key"),
                        name="unique_email_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_emails",
                    models.BooleanField(
                        default=True, help_text="Receive welcome emails"
                    ),
                ),
                (
                    "instant_sale_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive instant email notifications for completed sales",
                    ),
                ),
                (
                    "daily_summary_email",
                    models.BooleanField(
                        default=True, help_text="Receive daily sales summary emails"
                    ),
                ),
                (
                    "important_alerts_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive important system alerts via email",
                    ),
                ),
                (
                    "high_sales_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Receive alerts when sales spike for specific products",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Notification Preference",
                "verbose_name_plural": "Email Notification Preferences",
                "indexes": [
                    models.Index(fields=["user"], name="notificatio_user_id_0299fd_idx")
                ],
            },
        ),
    ]
