# Generated by Django 5.2.5 on 2025-12-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationevent_notificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WELCOME_MANAGER", "Welcome Manager"),
                    ("WELCOME_AGENT", "Welcome Agent"),
                    ("OTP_CODE", "OTP Code"),
                    ("OTP_RESET", "OTP Reset"),
                    ("OTP_VERIFY", "OTP Verify"),
                    ("SALE_INSTANT", "Sale Instant"),
                    ("SALE_BATCH", "Sale Batch"),
                    ("DAILY_SUMMARY", "Daily Summary"),
                    ("HIGH_SALES_ALERT", "High Sales Alert"),
                    ("IMPORTANT_ALERT", "Important Alert"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
