# Generated by Django 5.2.5 on 2025-12-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notificationevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="commission_emails_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Receive commission emails when completing sales (for agents)",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="weekly_digest_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Receive weekly sales summary emails every Friday (for managers)",
            ),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WELCOME_MANAGER", "Welcome Manager"),
                    ("WELCOME_AGENT", "Welcome Agent"),
                    ("OTP_CODE", "OTP Code"),
                    ("OTP_RESET", "OTP Reset"),
                    ("OTP_VERIFY", "OTP Verify"),
                    ("SALE_INSTANT", "Sale Instant"),
                    ("SALE_BATCH", "Sale Batch"),
                    ("DAILY_SUMMARY", "Daily Summary"),
                    ("HIGH_SALES_ALERT", "High Sales Alert"),
                    ("IMPORTANT_ALERT", "Important Alert"),
                    ("AGENT_COMMISSION", "Agent Commission"),
                    ("WEEKLY_DIGEST", "Weekly Digest"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
