# Generated by Django 5.2.5 on 2026-01-15 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_notification_defaults_opt_out"),
        ("tenants", "0030_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("SALE_OCCURRED", "Sale Occurred"),
                            ("USER_SIGNUP", "User Signup"),
                            ("OTP_REQUEST", "OTP Request"),
                            ("SUBSCRIPTION_SUCCESS", "Subscription Success"),
                            ("SUBSCRIPTION_CANCELLED", "Subscription Cancelled"),
                            ("AGENT_COMMISSION", "Agent Commission"),
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("WEEKLY_DIGEST", "Weekly Digest"),
                            ("IMPORTANT_ALERT", "Important Alert"),
                            ("NEW_SIGNUP_OWNER_ALERT", "New Signup Owner Alert"),
                            (
                                "NEW_SUBSCRIPTION_OWNER_ALERT",
                                "New Subscription Owner Alert",
                            ),
                            ("NEW_BUSINESS_OWNER_ALERT", "New Business Owner Alert"),
                            ("SALE_RECEIPT", "Sale Receipt"),
                            ("CUSTOM", "Custom"),
                        ],
                        help_text="Type of email event being sent",
                        max_length=50,
                    ),
                ),
                (
                    "to",
                    models.EmailField(
                        help_text="Primary recipient email", max_length=254
                    ),
                ),
                (
                    "cc",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="CC recipients (comma-separated)",
                    ),
                ),
                (
                    "bcc",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="BCC recipients (comma-separated)",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=255),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Template used (if applicable)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, help_text="Number of send attempts"),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", help_text="Last error message if failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When email was successfully sent",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (sale_id, subscription_id, etc.)",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        help_text="Business this email relates to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="tenants.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User this email relates to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Delivery Log",
                "verbose_name_plural": "Email Delivery Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="notificatio_status_d02558_idx",
                    ),
                    models.Index(
                        fields=["event", "created_at"],
                        name="notificatio_event_fe7058_idx",
                    ),
                    models.Index(
                        fields=["to", "created_at"], name="notificatio_to_38bc5c_idx"
                    ),
                    models.Index(
                        fields=["business", "created_at"],
                        name="notificatio_busines_4d0170_idx",
                    ),
                ],
            },
        ),
    ]
