# Generated by Django 5.2.5 on 2026-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_add_daily_summary_models"),
        ("tenants", "0031_car_hire_models"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="businessemailrecipient",
            name="uniq_daily_recipient_biz_email",
        ),
        migrations.AlterField(
            model_name="businessemailrecipient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailysummarysettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="businessemailrecipient",
            unique_together={("business", "email")},
        ),
    ]
