# Generated by Django 4.2.23 on 2025-08-16 13:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


def column_exists(schema_editor, table, column):
    with schema_editor.connection.cursor() as cursor:
        desc = schema_editor.connection.introspection.get_table_description(cursor, table)
    return any(c.name == column for c in desc)


def ensure_created_at(apps, schema_editor):
    table = "sales_sale"
    col = "created_at"

    if column_exists(schema_editor, table, col):
        # Column exists already; just ensure no NULLs if later set NOT NULL.
        if schema_editor.connection.vendor == "postgresql":
            schema_editor.execute(f'UPDATE "{table}" SET "{col}" = NOW() WHERE "{col}" IS NULL;')
        return

    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "{col}" timestamptz;')
        schema_editor.execute(f'UPDATE "{table}" SET "{col}" = NOW() WHERE "{col}" IS NULL;')
        # If your field is non-nullable in Django, enforce it:
        schema_editor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{col}" SET NOT NULL;')
    else:
        # Local dev safety (SQLite etc)
        schema_editor.execute(f'ALTER TABLE "{table}" ADD COLUMN "{col}" datetime;')


def drop_sale_price_nonneg_if_exists(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    Sale = apps.get_model("sales", "Sale")
    table = Sale._meta.db_table  # should be "sales_sale"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "sale_price_nonneg";')


def add_constraint_if_not_exists(apps, schema_editor, constraint_name, check_expression):
    """
    Add a check constraint only if it doesn't already exist.
    Works for both PostgreSQL and SQLite.
    """
    if schema_editor.connection.vendor == "postgresql":
        sql = f"""
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE c.conname = '{constraint_name}'
            AND t.relname = 'sales_sale'
          ) THEN
            ALTER TABLE sales_sale
              ADD CONSTRAINT {constraint_name} CHECK ({check_expression});
          END IF;
        END $$;
        """
        schema_editor.execute(sql)
    elif schema_editor.connection.vendor == "sqlite":
        # SQLite doesn't support adding constraints to existing tables easily,
        # but check constraints are defined during table creation.
        # For SQLite, we let Django handle it normally via state operations.
        # If constraint already exists in SQLite, we just pass.
        pass


def drop_constraint_if_exists(apps, schema_editor, constraint_name):
    """
    Drop a check constraint only if it exists.
    Works for both PostgreSQL and SQLite.
    """
    if schema_editor.connection.vendor == "postgresql":
        sql = f"""
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1 FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE c.conname = '{constraint_name}'
            AND t.relname = 'sales_sale'
          ) THEN
            ALTER TABLE sales_sale DROP CONSTRAINT {constraint_name};
          END IF;
        END $$;
        """
        schema_editor.execute(sql)
    elif schema_editor.connection.vendor == "sqlite":
        # SQLite doesn't support dropping constraints from existing tables
        # For tests and local dev, we just pass
        pass


def add_price_constraint(apps, schema_editor):
    add_constraint_if_not_exists(apps, schema_editor, "sale_price_nonneg", "price >= 0")


def add_commission_constraint(apps, schema_editor):
    add_constraint_if_not_exists(
        apps, schema_editor, "sale_commission_pct_0_100", "commission_pct >= 0 AND commission_pct <= 100"
    )


def drop_price_constraint(apps, schema_editor):
    drop_constraint_if_exists(apps, schema_editor, "sale_price_nonneg")


def drop_commission_constraint(apps, schema_editor):
    drop_constraint_if_exists(apps, schema_editor, "sale_commission_pct_0_100")


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-created_at"]},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_created_at, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="sale",
                    name="created_at",
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="sale",
            name="commission_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        # Indexes already exist from 0001_initial - no need to add them again
        migrations.RunPython(drop_sale_price_nonneg_if_exists, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_price_constraint, drop_price_constraint),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="sale",
                    constraint=models.CheckConstraint(check=models.Q(("price__gte", 0)), name="sale_price_nonneg"),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_commission_constraint, drop_commission_constraint),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="sale",
                    constraint=models.CheckConstraint(
                        check=models.Q(("commission_pct__gte", 0), ("commission_pct__lte", 100)),
                        name="sale_commission_pct_0_100",
                    ),
                ),
            ],
        ),
    ]
