# Generated by Django 4.2.23 on 2025-08-16 13:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


def column_exists(schema_editor, table, column):
    with schema_editor.connection.cursor() as cursor:
        desc = schema_editor.connection.introspection.get_table_description(cursor, table)
    return any(c.name == column for c in desc)


def ensure_created_at(apps, schema_editor):
    table = "sales_sale"
    col = "created_at"

    if column_exists(schema_editor, table, col):
        # Column exists already; just ensure no NULLs if later set NOT NULL.
        if schema_editor.connection.vendor == "postgresql":
            schema_editor.execute(f'UPDATE "{table}" SET "{col}" = NOW() WHERE "{col}" IS NULL;')
        return

    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "{col}" timestamptz;')
        schema_editor.execute(f'UPDATE "{table}" SET "{col}" = NOW() WHERE "{col}" IS NULL;')
        # If your field is non-nullable in Django, enforce it:
        schema_editor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{col}" SET NOT NULL;')
    else:
        # Local dev safety (SQLite etc)
        schema_editor.execute(f'ALTER TABLE "{table}" ADD COLUMN "{col}" datetime;')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_created_at, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='sale',
                    name='created_at',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        # Indexes already exist from 0001_initial - no need to add them again
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='sale_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('commission_pct__gte', 0), ('commission_pct__lte', 100)), name='sale_commission_pct_0_100'),
        ),
    ]
