# Generated by Django 5.2.5 on 2025-12-01 20:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_backfill_sale_created_and_item_sold_at"),
        ("tenants", "0011_agentinvite_temp_password_hash_and_more"),
        ("timelogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Default commission percentage for phone sales (e.g., 2.00 = 2%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fixed_commission_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed commission per sale (if set, overrides percentage).",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "early_bonus_per_30min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000.00"),
                        help_text="Bonus amount per 30 minutes arrived early (MWK).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "late_penalty_per_30min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("7000.00"),
                        help_text="Penalty amount per 30 minutes arrived late (MWK).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "lateness_penalties_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic lateness penalties based on time logs.",
                    ),
                ),
                (
                    "early_bonus_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic early arrival bonuses based on time logs.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_configs",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "is_active"],
                        name="sales_commi_busines_e3ebad_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "early_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bonus for arriving early.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "late_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Penalty for arriving late.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final commission after bonuses and penalties.",
                        max_digits=12,
                    ),
                ),
                (
                    "early_blocks",
                    models.PositiveIntegerField(default=0, help_text="Number of 30-min blocks arrived early."),
                ),
                (
                    "late_blocks",
                    models.PositiveIntegerField(default=0, help_text="Number of 30-min blocks arrived late."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_commissions",
                        to="tenants.business",
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_record",
                        to="sales.sale",
                    ),
                ),
                (
                    "work_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_commissions",
                        to="timelogs.agentworklog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "created_at"],
                        name="sales_salec_agent_i_15c20f_idx",
                    ),
                    models.Index(
                        fields=["business", "created_at"],
                        name="sales_salec_busines_a0bf92_idx",
                    ),
                ],
            },
        ),
    ]
