# Generated by Django 5.2.5 on 2025-12-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_commissionconfig_salecommission"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("BANK", "Bank"),
                    ("MOBILE_MONEY", "Mobile Money"),
                ],
                db_index=True,
                default="CASH",
                help_text="Payment method used for this sale",
                max_length=20,
            ),
        ),
    ]
