# Generated by Django 5.2.5 on 2025-12-02 10:21
# FIXED: Postgres-safe and idempotent column addition

from django.db import migrations, models, ProgrammingError


def add_payment_method_column_safe(apps, schema_editor):
    """
    Add payment_method column in a Postgres-safe, idempotent way.
    Uses 3-step pattern: add column -> backfill -> set default+NOT NULL
    """
    connection = schema_editor.connection

    if connection.vendor == "postgresql":
        # Postgres: Use IF NOT EXISTS for idempotency
        # Step 1: Add column if it doesn't exist (nullable, no default)
        schema_editor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'sales_sale'
                      AND column_name = 'payment_method'
                ) THEN
                    ALTER TABLE sales_sale
                    ADD COLUMN payment_method VARCHAR(20);
                END IF;
            END $$;
            """
        )

        # Step 2: Backfill NULL values with 'CASH'
        schema_editor.execute(
            """
            UPDATE sales_sale
            SET payment_method = 'CASH'
            WHERE payment_method IS NULL;
            """
        )

        # Step 3: Set default and NOT NULL constraint
        schema_editor.execute(
            """
            ALTER TABLE sales_sale
            ALTER COLUMN payment_method SET DEFAULT 'CASH',
            ALTER COLUMN payment_method SET NOT NULL;
            """
        )

    else:
        # SQLite: Use standard ADD COLUMN with DEFAULT
        # Check if column exists first
        cursor = schema_editor.connection.cursor()
        cursor.execute("PRAGMA table_info(sales_sale)")
        columns = [row[1] for row in cursor.fetchall()]

        if "payment_method" not in columns:
            schema_editor.execute(
                """
                ALTER TABLE sales_sale
                ADD COLUMN payment_method VARCHAR(20) NOT NULL DEFAULT 'CASH';
                """
            )


def remove_payment_method_column(apps, schema_editor):
    """Remove payment_method column if migration is reversed"""
    connection = schema_editor.connection

    if connection.vendor == "postgresql":
        schema_editor.execute(
            """
            ALTER TABLE sales_sale
            DROP COLUMN IF EXISTS payment_method;
            """
        )
    else:
        # For SQLite we keep this defensive; if unsupported on a given version
        # the reverse migration will simply fail, which is acceptable for now.
        cursor = schema_editor.connection.cursor()
        cursor.execute("PRAGMA table_info(sales_sale)")
        columns = [row[1] for row in cursor.fetchall()]

        if "payment_method" in columns:
            schema_editor.execute(
                """
                ALTER TABLE sales_sale
                DROP COLUMN payment_method;
                """
            )


def create_indexes_safe(apps, schema_editor):
    """
    Create indexes in an idempotent way.

    IMPORTANT: SQLite only allows one statement per execute(), so we loop
    and run each CREATE INDEX separately.
    """
    statements = [
        "CREATE INDEX IF NOT EXISTS sales_sale_payment_method_idx " "ON sales_sale (payment_method)",
        "CREATE INDEX IF NOT EXISTS sale_created_at_idx " "ON sales_sale (created_at)",
        "CREATE INDEX IF NOT EXISTS sale_sold_at_idx " "ON sales_sale (sold_at)",
        "CREATE INDEX IF NOT EXISTS sale_loc_created_idx " "ON sales_sale (location_id, created_at)",
        "CREATE INDEX IF NOT EXISTS sale_agent_created_idx " "ON sales_sale (agent_id, created_at)",
    ]

    for sql in statements:
        try:
            schema_editor.execute(sql)
        except ProgrammingError:
            # If an index already exists or backend complains, ignore and continue
            pass


def drop_indexes_safe(apps, schema_editor):
    """
    Drop indexes in an idempotent, SQLite-friendly way.

    Again: one statement per execute() to avoid
    "You can only execute one statement at a time."
    """
    statements = [
        "DROP INDEX IF EXISTS sales_sale_payment_method_idx",
        "DROP INDEX IF EXISTS sale_created_at_idx",
        "DROP INDEX IF EXISTS sale_sold_at_idx",
        "DROP INDEX IF EXISTS sale_loc_created_idx",
        "DROP INDEX IF EXISTS sale_agent_created_idx",
    ]

    for sql in statements:
        try:
            schema_editor.execute(sql)
        except ProgrammingError:
            # If an index never existed on a given DB, ignore and continue.
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_commissionconfig_salecommission"),
    ]

    operations = [
        # First, ensure old indexes are dropped (idempotent)
        migrations.RunPython(
            drop_indexes_safe,
            migrations.RunPython.noop,
        ),
        # Then use SeparateDatabaseAndState for the field addition
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_payment_method_column_safe,
                    remove_payment_method_column,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="sale",
                    name="payment_method",
                    field=models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        db_index=True,
                        default="CASH",
                        help_text="Payment method used for this sale",
                        max_length=20,
                    ),
                ),
            ],
        ),
        # Finally, create all indexes (idempotent)
        migrations.RunPython(
            create_indexes_safe,
            drop_indexes_safe,
        ),
    ]
