# Generated by Django 5.2.5 on 2025-12-17 19:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "1000_add_commission_toggle_and_mode"),
        ("tenants", "0016_add_unique_active_membership_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquorSaleAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liquor_sale_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ID of the LiquorSale this attribution is for",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Reconciliation"),
                            ("reconciled", "Reconciled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sale_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total sale amount (denormalized for performance)",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "attributed_by",
                    models.ForeignKey(
                        help_text="The barman who made this sale",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquor_attributions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attributed_to",
                    models.ForeignKey(
                        help_text="The agent this sale is attributed to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquor_attributions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquor_sale_attributions",
                        to="tenants.business",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquor_attributions_reconciled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "status", "-created_at"],
                        name="sales_liquo_busines_3b6dde_idx",
                    ),
                    models.Index(
                        fields=["attributed_to", "status", "-created_at"],
                        name="sales_liquo_attribu_e4bff2_idx",
                    ),
                    models.Index(
                        fields=["attributed_by", "-created_at"],
                        name="sales_liquo_attribu_184f64_idx",
                    ),
                    models.Index(fields=["liquor_sale_id"], name="sales_liquo_liquor__c393e1_idx"),
                ],
            },
        ),
    ]
