# Generated by Django 5.2.5 on 2025-12-18 13:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "1001_add_liquor_sale_attribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_rolled_back",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this sale has been rolled back/reversed",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="rolled_back_at",
            field=models.DateTimeField(
                blank=True, help_text="When this sale was rolled back", null=True
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="rolled_back_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who rolled back this sale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rolled_back_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SaleRollback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged"),
                            ("RETURNED", "Returned"),
                            ("ERROR", "Data Entry Error"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Reason for rollback",
                        max_length=20,
                    ),
                ),
                (
                    "refunded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a refund was issued to customer",
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount refunded to customer (if any)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "return_to_stock",
                    models.BooleanField(
                        default=False, help_text="Whether item was returned to stock"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the rollback"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When the rollback was performed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who performed the rollback",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rollbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        help_text="The sale that was rolled back",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollbacks",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "sales_sale_rollback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="rollback_created_idx"),
                    models.Index(fields=["sale"], name="rollback_sale_idx"),
                    models.Index(fields=["created_by"], name="rollback_user_idx"),
                ],
            },
        ),
    ]
