# Generated by Django 5.2.5 on 2025-12-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "1002_add_sale_rollback_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="salecommission",
            name="is_reversed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this commission was reversed due to sale rollback",
            ),
        ),
        migrations.AddField(
            model_name="salecommission",
            name="reversed_at",
            field=models.DateTimeField(blank=True, help_text="When this commission was reversed", null=True),
        ),
    ]
